package com.hospital.platform.medication;

import com.hospital.platform.common.error.BusinessException;
import com.hospital.platform.common.error.ErrorCode;
import com.hospital.platform.common.trace.TraceId;
import java.math.BigDecimal;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.sql.Timestamp;
import java.time.Instant;
import java.util.ArrayList;
import java.util.HexFormat;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Set;
import java.util.UUID;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

/**
 * Independent outpatient medication domain. MySQL transactions and conditional updates are the
 * stock authority; no prescription content, allergy detail or token is written to audit/logs.
 */
@Service public class MedicationService {
  private final JdbcTemplate jdbc; private final MedicationSafetyProvider safety;
  public MedicationService(JdbcTemplate jdbc,MedicationSafetyProvider safety){this.jdbc=jdbc;this.safety=safety;}

  @Transactional public PrescriptionView createDraft(long actor,long encounterId,Long supersedesId){
    Map<String,Object> e=doctorEncounter(actor,encounterId); long revision=signedRevision(encounterId);
    if(!"IN_CONSULTATION".equals(text(e,"status")))throw new BusinessException(ErrorCode.PRESCRIPTION_INVALID_STATE);
    if(supersedesId!=null){Map<String,Object> old=one("select * from outpatient_prescription where id=? for update",supersedesId);if(num(old,"encounter_id")!=encounterId||!Set.of("PHARMACY_REJECTED","CANCELLED").contains(text(old,"status")))throw new BusinessException(ErrorCode.PRESCRIPTION_INVALID_STATE);}
    String no="RX"+UUID.randomUUID().toString().replace("-","").substring(0,24).toUpperCase(Locale.ROOT);
    jdbc.update("insert into outpatient_prescription(prescription_no,encounter_id,patient_id,member_id,doctor_id,department_id,medical_record_revision_id,supersedes_prescription_id) values(?,?,?,?,?,?,?,?)",no,encounterId,num(e,"patient_id"),num(e,"member_id"),num(e,"doctor_id"),num(e,"department_id"),revision,supersedesId);
    long id=id(); audit(actor,"CREATE_DRAFT","PRESCRIPTION",id); return view(id);
  }

  @Transactional public PrescriptionView addItem(long actor,long encounterId,long prescriptionId,ItemInput input){
    Map<String,Object> p=doctorPrescription(actor,encounterId,prescriptionId,true); validItem(input);
    Map<String,Object> drug=formularyDrug(p,input.drugId());
    try {jdbc.update("insert into prescription_item(prescription_id,drug_id,drug_code_snapshot,drug_name_snapshot,dosage_form_snapshot,strength_snapshot,dose_amount,dose_unit,route_code,route_name_snapshot,frequency_code,frequency_name_snapshot,duration_value,duration_unit,quantity,quantity_unit,usage_instruction,sort_order) values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",prescriptionId,input.drugId(),text(drug,"drug_code"),text(drug,"generic_name"),text(drug,"dosage_form_name"),decimal(drug,"strength_value").stripTrailingZeros().toPlainString()+" "+text(drug,"strength_unit"),input.doseAmount(),input.doseUnit(),input.routeCode(),routeName(input.routeCode()),input.frequencyCode(),frequencyName(input.frequencyCode()),input.durationValue(),input.durationUnit(),input.quantity(),input.quantityUnit(),clean(input.usageInstruction(),1024),nextSort(prescriptionId));}
    catch(org.springframework.dao.DuplicateKeyException ex){throw new BusinessException(ErrorCode.VALIDATION);}
    touch(prescriptionId,actor); audit(actor,"ADD_ITEM","PRESCRIPTION",prescriptionId); return view(prescriptionId);
  }

  @Transactional public PrescriptionView removeItem(long actor,long encounterId,long prescriptionId,long itemId){
    doctorPrescription(actor,encounterId,prescriptionId,true);
    if(jdbc.update("delete from prescription_item where id=? and prescription_id=?",itemId,prescriptionId)!=1)throw new BusinessException(ErrorCode.NOT_FOUND);
    touch(prescriptionId,actor); audit(actor,"REMOVE_ITEM","PRESCRIPTION",prescriptionId); return view(prescriptionId);
  }

  @Transactional public PrescriptionView sign(long actor,long encounterId,long prescriptionId,VersionInput input){
    Map<String,Object> p=doctorPrescriptionForUpdate(actor,encounterId,prescriptionId);
    requireVersion(p,input.version()); if(!"DRAFT".equals(text(p,"status")))throw new BusinessException(ErrorCode.PRESCRIPTION_IMMUTABLE);
    List<ItemView> items=items(prescriptionId); if(items.isEmpty())throw new BusinessException(ErrorCode.PRESCRIPTION_REQUIRED_FIELD);
    String hash=hash(p,items);
    if(jdbc.update("update outpatient_prescription set status='SIGNED',signed_by=?,signed_at=current_timestamp(3),content_hash=?,version=version+1 where id=? and status='DRAFT' and version=?",actor,hash,prescriptionId,input.version())!=1)throw new BusinessException(ErrorCode.PRESCRIPTION_VERSION_CONFLICT);
    audit(actor,"SIGN","PRESCRIPTION",prescriptionId); return view(prescriptionId);
  }

  @Transactional public PrescriptionView submit(long actor,long encounterId,long prescriptionId,SubmitInput input,boolean overrideAllowed){
    Map<String,Object> p=doctorPrescriptionForUpdate(actor,encounterId,prescriptionId);
    requireVersion(p,input.version()); if(!"SIGNED".equals(text(p,"status")))throw new BusinessException(ErrorCode.PRESCRIPTION_INVALID_STATE);
    List<ItemView> items=items(prescriptionId); if(items.isEmpty())throw new BusinessException(ErrorCode.PRESCRIPTION_REQUIRED_FIELD);
    for(ItemView i:items)formularyDrug(p,i.drugId());
    List<MedicationSafetyProvider.Alert> alerts=safety.check(num(p,"patient_id"),num(p,"member_id"),items.stream().map(ItemView::drugCode).toList());
    persistAlerts(prescriptionId,actor,alerts,input.overrideReason(),overrideAllowed);
    if(jdbc.update("update outpatient_prescription set status='SUBMITTED',version=version+1 where id=? and status='SIGNED' and version=?",prescriptionId,input.version())!=1)throw new BusinessException(ErrorCode.PRESCRIPTION_VERSION_CONFLICT);
    audit(actor,"SUBMIT","PRESCRIPTION",prescriptionId); return view(prescriptionId);
  }

  @Transactional public PrescriptionView cancel(long actor,long encounterId,long prescriptionId,CancelInput input){
    Map<String,Object> p=doctorPrescriptionForUpdate(actor,encounterId,prescriptionId); if(blank(input.reason()))throw new BusinessException(ErrorCode.VALIDATION);
    String status=text(p,"status"); if(!Set.of("DRAFT","SIGNED","SUBMITTED","PHARMACY_APPROVED").contains(status))throw new BusinessException(ErrorCode.PRESCRIPTION_INVALID_STATE);
    if("PHARMACY_APPROVED".equals(status))release(prescriptionId);
    jdbc.update("update outpatient_prescription set status='CANCELLED',cancel_reason=?,version=version+1 where id=?",clean(input.reason(),512),prescriptionId);
    audit(actor,"CANCEL","PRESCRIPTION",prescriptionId); return view(prescriptionId);
  }

  @Transactional public PrescriptionView review(long actor,long prescriptionId,ReviewInput input){
    pharmacy(actor,input.pharmacyId()); Map<String,Object> p=one("select * from outpatient_prescription where id=? for update",prescriptionId);
    prescriptionInPharmacy(p,input.pharmacyId());
    if(!"SUBMITTED".equals(text(p,"status")))throw new BusinessException(ErrorCode.PHARMACY_REVIEW_CONFLICT);
    if(!Set.of("APPROVED","REJECTED").contains(input.decision()))throw new BusinessException(ErrorCode.VALIDATION);
    if("REJECTED".equals(input.decision())&&blank(input.reason()))throw new BusinessException(ErrorCode.VALIDATION);
    if("APPROVED".equals(input.decision()))reserve(prescriptionId,input.pharmacyId());
    String status="APPROVED".equals(input.decision())?"PHARMACY_APPROVED":"PHARMACY_REJECTED";
    if(jdbc.update("update outpatient_prescription set status=?,version=version+1 where id=? and status='SUBMITTED'",status,prescriptionId)!=1)throw new BusinessException(ErrorCode.PHARMACY_REVIEW_CONFLICT);
    jdbc.update("insert into pharmacy_review(prescription_id,pharmacy_id,pharmacist_id,decision,reason_code,reason,trace_id) values(?,?,?,?,?,?,?)",prescriptionId,input.pharmacyId(),actor,input.decision(),clean(input.reasonCode(),64),clean(input.reason(),512),TraceId.get());
    audit(actor,"PHARMACY_"+input.decision(),"PRESCRIPTION",prescriptionId); return view(prescriptionId);
  }

  @Transactional public PrescriptionView dispense(long actor,long prescriptionId,long pharmacyId){
    pharmacy(actor,pharmacyId); Map<String,Object> p=one("select * from outpatient_prescription where id=? for update",prescriptionId);
    if(!"PHARMACY_APPROVED".equals(text(p,"status")))throw new BusinessException(ErrorCode.PHARMACY_DISPENSE_CONFLICT);
    List<Map<String,Object>> rs=jdbc.queryForList("select r.*,l.pharmacy_id from pharmacy_stock_reservation r join pharmacy_inventory_lot l on l.id=r.lot_id where r.prescription_id=? and r.status='RESERVED' for update",prescriptionId);
    if(rs.isEmpty()||rs.stream().anyMatch(x->num(x,"pharmacy_id")!=pharmacyId))throw new BusinessException(ErrorCode.PHARMACY_SCOPE_DENIED);
    jdbc.update("insert into dispensing_record(prescription_id,pharmacy_id,dispenser_id,status) values(?,?,?,'DISPENSING')",prescriptionId,pharmacyId,actor); long record=id();
    for(Map<String,Object> r:rs){BigDecimal q=decimal(r,"quantity"); if(jdbc.update("update pharmacy_inventory_lot set on_hand_quantity=on_hand_quantity-?,reserved_quantity=reserved_quantity-?,version=version+1 where id=? and status='ACTIVE' and expiry_date>=current_date and on_hand_quantity>=? and reserved_quantity>=?",q,q,num(r,"lot_id"),q,q)!=1)throw new BusinessException(ErrorCode.PHARMACY_STOCK_NOT_ENOUGH); jdbc.update("update pharmacy_stock_reservation set status='DISPENSED' where id=?",num(r,"id")); Map<String,Object> item=one("select drug_id from prescription_item where id=?",num(r,"prescription_item_id"));jdbc.update("insert into dispensing_item(dispensing_record_id,prescription_item_id,drug_id,lot_id,quantity,dispenser_id) values(?,?,?,?,?,?)",record,num(r,"prescription_item_id"),num(item,"drug_id"),num(r,"lot_id"),q,actor);}
    jdbc.update("update dispensing_record set status='DISPENSED',completed_at=current_timestamp(3) where id=?",record); jdbc.update("update outpatient_prescription set status='DISPENSED',version=version+1 where id=?",prescriptionId); audit(actor,"DISPENSE","PRESCRIPTION",prescriptionId); return view(prescriptionId);
  }

  @Transactional public ReturnView requestReturn(long patient,long prescriptionId,List<ReturnItemInput> values,String reasonCode,String reason){
    Map<String,Object> p=one("select p.*,d.id dispensing_id,d.pharmacy_id from outpatient_prescription p join dispensing_record d on d.prescription_id=p.id and d.status='DISPENSED' where p.id=? and p.patient_id=? for update",prescriptionId,patient); if(values==null||values.isEmpty()||blank(reasonCode))throw new BusinessException(ErrorCode.VALIDATION);
    String no="RT"+UUID.randomUUID().toString().replace("-","").substring(0,24).toUpperCase(Locale.ROOT); jdbc.update("insert into medication_return_order(return_no,prescription_id,dispensing_record_id,patient_id,pharmacy_id,reason_code,reason,requested_by) values(?,?,?,?,?,?,?,?)",no,prescriptionId,num(p,"dispensing_id"),patient,num(p,"pharmacy_id"),clean(reasonCode,64),clean(reason,512),patient); long id=id();
    for(ReturnItemInput x:values){if(x.quantity()==null||x.quantity().signum()<=0)throw new BusinessException(ErrorCode.VALIDATION);Map<String,Object> item=one("select di.id,di.quantity from dispensing_item di where di.id=? and di.dispensing_record_id=?",x.dispensingItemId(),num(p,"dispensing_id"));BigDecimal completed=jdbc.queryForObject("select coalesce(sum(ri.quantity),0) from medication_return_item ri join medication_return_order ro on ro.id=ri.return_order_id where ri.dispensing_item_id=? and ro.status in ('APPROVED','COMPLETED')",BigDecimal.class,x.dispensingItemId());if(decimal(item,"quantity").subtract(completed==null?BigDecimal.ZERO:completed).compareTo(x.quantity())<0)throw new BusinessException(ErrorCode.RETURN_QUANTITY_EXCEEDED);jdbc.update("insert into medication_return_item(return_order_id,dispensing_item_id,quantity) values(?,?,?)",id,x.dispensingItemId(),x.quantity());}
    audit(patient,"RETURN_REQUEST","RETURN",id);return returnView(id);
  }

  @Transactional public ReturnView completeReturn(long actor,long returnId,boolean restock){Map<String,Object> r=one("select * from medication_return_order where id=? for update",returnId);pharmacy(actor,num(r,"pharmacy_id"));if(!"REQUESTED".equals(text(r,"status")))throw new BusinessException(ErrorCode.PRESCRIPTION_INVALID_STATE);jdbc.update("update medication_return_order set status='COMPLETED',reviewed_by=?,restock_eligible=?,completed_at=current_timestamp(3),version=version+1 where id=?",actor,restock?1:0,returnId);if(restock){List<Map<String,Object>> rows=jdbc.queryForList("select ri.quantity,di.lot_id from medication_return_item ri join dispensing_item di on di.id=ri.dispensing_item_id where ri.return_order_id=?",returnId);for(Map<String,Object>x:rows)jdbc.update("update pharmacy_inventory_lot set on_hand_quantity=on_hand_quantity+?,available_quantity=available_quantity+?,version=version+1 where id=? and status='ACTIVE' and expiry_date>=current_date",decimal(x,"quantity"),decimal(x,"quantity"),num(x,"lot_id"));}audit(actor,"RETURN_COMPLETE","RETURN",returnId);return returnView(returnId);}

  @Transactional(readOnly=true) public List<DrugView> catalog(long actor,long encounterId,String query){Map<String,Object> e=doctorEncounter(actor,encounterId);long hospital=hospital(e);String like="%"+(query==null?"":query.trim())+"%";return jdbc.queryForList("select d.* from hospital_drug_formulary f join drug_catalog d on d.id=f.drug_id where f.hospital_id=? and f.enabled=1 and f.prescribable=1 and f.effective_from<=current_date and (f.effective_to is null or f.effective_to>=current_date) and d.status='ACTIVE' and d.deleted=0 and (d.drug_code like ? or d.generic_name like ?) order by d.drug_code limit 50",hospital,like,like).stream().map(this::drugView).toList();}
  @Transactional(readOnly=true) public List<PrescriptionView> doctorList(long actor,long encounterId){doctorEncounter(actor,encounterId);return jdbc.queryForList("select id from outpatient_prescription where encounter_id=? order by id desc",encounterId).stream().map(x->view(num(x,"id"))).toList();}
  @Transactional(readOnly=true) public PrescriptionView doctorDetail(long actor,long encounterId,long id){doctorPrescription(actor,encounterId,id,false);return view(id);}
  @Transactional(readOnly=true) public List<PrescriptionView> pharmacyQueue(long actor,long pharmacyId,String status){pharmacy(actor,pharmacyId);String s=blank(status)?"SUBMITTED":status;return jdbc.queryForList("select distinct p.id from outpatient_prescription p join visit_encounter e on e.id=p.encounter_id join pharmacy_location pl on pl.id=? left join pharmacy_stock_reservation r on r.prescription_id=p.id left join pharmacy_inventory_lot l on l.id=r.lot_id where p.status=? and e.campus_id=pl.campus_id and (r.id is null or l.pharmacy_id=?) order by p.id",pharmacyId,s,pharmacyId).stream().map(x->view(num(x,"id"))).toList();}
  @Transactional(readOnly=true) public List<PharmacyView> pharmacies(long actor){return jdbc.queryForList("select p.* from pharmacy_location p join pharmacy_user_scope s on s.pharmacy_id=p.id where s.user_id=? and p.status='ACTIVE' order by p.id",actor).stream().map(x->new PharmacyView(num(x,"id"),text(x,"pharmacy_code"),text(x,"pharmacy_name"),number(x,"campus_id"))).toList();}
  @Transactional(readOnly=true) public List<InventoryLotView> inventory(long actor,long pharmacyId){pharmacy(actor,pharmacyId);return jdbc.queryForList("select l.*,d.drug_code,d.generic_name,d.dosage_form_name,d.strength_value,d.strength_unit from pharmacy_inventory_lot l join drug_catalog d on d.id=l.drug_id where l.pharmacy_id=? order by d.drug_code,l.expiry_date",pharmacyId).stream().map(x->new InventoryLotView(num(x,"id"),text(x,"drug_code"),text(x,"generic_name"),text(x,"dosage_form_name"),decimal(x,"strength_value"),text(x,"strength_unit"),text(x,"batch_no"),String.valueOf(x.get("expiry_date")),decimal(x,"on_hand_quantity"),decimal(x,"reserved_quantity"),decimal(x,"available_quantity"),text(x,"status"))).toList();}
  @Transactional public InventoryLotView adjustInventory(long actor,InventoryAdjustmentInput input){
    if(input==null||input.pharmacyId()<=0||input.lotId()<=0||input.deltaQuantity()==null||input.deltaQuantity().signum()==0||blank(input.reasonCode())||badText(input.reasonCode(),64)||badText(input.reason(),512))throw new BusinessException(ErrorCode.VALIDATION);
    pharmacy(actor,input.pharmacyId()); Map<String,Object> lot=one("select * from pharmacy_inventory_lot where id=? and pharmacy_id=? for update",input.lotId(),input.pharmacyId());
    BigDecimal delta=input.deltaQuantity();
    if(jdbc.update("update pharmacy_inventory_lot set on_hand_quantity=on_hand_quantity+?,available_quantity=available_quantity+?,version=version+1 where id=? and pharmacy_id=? and status='ACTIVE' and on_hand_quantity+?>=reserved_quantity and available_quantity+?>=0",delta,delta,input.lotId(),input.pharmacyId(),delta,delta)!=1)throw new BusinessException(ErrorCode.PHARMACY_STOCK_NOT_ENOUGH);
    jdbc.update("insert into pharmacy_inventory_adjustment(pharmacy_id,lot_id,delta_quantity,reason_code,reason,adjusted_by) values(?,?,?,?,?,?)",input.pharmacyId(),input.lotId(),delta,clean(input.reasonCode(),64),clean(input.reason(),512),actor);
    audit(actor,"INVENTORY_ADJUST","INVENTORY_LOT",input.lotId()); return inventoryLot(one("select l.*,d.drug_code,d.generic_name,d.dosage_form_name,d.strength_value,d.strength_unit from pharmacy_inventory_lot l join drug_catalog d on d.id=l.drug_id where l.id=?",num(lot,"id")));
  }
  @Transactional(readOnly=true) public List<PrescriptionView> patientList(long patient){return jdbc.queryForList("select id from outpatient_prescription where patient_id=? and status<>'DRAFT' order by id desc",patient).stream().map(x->view(num(x,"id"))).toList();}
  @Transactional(readOnly=true) public PrescriptionView patientDetail(long patient,long id){Map<String,Object>p=one("select * from outpatient_prescription where id=? and patient_id=?",id,patient);if("DRAFT".equals(text(p,"status")))throw new BusinessException(ErrorCode.NOT_FOUND);return view(id);}
  @Transactional public boolean verifyIntegrity(long actor,long encounterId,long id){doctorPrescription(actor,encounterId,id,false);Map<String,Object> p=one("select * from outpatient_prescription where id=?",id);boolean valid="SIGNED".equals(text(p,"status"))||Set.of("SUBMITTED","PHARMACY_APPROVED","PHARMACY_REJECTED","DISPENSED","CANCELLED").contains(text(p,"status"));boolean ok=valid&&text(p,"content_hash")!=null&&text(p,"content_hash").equals(hash(p,items(id)));audit(actor,ok?"VERIFY_INTEGRITY":"INTEGRITY_FAILURE","PRESCRIPTION",id);return ok;}

  private void persistAlerts(long prescription,long actor,List<MedicationSafetyProvider.Alert> alerts,String override,boolean allowed){jdbc.update("delete from prescription_safety_alert where prescription_id=?",prescription);boolean block=alerts.stream().anyMatch(a->"BLOCK".equals(a.severity()));boolean warning=alerts.stream().anyMatch(a->"WARNING".equals(a.severity()));if(block){for(var a:alerts)jdbc.update("insert into prescription_safety_alert(prescription_id,severity,rule_code,display_message) values(?,?,?,?)",prescription,a.severity(),a.ruleCode(),a.message());audit(actor,"SAFETY_BLOCK","PRESCRIPTION",prescription);throw new BusinessException(ErrorCode.PRESCRIPTION_SAFETY_BLOCKED);}if(warning&&(!allowed||blank(override)))throw new BusinessException(ErrorCode.PRESCRIPTION_OVERRIDE_REQUIRED);for(var a:alerts)jdbc.update("insert into prescription_safety_alert(prescription_id,severity,rule_code,display_message,overridden_by,override_reason) values(?,?,?,?,?,?)",prescription,a.severity(),a.ruleCode(),a.message(),"WARNING".equals(a.severity())?actor:null,"WARNING".equals(a.severity())?clean(override,512):null);if(warning)audit(actor,"SAFETY_OVERRIDE","PRESCRIPTION",prescription);}
  private void reserve(long prescription,long pharmacy){for(ItemView item:items(prescription)){List<Map<String,Object>> lots=jdbc.queryForList("select id from pharmacy_inventory_lot where pharmacy_id=? and drug_id=? and status='ACTIVE' and expiry_date>=current_date and available_quantity>=? order by expiry_date,id",pharmacy,item.drugId(),item.quantity());Map<String,Object> lot=lots.stream().filter(x->jdbc.update("update pharmacy_inventory_lot set available_quantity=available_quantity-?,reserved_quantity=reserved_quantity+?,version=version+1 where id=? and status='ACTIVE' and expiry_date>=current_date and available_quantity>=?",item.quantity(),item.quantity(),num(x,"id"),item.quantity())==1).findFirst().orElseThrow(()->new BusinessException(ErrorCode.PHARMACY_STOCK_NOT_ENOUGH));jdbc.update("insert into pharmacy_stock_reservation(prescription_id,prescription_item_id,lot_id,quantity) values(?,?,?,?)",prescription,item.id(),num(lot,"id"),item.quantity());}}
  private void release(long prescription){List<Map<String,Object>>rs=jdbc.queryForList("select * from pharmacy_stock_reservation where prescription_id=? and status='RESERVED' for update",prescription);for(Map<String,Object>r:rs){BigDecimal q=decimal(r,"quantity");jdbc.update("update pharmacy_inventory_lot set available_quantity=available_quantity+?,reserved_quantity=reserved_quantity-?,version=version+1 where id=? and reserved_quantity>=?",q,q,num(r,"lot_id"),q);jdbc.update("update pharmacy_stock_reservation set status='RELEASED' where id=?",num(r,"id"));}}
  private Map<String,Object> formularyDrug(Map<String,Object> p,long drug){return jdbc.queryForList("select d.* from hospital_drug_formulary f join drug_catalog d on d.id=f.drug_id where f.hospital_id=? and f.drug_id=? and f.enabled=1 and f.prescribable=1 and f.effective_from<=current_date and (f.effective_to is null or f.effective_to>=current_date) and d.status='ACTIVE' and d.deleted=0",hospital(p),drug).stream().findFirst().orElseThrow(()->new BusinessException(ErrorCode.FORMULARY_UNAVAILABLE));}
  private long signedRevision(long encounter){Long id=jdbc.queryForObject("select r.current_revision_id from outpatient_medical_record r join outpatient_medical_record_revision v on v.id=r.current_revision_id where r.encounter_id=? and r.deleted=0 and v.status='SIGNED'",Long.class,encounter);if(id==null)throw new BusinessException(ErrorCode.PRESCRIPTION_REQUIRED_FIELD);Long primary=jdbc.queryForObject("select count(*) from encounter_diagnosis where medical_record_revision_id=? and diagnosis_type='PRIMARY' and status in ('PROVISIONAL','CONFIRMED') and deleted=0",Long.class,id);if(primary==null||primary!=1)throw new BusinessException(ErrorCode.PRESCRIPTION_REQUIRED_FIELD);return id;}
  private Map<String,Object> doctorPrescription(long actor,long encounter,long id,boolean editable){doctorEncounter(actor,encounter);Map<String,Object>p=one("select * from outpatient_prescription where id=? and encounter_id=?",id,encounter);if(editable&&!"DRAFT".equals(text(p,"status")))throw new BusinessException(ErrorCode.PRESCRIPTION_IMMUTABLE);return p;}
  private Map<String,Object> doctorPrescriptionForUpdate(long actor,long encounter,long id){doctorEncounter(actor,encounter);return one("select * from outpatient_prescription where id=? and encounter_id=? for update",id,encounter);}
  private Map<String,Object> doctorEncounter(long user,long encounter){long doctor=doctor(user);return jdbc.queryForList("select * from visit_encounter where id=? and doctor_id=? and deleted=0",encounter,doctor).stream().findFirst().orElseThrow(()->new BusinessException(ErrorCode.PRESCRIPTION_ACCESS_DENIED));}
  private long doctor(long user){Long id=jdbc.query("select id from doctor where user_id=? and deleted=0 and status=1 and published=1",(rs,row)->rs.getLong(1),user).stream().findFirst().orElse(null);if(id==null)throw new BusinessException(ErrorCode.PRESCRIPTION_ACCESS_DENIED);return id;}
  private void pharmacy(long user,long pharmacy){Long count=jdbc.queryForObject("select count(*) from pharmacy_user_scope where user_id=? and pharmacy_id=?",Long.class,user,pharmacy);if(count==null||count!=1)throw new BusinessException(ErrorCode.PHARMACY_SCOPE_DENIED);}
  private void prescriptionInPharmacy(Map<String,Object> prescription,long pharmacy){Long count=jdbc.queryForObject("select count(*) from outpatient_prescription p join visit_encounter e on e.id=p.encounter_id join pharmacy_location pl on pl.id=? where p.id=? and e.campus_id=pl.campus_id",Long.class,pharmacy,num(prescription,"id"));if(count==null||count!=1)throw new BusinessException(ErrorCode.PHARMACY_SCOPE_DENIED);}
  private long hospital(Map<String,Object> p){Long h=jdbc.queryForObject("select hospital_id from department where id=?",Long.class,num(p,"department_id"));if(h==null)throw new BusinessException(ErrorCode.FORMULARY_UNAVAILABLE);return h;}
  private PrescriptionView view(long id){Map<String,Object>p=one("select * from outpatient_prescription where id=?",id);List<ItemView> items=items(id);List<AlertView>alerts=jdbc.queryForList("select severity,rule_code,display_message from prescription_safety_alert where prescription_id=? order by id",id).stream().map(x->new AlertView(text(x,"severity"),text(x,"rule_code"),text(x,"display_message"))).toList();return new PrescriptionView(id,text(p,"prescription_no"),num(p,"encounter_id"),text(p,"status"),num(p,"version"),number(p,"supersedes_prescription_id"),items,alerts,instant(p.get("signed_at")));}
  private List<ItemView> items(long prescription){return jdbc.queryForList("select * from prescription_item where prescription_id=? order by sort_order,id",prescription).stream().map(x->new ItemView(num(x,"id"),num(x,"drug_id"),text(x,"drug_code_snapshot"),text(x,"drug_name_snapshot"),text(x,"dosage_form_snapshot"),text(x,"strength_snapshot"),decimal(x,"dose_amount"),text(x,"dose_unit"),text(x,"route_code"),text(x,"route_name_snapshot"),text(x,"frequency_code"),text(x,"frequency_name_snapshot"),((Number)x.get("duration_value")).intValue(),text(x,"duration_unit"),decimal(x,"quantity"),text(x,"quantity_unit"),text(x,"usage_instruction"))).toList();}
  private DrugView drugView(Map<String,Object>x){return new DrugView(num(x,"id"),text(x,"drug_code"),text(x,"generic_name"),text(x,"dosage_form_code"),text(x,"dosage_form_name"),decimal(x,"strength_value"),text(x,"strength_unit"),text(x,"dose_unit"),text(x,"dispensing_unit"),text(x,"route_default"));}
  private InventoryLotView inventoryLot(Map<String,Object>x){return new InventoryLotView(num(x,"id"),text(x,"drug_code"),text(x,"generic_name"),text(x,"dosage_form_name"),decimal(x,"strength_value"),text(x,"strength_unit"),text(x,"batch_no"),String.valueOf(x.get("expiry_date")),decimal(x,"on_hand_quantity"),decimal(x,"reserved_quantity"),decimal(x,"available_quantity"),text(x,"status"));}
  private ReturnView returnView(long id){Map<String,Object>x=one("select * from medication_return_order where id=?",id);return new ReturnView(id,text(x,"return_no"),text(x,"status"),number(x,"reviewed_by"),Boolean.TRUE.equals(x.get("restock_eligible")));}
  private void validItem(ItemInput x){if(x==null||x.drugId()<=0||positive(x.doseAmount())==false||positive(x.quantity())==false||x.durationValue()<=0||!Set.of("tablet","mL","capsule","bag","piece").contains(x.doseUnit())||!Set.of("tablet","mL","capsule","bag","piece").contains(x.quantityUnit())||!Set.of("DAY").contains(x.durationUnit())||!Set.of("PO","IV","IM","TOPICAL").contains(x.routeCode())||!Set.of("QD","BID","TID","QID","PRN").contains(x.frequencyCode())||badText(x.usageInstruction(),1024))throw new BusinessException(ErrorCode.VALIDATION);}
  private void requireVersion(Map<String,Object>p,int version){if(num(p,"version")!=version)throw new BusinessException(ErrorCode.PRESCRIPTION_VERSION_CONFLICT);}
  private void touch(long id,long actor){jdbc.update("update outpatient_prescription set version=version+1 where id=? and status='DRAFT'",id);}
  private long nextSort(long id){Long n=jdbc.queryForObject("select coalesce(max(sort_order),-1)+1 from prescription_item where prescription_id=?",Long.class,id);return n==null?0:n;}
  private String hash(Map<String,Object>p,List<ItemView> items){StringBuilder b=new StringBuilder("prescriptionNo=").append(text(p,"prescription_no")).append('\n').append("encounter=").append(num(p,"encounter_id")).append('\n').append("revision=").append(num(p,"medical_record_revision_id")).append('\n');for(ItemView i:items)b.append(i.drugCode()).append('|').append(i.drugName()).append('|').append(i.dosageForm()).append('|').append(i.strength()).append('|').append(i.doseAmount().stripTrailingZeros()).append('|').append(i.doseUnit()).append('|').append(i.routeCode()).append('|').append(i.frequencyCode()).append('|').append(i.durationValue()).append('|').append(i.durationUnit()).append('|').append(i.quantity().stripTrailingZeros()).append('|').append(i.quantityUnit()).append('|').append(i.usageInstruction()==null?"<NULL>":i.usageInstruction()).append('\n');try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(b.toString().getBytes(StandardCharsets.UTF_8)));}catch(Exception e){throw new IllegalStateException(e);}}
  private void audit(long actor,String action,String type,long resource){jdbc.update("insert into medication_audit(actor_id,action,resource_type,resource_id,trace_id) values(?,?,?,?,?)",actor,action,type,resource,TraceId.get());}
  private long id(){Long id=jdbc.queryForObject("select last_insert_id()",Long.class);if(id==null)throw new BusinessException(ErrorCode.SYSTEM);return id;}
  private Map<String,Object> one(String sql,Object...args){return jdbc.queryForList(sql,args).stream().findFirst().orElseThrow(()->new BusinessException(ErrorCode.NOT_FOUND));}
  private static boolean positive(BigDecimal n){return n!=null&&n.signum()>0;} private static boolean blank(String s){return s==null||s.trim().isEmpty();}private static boolean badText(String s,int max){return s!=null&&(s.length()>max||s.contains("<")||s.contains(">"));}private static String clean(String s,int max){if(s==null)return null;if(badText(s,max))throw new BusinessException(ErrorCode.VALIDATION);return s.trim();}private static String text(Map<String,Object>x,String k){Object v=x.get(k);return v==null?null:String.valueOf(v);}private static long num(Map<String,Object>x,String k){return ((Number)x.get(k)).longValue();}private static Long number(Map<String,Object>x,String k){Object v=x.get(k);return v instanceof Number n?n.longValue():null;}private static BigDecimal decimal(Map<String,Object>x,String k){Object v=x.get(k);return v==null?null:new BigDecimal(v.toString());}private static Instant instant(Object x){return x instanceof Timestamp t?t.toInstant():x instanceof java.time.LocalDateTime t?t.toInstant(java.time.ZoneOffset.UTC):null;}private static String routeName(String code){return Map.of("PO","口服","IV","静脉","IM","肌注","TOPICAL","外用").get(code);}private static String frequencyName(String code){return Map.of("QD","每日一次","BID","每日两次","TID","每日三次","QID","每日四次","PRN","必要时").get(code);}
  public record ItemInput(long drugId,BigDecimal doseAmount,String doseUnit,String routeCode,String frequencyCode,int durationValue,String durationUnit,BigDecimal quantity,String quantityUnit,String usageInstruction){} public record VersionInput(int version){} public record SubmitInput(int version,String overrideReason){} public record CancelInput(String reason){} public record ReviewInput(long pharmacyId,String decision,String reasonCode,String reason){} public record ReturnItemInput(long dispensingItemId,BigDecimal quantity){} public record InventoryAdjustmentInput(long pharmacyId,long lotId,BigDecimal deltaQuantity,String reasonCode,String reason){} public record DrugView(long id,String drugCode,String genericName,String dosageFormCode,String dosageFormName,BigDecimal strengthValue,String strengthUnit,String doseUnit,String dispensingUnit,String routeDefault){} public record ItemView(long id,long drugId,String drugCode,String drugName,String dosageForm,String strength,BigDecimal doseAmount,String doseUnit,String routeCode,String routeName,String frequencyCode,String frequencyName,int durationValue,String durationUnit,BigDecimal quantity,String quantityUnit,String usageInstruction){} public record AlertView(String severity,String ruleCode,String message){} public record PrescriptionView(long id,String prescriptionNo,long encounterId,String status,long version,Long supersedesPrescriptionId,List<ItemView> items,List<AlertView>alerts,Instant signedAt){} public record PharmacyView(long id,String code,String name,Long campusId){} public record InventoryLotView(long id,String drugCode,String drugName,String dosageForm,BigDecimal strengthValue,String strengthUnit,String batchNo,String expiryDate,BigDecimal onHand,BigDecimal reserved,BigDecimal available,String status){} public record ReturnView(long id,String returnNo,String status,Long reviewedBy,boolean restockEligible){}
}
