<script setup lang="ts">
/* eslint-disable @typescript-eslint/no-explicit-any */
import { onMounted, reactive, ref } from 'vue';
import { ElMessage } from 'element-plus';
import http from '../api/http';
type Room={id:number;campusId:number;buildingId:number;floorId:number;outpatientDepartmentId:number;roomCode:string;roomName:string;roomNumber:string;status:number;sortOrder:number;version:number};
const rows=ref<Room[]>([]), open=ref(false), selected=ref<Room|null>(null), error=ref('');const form=reactive<any>({});const master=reactive<any>({campuses:[],buildings:[],floors:[],outpatientDepartments:[]});
async function load(){try{rows.value=(await http.get('/admin/clinic-rooms')).data.data;const sources=[['campuses','/admin/master/campuses'],['buildings','/admin/master/buildings'],['floors','/admin/master/floors'],['outpatientDepartments','/admin/master/outpatient-departments']] as const;await Promise.all(sources.map(async([k,url])=>{master[k]=(await http.get(url)).data.data;}));}catch(e:any){error.value=e.response?.data?.message??'无法读取诊室';}}
function edit(row?:Room){selected.value=row??null;Object.assign(form,row??{campusId:undefined,buildingId:undefined,floorId:undefined,outpatientDepartmentId:undefined,roomCode:'',roomName:'',roomNumber:'',status:true,sortOrder:0,version:0});open.value=true;}
async function save(){try{const payload={...form,status:!!form.status,sortOrder:Number(form.sortOrder||0),version:Number(form.version||0)};if(selected.value)await http.put(`/admin/clinic-rooms/${selected.value.id}`,payload);else await http.post('/admin/clinic-rooms',payload);ElMessage.success('诊室已保存');open.value=false;await load();}catch(e:any){ElMessage.error(e.response?.data?.message??'保存失败');}}
onMounted(()=>void load());
</script>
<template><section><header><div><h1>诊室管理</h1><p>诊室是排班与候诊的真实主数据，患者、前台和医生使用同一来源。</p></div><el-button type="primary" @click="edit()">新增诊室</el-button></header><el-alert v-if="error" :title="error" type="error" show-icon/><el-table v-else :data="rows"><el-table-column prop="roomCode" label="编码"/><el-table-column prop="roomName" label="名称"/><el-table-column prop="roomNumber" label="房间号"/><el-table-column prop="campusId" label="院区 ID"/><el-table-column prop="outpatientDepartmentId" label="门诊科室 ID"/><el-table-column label="状态"><template #default="s">{{s.row.status?'启用':'停用'}}</template></el-table-column><el-table-column prop="sortOrder" label="排序"/><el-table-column label="操作"><template #default="s"><el-button link type="primary" @click="edit(s.row)">编辑</el-button></template></el-table-column></el-table><el-dialog v-model="open" :title="selected?'编辑诊室':'新增诊室'" width="620px"><el-form label-position="top"><el-row :gutter="12"><el-col :span="12"><el-form-item label="院区"><el-select v-model="form.campusId"><el-option v-for="x in master.campuses" :key="x.id" :value="x.id" :label="x.name"/></el-select></el-form-item></el-col><el-col :span="12"><el-form-item label="楼宇"><el-select v-model="form.buildingId"><el-option v-for="x in master.buildings" :key="x.id" :value="x.id" :label="x.name"/></el-select></el-form-item></el-col></el-row><el-row :gutter="12"><el-col :span="12"><el-form-item label="楼层"><el-select v-model="form.floorId"><el-option v-for="x in master.floors" :key="x.id" :value="x.id" :label="x.name"/></el-select></el-form-item></el-col><el-col :span="12"><el-form-item label="门诊科室"><el-select v-model="form.outpatientDepartmentId"><el-option v-for="x in master.outpatientDepartments" :key="x.id" :value="x.id" :label="x.name"/></el-select></el-form-item></el-col></el-row><el-form-item label="编码"><el-input v-model="form.roomCode"/></el-form-item><el-form-item label="名称"><el-input v-model="form.roomName"/></el-form-item><el-form-item label="房间号"><el-input v-model="form.roomNumber"/></el-form-item><el-form-item label="排序"><el-input-number v-model="form.sortOrder" :min="0"/></el-form-item><el-form-item label="状态"><el-switch v-model="form.status" active-text="启用" inactive-text="停用"/></el-form-item></el-form><template #footer><el-button @click="open=false">取消</el-button><el-button type="primary" @click="save">保存</el-button></template></el-dialog></section></template>
<style scoped>header{display:flex;justify-content:space-between;align-items:center;margin-bottom:18px}header p{color:#64748b}</style>
