<script setup lang="ts">
/* eslint-disable @typescript-eslint/no-explicit-any */
import { ref } from 'vue';
import { ElMessage } from 'element-plus';
import http from '../api/http';
import { useAuthStore } from '../stores/auth';
const status=ref('PENDING_COLLECTION'),specimens=ref<any[]>([]),reviewQueue=ref<any[]>([]),result=ref<any>({specimenId:null,providerEventId:'',items:[{testCode:'TEST-LAB-001',testName:'TEST LAB RESULT',valueType:'NUMERIC',numericValue:0,unitName:'test-unit',referenceLow:0,referenceHigh:10,abnormalFlag:'NORMAL',criticalFlag:false}]});
const auth=useAuthStore(); const can=(permission:string)=>auth.session?.permissions.includes(permission)??false;
function error(e:any,fallback:string){ElMessage.error(e?.response?.data?.message??fallback)}
async function load(){try{specimens.value=(await http.get('/lab/specimens',{params:{status:status.value}})).data.data}catch(e){error(e,'无法读取检验标本工作队列')}}
async function collect(s:any){try{await http.post(`/lab/specimens/${s.id}/collect`,{version:s.version});await load();ElMessage.success('标本已采集')}catch(e){error(e,'采集状态冲突')}}
async function receive(s:any){try{await http.post(`/lab/specimens/${s.id}/receive`,{version:s.version});await load();ElMessage.success('标本已接收')}catch(e){error(e,'接收状态冲突')}}
async function loadReviewQueue(){try{reviewQueue.value=(await http.get('/lab/results',{params:{status:'PRELIMINARY'}})).data.data}catch(e){error(e,'无法读取待审核结果')}}
async function enter(){if(!result.value.specimenId||!result.value.providerEventId)return;try{await http.post('/lab/results',result.value);ElMessage.success('结果已录入，等待审核');await loadReviewQueue();await load()}catch(e){error(e,'录入结果失败')}}
async function verify(row:any){try{await http.post(`/lab/results/${row.id}/verify`);ElMessage.success('结果已审核并生成最终报告');await loadReviewQueue();await load()}catch(e){error(e,'审核结果失败')}}
</script>
<template><section class="workbench"><header><div><h1>检验工作台</h1><p>仅展示当前检验岗位已授权范围内的标本；操作按岗位最小权限启用。</p></div><el-button @click="load">刷新</el-button></header><el-form inline><el-form-item label="标本状态"><el-select v-model="status"><el-option label="待采集" value="PENDING_COLLECTION"/><el-option label="已采集" value="COLLECTED"/><el-option label="已接收" value="RECEIVED"/></el-select></el-form-item><el-button type="primary" @click="load">查询</el-button></el-form><el-table :data="specimens"><el-table-column prop="specimenNo" label="标本号"/><el-table-column prop="specimenType" label="类型"/><el-table-column prop="status" label="状态"/><el-table-column label="操作"><template #default="s"><el-button v-if="can('hospital:clinical:lab:specimen:collect')&&s.row.status==='PENDING_COLLECTION'" link type="primary" @click="collect(s.row)">采集</el-button><el-button v-if="can('hospital:clinical:lab:specimen:receive')&&s.row.status==='COLLECTED'" link type="success" @click="receive(s.row)">接收</el-button></template></el-table-column></el-table><article v-if="can('hospital:clinical:lab:result:entry')" class="panel"><h2>录入测试检验结果</h2><el-form inline><el-form-item label="标本 ID"><el-input-number v-model="result.specimenId" :min="1"/></el-form-item><el-form-item label="Provider Event ID"><el-input v-model="result.providerEventId" placeholder="唯一事件标识"/></el-form-item><el-form-item label="数值"><el-input-number v-model="result.items[0].numericValue"/></el-form-item><el-form-item><el-checkbox v-model="result.items[0].criticalFlag">TEST Critical</el-checkbox></el-form-item><el-button type="danger" @click="enter">录入结果</el-button></el-form></article><article v-if="can('hospital:clinical:lab:result:verify')" class="panel"><header><h2>待审核结果</h2><el-button @click="loadReviewQueue">刷新待审核队列</el-button></header><el-table :data="reviewQueue"><el-table-column prop="resultNo" label="结果号"/><el-table-column prop="status" label="状态"/><el-table-column label="操作"><template #default="s"><el-button type="success" @click="verify(s.row)">审核并生成报告</el-button></template></el-table-column></el-table></article><el-alert v-if="!can('hospital:clinical:lab:result:entry')&&!can('hospital:clinical:lab:result:verify')" title="当前角色无结果录入或审核权限" type="info" show-icon/></section></template>
<style scoped>.workbench{display:grid;gap:16px}.workbench header{display:flex;justify-content:space-between}.panel{background:#fff;border:1px solid #e5e7eb;border-radius:10px;padding:16px}</style>
