<script setup lang="ts">
/* eslint-disable @typescript-eslint/no-explicit-any */
import { onMounted, ref } from 'vue';
import { ElMessage } from 'element-plus';
import http from '../api/http';

type Row = { encounterId:number; queueNo:string; queueStatus:string };
const rows=ref<Row[]>([]), active=ref<Row|null>(null), clinical=ref<any>(null), prescriptions=ref<any[]>([]), current=ref<any>(null), drugs=ref<any[]>([]), orders=ref<any[]>([]), serviceCatalog=ref<any[]>([]), pendingReports=ref<any[]>([]), criticalAlerts=ref<any[]>([]), error=ref('');
const fallbackDiagnosis=()=>[{diagnosisType:'PRIMARY',codeSystem:'TEST',diagnosisCode:'T001',status:'PROVISIONAL'}];
const form=ref<any>({version:0,chiefComplaint:'',presentIllness:'',physicalExamination:'',diagnoses:fallbackDiagnosis()});
const vital=ref<any>({temperatureCelsius:null,pulseBpm:null,respiratoryRate:null,systolicBp:null,diastolicBp:null,spo2Percent:null,heightCm:null,weightKg:null});
const allergy=ref<any>({allergenType:'DRUG',allergenCode:'',allergenName:'',reaction:'',severity:'MODERATE'}), amendReason=ref('');
const drug=ref<any>({drugId:null,doseAmount:1,doseUnit:'tablet',routeCode:'PO',frequencyCode:'TID',durationValue:3,durationUnit:'DAY',quantity:9,quantityUnit:'tablet',usageInstruction:''});
const orderForm=ref<any>({type:'LAB',serviceItemId:null,priority:'ROUTINE',clinicalIndication:'',bodyPart:'',laterality:''});
function message(e:any,fallback:string){ElMessage.error(e?.response?.data?.message??fallback)}
async function rxLoad(){if(!active.value)return;try{prescriptions.value=(await http.get(`/doctor/visits/${active.value.encounterId}/prescriptions`)).data.data;current.value=prescriptions.value[0]??null;if(clinical.value?.currentRecord?.status==='SIGNED')drugs.value=(await http.get(`/doctor/visits/${active.value.encounterId}/prescriptions/drug-catalog`)).data.data}catch{prescriptions.value=[];current.value=null;drugs.value=[]}}
async function diagnosticLoad(){if(!active.value||clinical.value?.currentRecord?.status!=='SIGNED')return;orders.value=(await http.get(`/doctor/visits/${active.value.encounterId}/orders`)).data.data;serviceCatalog.value=(await http.get('/doctor/clinical-service-catalog',{params:{type:orderForm.value.type}})).data.data;pendingReports.value=(await http.get('/doctor/diagnostic-reports/pending')).data.data;criticalAlerts.value=(await http.get('/doctor/critical-alerts')).data.data}
async function loadClinical(){if(!active.value)return;clinical.value=(await http.get(`/doctor/visits/${active.value.encounterId}/clinical`)).data.data;const record=clinical.value.currentRecord;const diagnoses=record?.diagnoses?.map((d:any)=>({diagnosisType:d.type,codeSystem:d.codeSystem,diagnosisCode:d.code,status:d.status}))??[];if(record?.revision)form.value={version:record.version,chiefComplaint:record.revision.chiefComplaint??'',presentIllness:record.revision.presentIllness??'',physicalExamination:record.revision.physicalExamination??'',diagnoses:diagnoses.length?diagnoses:fallbackDiagnosis()};await rxLoad();await diagnosticLoad()}
async function load(){try{error.value='';rows.value=(await http.get('/doctor/visits/workbench')).data.data;active.value=rows.value.find(x=>['CALLED','IN_SERVICE'].includes(x.queueStatus))??null;if(active.value)await loadClinical()}catch(e){error.value='无法读取医生工作台';message(e,error.value)}}
async function select(row:Row){active.value=row;try{await loadClinical()}catch(e){message(e,'无法读取临床记录')}}
async function saveRecord(){if(!active.value)return;try{const r=(await http.put(`/doctor/visits/${active.value.encounterId}/clinical/record/draft`,form.value)).data.data;clinical.value.currentRecord=r;form.value.version=r.version;ElMessage.success('病历草稿已保存')}catch(e){message(e,'保存失败')}}
async function signRecord(){if(!active.value)return;try{await http.post(`/doctor/visits/${active.value.encounterId}/clinical/record/sign`,{version:form.value.version});await loadClinical();ElMessage.success('病历已签署')}catch(e){message(e,'签署病历失败')}}
async function saveVital(){if(!active.value)return;try{await http.post(`/doctor/visits/${active.value.encounterId}/clinical/vitals`,vital.value);await loadClinical();ElMessage.success('生命体征已记录')}catch(e){message(e,'生命体征保存失败')}}
async function saveAllergy(){if(!active.value||!allergy.value.allergenName)return;try{await http.post(`/doctor/visits/${active.value.encounterId}/clinical/allergies`,allergy.value);await loadClinical();ElMessage.success('过敏史已记录')}catch(e){message(e,'过敏史保存失败')}}
async function setAllergyStatus(status:string){if(!active.value)return;try{await http.put(`/doctor/visits/${active.value.encounterId}/clinical/allergy-status`,{status});await loadClinical();ElMessage.success('过敏状态已更新')}catch(e){message(e,'过敏状态更新失败')}}
async function amend(){if(!active.value||!amendReason.value.trim())return;try{await http.post(`/doctor/visits/${active.value.encounterId}/clinical/record/amendments`,{reason:amendReason.value.trim()});amendReason.value='';await loadClinical();ElMessage.success('已创建病历修订草稿')}catch(e){message(e,'创建修订失败')}}
async function create(){if(!active.value)return;try{current.value=(await http.post(`/doctor/visits/${active.value.encounterId}/prescriptions`,{})).data.data;await rxLoad();ElMessage.success('处方草稿已创建')}catch(e){message(e,'请先签署病历并确认主诊断')}}
async function add(){if(!active.value||!current.value||!drug.value.drugId)return;try{current.value=(await http.post(`/doctor/visits/${active.value.encounterId}/prescriptions/${current.value.id}/items`,drug.value)).data.data;await rxLoad();ElMessage.success('药品已加入处方')}catch(e){message(e,'添加药品失败')}}
async function sign(){if(!active.value||!current.value)return;try{await http.post(`/doctor/visits/${active.value.encounterId}/prescriptions/${current.value.id}/sign`,{version:current.value.version});await rxLoad();ElMessage.success('处方已签署')}catch(e){message(e,'处方签署失败')}}
async function submit(){if(!active.value||!current.value)return;try{await http.post(`/doctor/visits/${active.value.encounterId}/prescriptions/${current.value.id}/submit`,{version:current.value.version,overrideReason:''});await rxLoad();ElMessage.success('处方已提交药房')}catch(e){message(e,'处方提交被安全规则阻断或未完成')}}
async function changeOrderType(){orderForm.value.serviceItemId=null;try{serviceCatalog.value=(await http.get('/doctor/clinical-service-catalog',{params:{type:orderForm.value.type}})).data.data}catch(e){message(e,'无法读取临床服务目录')}}
async function createOrder(){if(!active.value||!orderForm.value.serviceItemId||!orderForm.value.clinicalIndication.trim())return;try{const draft=(await http.post(`/doctor/visits/${active.value.encounterId}/orders/${orderForm.value.type}`,orderForm.value)).data.data;await http.post(`/doctor/visits/${active.value.encounterId}/orders/${draft.id}/place`,{version:draft.version});await diagnosticLoad();ElMessage.success('临床申请单已签署并提交')}catch(e){message(e,'创建申请单失败，请确认病历已签署和项目填写完整')}}
async function reviewReport(row:any){try{await http.post(`/doctor/diagnostic-reports/${row.id}/review`,{reason:'E2E74B TEST doctor review'});await diagnosticLoad();ElMessage.success('诊断报告已确认阅览')}catch(e){message(e,'确认报告失败')}}
async function acknowledgeAlert(row:any){try{await http.post(`/doctor/critical-alerts/${row.id}/acknowledge`,{reason:'E2E74B TEST critical acknowledge'});await diagnosticLoad();ElMessage.success('危急结果已确认')}catch(e){message(e,'确认危急结果失败')}}
onMounted(load);
</script>

<template>
  <section class="workbench">
    <header><div><h1>医生工作站</h1><p>门诊病历、生命体征、过敏史、处方与临床申请。</p></div><el-button @click="load">刷新</el-button></header>
    <el-alert v-if="error" :title="error" type="warning" show-icon/>
    <div class="grid"><article class="panel"><h2>今日候诊队列</h2><el-table :data="rows" @row-click="select"><el-table-column prop="queueNo" label="候诊号"/><el-table-column prop="queueStatus" label="状态"/></el-table></article><article class="panel"><h2>当前就诊</h2><el-empty v-if="!active" description="暂无接诊中的患者"/><p v-else>候诊号：{{ active.queueNo }} · {{ active.queueStatus }}</p></article></div>
    <article v-if="active&&clinical" class="panel"><h2>电子病历</h2><el-form :disabled="clinical.currentRecord?.status==='SIGNED'" label-position="top"><el-form-item label="主诉"><el-input v-model="form.chiefComplaint" type="textarea"/></el-form-item><el-form-item label="现病史"><el-input v-model="form.presentIllness" type="textarea"/></el-form-item><el-form-item label="体格检查"><el-input v-model="form.physicalExamination" type="textarea"/></el-form-item><el-form-item label="主诊断"><el-input v-model="form.diagnoses[0].diagnosisCode"/></el-form-item></el-form><div v-if="clinical.currentRecord?.status!=='SIGNED'"><el-button @click="saveRecord">保存草稿</el-button><el-button type="primary" @click="signRecord">签署病历</el-button></div><el-divider>生命体征与过敏史</el-divider><div class="editor"><el-input-number v-model="vital.temperatureCelsius" :min="30" :max="45" placeholder="体温"/><el-input-number v-model="vital.pulseBpm" :min="0" placeholder="脉搏"/><el-button @click="saveVital">记录体征</el-button></div><p>过敏状态：{{ clinical.allergyProfile?.allergyStatus??'UNKNOWN' }}</p><div class="editor"><el-input v-model="allergy.allergenName" placeholder="过敏原名称"/><el-input v-model="allergy.reaction" placeholder="反应"/><el-button @click="saveAllergy">新增过敏史</el-button><el-button @click="setAllergyStatus('NO_KNOWN_ALLERGIES')">确认无已知过敏</el-button></div><div v-if="clinical.currentRecord?.status==='SIGNED'" class="editor"><el-input v-model="amendReason" placeholder="修订原因"/><el-button @click="amend">创建病历修订</el-button></div></article>
    <article v-if="active&&clinical?.currentRecord?.status==='SIGNED'" class="panel"><h2>临床申请</h2><p>申请单绑定当前已签署病历版本；提交后不可在此页面修改。</p><div class="editor"><el-select v-model="orderForm.type" @change="changeOrderType"><el-option label="检验" value="LAB"/><el-option label="影像" value="IMAGING"/><el-option label="检查" value="EXAMINATION"/></el-select><el-select v-model="orderForm.serviceItemId" placeholder="选择服务项目"><el-option v-for="item in serviceCatalog" :key="item.id" :label="item.serviceCode+' · '+item.serviceName" :value="item.id"/></el-select><el-select v-model="orderForm.priority"><el-option label="常规" value="ROUTINE"/><el-option label="紧急" value="URGENT"/><el-option label="特急" value="STAT"/></el-select><el-input v-model="orderForm.clinicalIndication" placeholder="临床指征"/><el-input v-model="orderForm.bodyPart" placeholder="部位（如项目要求）"/><el-input v-model="orderForm.laterality" placeholder="侧别（如项目要求）"/><el-button type="primary" @click="createOrder">开立并提交申请</el-button></div><el-table :data="orders"><el-table-column prop="orderNo" label="申请单号"/><el-table-column prop="type" label="类型"/><el-table-column prop="status" label="状态"/><el-table-column prop="priority" label="优先级"/></el-table></article>
    <article v-if="active&&clinical?.currentRecord?.status==='SIGNED'" class="panel"><h2>待阅诊断结果</h2><el-table :data="pendingReports"><el-table-column prop="reportNo" label="报告号"/><el-table-column prop="type" label="类型"/><el-table-column prop="status" label="状态"/><el-table-column label="操作"><template #default="scope"><el-button type="primary" link @click="reviewReport(scope.row)">确认阅览</el-button></template></el-table-column></el-table><h2>危急结果提醒</h2><el-table :data="criticalAlerts"><el-table-column prop="severity" label="级别"/><el-table-column prop="detectedAt" label="检出时间"/><el-table-column label="操作"><template #default="scope"><el-button type="danger" link @click="acknowledgeAlert(scope.row)">确认危急结果</el-button></template></el-table-column></el-table></article>
    <article v-if="active&&clinical?.currentRecord?.status==='SIGNED'" class="panel"><h2>电子处方</h2><el-button type="primary" @click="create">新建处方草稿</el-button><el-select v-model="current" value-key="id" placeholder="选择处方"><el-option v-for="p in prescriptions" :key="p.id" :label="p.prescriptionNo+' · '+p.status" :value="p"/></el-select><div v-if="current" class="editor"><el-select v-model="drug.drugId" filterable placeholder="选择药品"><el-option v-for="d in drugs" :key="d.id" :label="d.drugCode+' · '+d.genericName" :value="d.id"/></el-select><el-button @click="add">加入药品</el-button><el-button @click="sign">签署处方</el-button><el-button type="success" @click="submit">提交药房审核</el-button></div></article>
  </section>
</template>

<style scoped>
.workbench{display:grid;gap:16px}.workbench>header,.grid{display:flex;gap:16px;justify-content:space-between}.grid{display:grid;grid-template-columns:1fr 1fr}.panel{background:#fff;border:1px solid #e5e7eb;border-radius:10px;padding:16px}.editor{display:flex;gap:8px;flex-wrap:wrap;margin-top:12px}@media(max-width:800px){.grid{grid-template-columns:1fr}}
</style>
