<script setup lang="ts">
import { onMounted,ref,watch } from 'vue';
import { ElMessage,ElMessageBox } from 'element-plus';
import { paymentApi,formatMoney,type Order } from '../api/payment';
import { useAuthStore } from '../stores/auth';
type FinanceRow=Order&{refundNo?:string;reasonCode?:string;anomalyType?:string;resourceType?:string;resourceId?:number};
type Dashboard=Record<string,number>;
const auth=useAuthStore(),tab=ref('registrations'),rows=ref<FinanceRow[]>([]),dashboard=ref<Dashboard>({}),page=ref(1),total=ref(0),status=ref(''),busy=ref(false),error=ref(''),detail=ref<FinanceRow|null>(null),opened=ref(false);
const canRetry=()=>auth.session?.permissions.includes('hospital:refund:retry')??false;
async function loadDashboard(){dashboard.value=(await paymentApi.dashboard()).data.data;}
async function load(){busy.value=true;error.value='';try{if(tab.value==='refunds'){const r=(await paymentApi.refunds(page.value,status.value)).data.data;rows.value=r.records;total.value=r.total;}else if(tab.value==='reconciliation'){rows.value=(await paymentApi.reconciliation()).data.data;total.value=rows.value.length;}else{const type=tab.value==='registrations'?'registration-orders':'payment-orders';const r=(await paymentApi.list(type,page.value,status.value)).data.data;rows.value=r.records;total.value=r.total;}}catch{error.value='财务数据加载失败，请检查权限或稍后重试';}finally{busy.value=false;}}
async function open(row:FinanceRow){try{if(tab.value==='reconciliation'){detail.value=row;}else if(tab.value==='refunds'){detail.value=(await paymentApi.refundDetail(row.id)).data.data;}else{detail.value=(await paymentApi.detail(tab.value==='registrations'?'registration-orders':'payment-orders',row.id)).data.data;}opened.value=true;}catch{ElMessage.error('无法读取订单详情');}}
async function retry(row:FinanceRow){await ElMessageBox.confirm('仅会对失败退款重新提交，不会改变原支付成功事实。确认继续？','退款重试');await paymentApi.retryRefund(row.id);ElMessage.success('已提交退款重试');await load();}
watch([tab,status],()=>{page.value=1;void load();});onMounted(()=>{void loadDashboard();void load();});
</script>
<template><section><h1>财务订单中心</h1><p>金额以分存储、以元展示；数据范围受当前账号的数据权限限制。</p><el-alert v-if="error" :title="error" type="error" show-icon/><el-row :gutter="12" class="cards"><el-col :span="4" v-for="item in [{k:'paidAmountCent',n:'已支付'},{k:'pendingAmountCent',n:'待支付'},{k:'refundedAmountCent',n:'已退款'}]" :key="item.k"><el-card><small>{{item.n}}</small><h2>{{formatMoney(dashboard[item.k]||0)}}</h2></el-card></el-col><el-col :span="4" v-for="item in [{k:'successfulPaymentCount',n:'支付成功'},{k:'pendingPaymentCount',n:'待支付订单'},{k:'refundPendingCount',n:'退款中'},{k:'refundSuccessCount',n:'退款成功'},{k:'anomalyCount',n:'待处理异常'}]" :key="item.k"><el-card><small>{{item.n}}</small><h2>{{dashboard[item.k]||0}}</h2></el-card></el-col></el-row><el-tabs v-model="tab"><el-tab-pane label="挂号订单" name="registrations"/><el-tab-pane label="支付订单" name="payments"/><el-tab-pane label="退款订单" name="refunds"/><el-tab-pane label="对账异常" name="reconciliation"/></el-tabs><template v-if="tab!=='reconciliation'"><el-input v-model="status" placeholder="按状态筛选" clearable style="width:220px"/><el-button @click="load">查询</el-button></template><el-table :data="rows" v-loading="busy" @row-click="open"><el-table-column prop="id" label="ID" width="80"/><el-table-column label="单号"><template #default="{row}">{{row.orderNo||row.paymentNo||row.refundNo}}</template></el-table-column><el-table-column prop="appointmentId" label="预约 ID"/><el-table-column label="金额"><template #default="{row}">{{row.amountCent===undefined?'--':formatMoney(row.amountCent,row.currency)}}</template></el-table-column><el-table-column prop="provider" label="支付渠道"/><el-table-column prop="status" label="状态"/><el-table-column label="操作" width="130"><template #default="{row}"><el-button v-if="tab==='refunds'&&row.status==='FAILED'&&canRetry()" text type="danger" @click.stop="retry(row)">重试</el-button><el-button text @click.stop="open(row)">详情</el-button></template></el-table-column></el-table><div v-if="tab!=='reconciliation'" class="pager"><el-button :disabled="page===1||busy" @click="page--;load()">上一页</el-button>第 {{page}} 页，共 {{total}} 条<el-button :disabled="page*20>=total||busy" @click="page++;load()">下一页</el-button></div><el-drawer v-model="opened" title="资金订单详情"><pre>{{detail}}</pre></el-drawer></section></template>
<style scoped>.cards{margin:16px 0}.pager{margin-top:16px}pre{white-space:pre-wrap;word-break:break-word}</style>
