<script setup lang="ts">
/* eslint-disable @typescript-eslint/no-explicit-any */
import { computed, onMounted, ref } from 'vue';
import { ElMessage, ElMessageBox } from 'element-plus';
import http from '../api/http';
type Schedule={id:number;scheduleDate:string;doctorName:string;departmentName:string;startTime:string;endTime:string}; type Queue={encounterId:number;queueNo:string;status:string;roomName?:string}; type Appointment={id:number;appointmentNo:string;patientNo:string;memberName:string;doctorName:string;departmentName:string;status:string};
const schedules=ref<Schedule[]>([]), scheduleId=ref<number>(), queues=ref<Queue[]>([]), appointments=ref<Appointment[]>([]), keyword=ref(''), error=ref(''), loading=ref(false);
const selectedSchedule=computed(()=>schedules.value.find(x=>x.id===scheduleId.value));
async function loadSchedules(){const d=(await http.get('/admin/schedules',{params:{page:1,pageSize:100}})).data.data;schedules.value=d.records??[];if(!scheduleId.value&&schedules.value.length)scheduleId.value=schedules.value[0].id;}
async function load(){loading.value=true;error.value='';try{await loadSchedules();if(scheduleId.value)queues.value=(await http.get('/admin/visits/queues',{params:{scheduleId:scheduleId.value}})).data.data;const d=(await http.get('/admin/appointments',{params:{page:1,pageSize:50,status:'BOOKED',appointmentNo:keyword.value||undefined}})).data.data;appointments.value=d.records??[];}catch(e:any){error.value=e.response?.data?.message??'无法读取前台工作台数据';}finally{loading.value=false;}}
async function checkin(row:Appointment){try{const data=(await http.post('/admin/visits/check-in',{appointmentId:row.id,paymentOverride:false})).data.data;ElMessage.success(`签到成功，候诊号 ${data.queueNo}`);await load();}catch(e:any){ElMessage.error(e.response?.data?.message??'当前不可签到');}}
async function queueAction(row:Queue,action:'call-next'|'recall'|'skip'|'return'){try{if(action==='call-next')await http.post(`/admin/visits/queues/${scheduleId.value}/call-next`);else{let data:any=undefined;if(action==='skip'||action==='return'){const {value}=await ElMessageBox.prompt('请输入操作原因','候诊操作',{inputValue:'现场候诊处理'});data={reason:value};}await http.post(`/admin/visits/${row.encounterId}/${action}`,data);}ElMessage.success('队列已更新');await load();}catch(e:any){if(e!=='cancel'&&e!=='close')ElMessage.error(e.response?.data?.message??'操作未完成');}}
onMounted(()=>void load());
</script>
<template><section class="desk"><header><div><h1>门诊签到与候诊工作台</h1><p>前台高频操作 · 所有名单和队列来自后端实时数据。</p></div><el-button @click="load">刷新</el-button></header><el-form inline class="filters"><el-form-item label="今日排班"><el-select v-model="scheduleId" filterable @change="load"><el-option v-for="s in schedules" :key="s.id" :value="s.id" :label="`${s.scheduleDate} ${s.startTime} ${s.doctorName} · ${s.departmentName}`"/></el-select></el-form-item><el-form-item label="预约编号"><el-input v-model="keyword" clearable @keyup.enter="load"/></el-form-item><el-button @click="load">查询</el-button></el-form><el-alert v-if="error" :title="error" type="error" show-icon/><el-skeleton v-else-if="loading" :rows="6" animated/><template v-else><el-descriptions v-if="selectedSchedule" :column="3" border><el-descriptions-item label="医生">{{selectedSchedule.doctorName}}</el-descriptions-item><el-descriptions-item label="科室">{{selectedSchedule.departmentName}}</el-descriptions-item><el-descriptions-item label="时段">{{selectedSchedule.startTime}}-{{selectedSchedule.endTime}}</el-descriptions-item></el-descriptions><div class="two"><article><h2>待签到预约</h2><el-table :data="appointments"><el-table-column prop="appointmentNo" label="预约编号"/><el-table-column prop="patientNo" label="患者编号"/><el-table-column prop="memberName" label="就诊人"/><el-table-column prop="doctorName" label="医生"/><el-table-column label="操作"><template #default="s"><el-button type="primary" link @click="checkin(s.row)">签到</el-button></template></el-table-column></el-table></article><article><div class="queue-head"><h2>候诊队列</h2><el-button type="primary" :disabled="!scheduleId" @click="queueAction({encounterId:0,queueNo:'',status:''},'call-next')">叫下一位</el-button></div><el-empty v-if="!queues.length" description="当前暂无候诊患者"/><el-table v-else :data="queues"><el-table-column prop="queueNo" label="候诊号"/><el-table-column prop="status" label="状态"/><el-table-column prop="roomName" label="诊室"/><el-table-column label="操作" width="180"><template #default="s"><el-button v-if="s.row.status==='CALLED'" link @click="queueAction(s.row,'recall')">重叫</el-button><el-button v-if="s.row.status==='CALLED'" type="warning" link @click="queueAction(s.row,'skip')">过号</el-button><el-button v-if="s.row.status==='SKIPPED'" type="success" link @click="queueAction(s.row,'return')">回队列</el-button></template></el-table-column></el-table></article></div></template></section></template>
<style scoped>header,.queue-head{display:flex;justify-content:space-between;align-items:center}.filters{padding:14px;background:#f8fafc;margin:16px 0}.two{display:grid;grid-template-columns:1fr 1fr;gap:20px;margin-top:20px}.two article{background:#fff;border:1px solid #e5e7eb;border-radius:10px;padding:16px}@media(max-width:1000px){.two{grid-template-columns:1fr}}</style>
