<script setup lang="ts">
import { onMounted, ref, watch } from 'vue';
import { paymentApi,formatMoney,type Order } from '../api/payment';
const type=ref('registration-orders'),rows=ref<Order[]>([]),total=ref(0),page=ref(1),status=ref(''),error=ref(''),busy=ref(false),detail=ref<Order|null>(null),opened=ref(false);
async function load(){busy.value=true;try{const data=(await paymentApi.list(type.value,page.value,status.value)).data.data;rows.value=data.records;total.value=data.total;error.value='';}catch{error.value='查询失败，请检查权限或网络。';}finally{busy.value=false;}}
async function open(row:Order){try{detail.value=(await paymentApi.detail(type.value,row.id)).data.data;opened.value=true;}catch{error.value='详情不在您的数据范围内，或缺少查看权限。';}}
watch(type,()=>{page.value=1;status.value='';void load();});onMounted(load);
</script>
<template><section><h1>挂号与支付订单</h1><p>只读查询，仅返回当前科室数据范围内订单。支付状态由提供方验证结果更新。</p><p v-if="error" role="alert">{{error}}</p><el-radio-group v-model="type"><el-radio-button value="registration-orders">挂号订单</el-radio-button><el-radio-button value="payment-orders">支付尝试</el-radio-button></el-radio-group><el-input v-model="status" placeholder="状态筛选，如 PAID / SUCCESS" style="width:260px" clearable/><el-button @click="page=1;load()">查询</el-button>
<el-table :data="rows" v-loading="busy" @row-click="open"><el-table-column prop="id" label="ID"/><el-table-column label="编号"><template #default="{row}">{{row.orderNo||row.paymentNo}}</template></el-table-column><el-table-column prop="appointmentId" label="预约 ID"/><el-table-column prop="registrationOrderId" label="挂号订单 ID"/><el-table-column prop="provider" label="提供方"/><el-table-column label="金额"><template #default="{row}">{{formatMoney(row.amountCent,row.currency)}}</template></el-table-column><el-table-column prop="status" label="状态"/></el-table><el-button :disabled="page===1||busy" @click="page--;load()">上一页</el-button>第 {{page}} 页，共 {{total}} 条<el-button :disabled="page*20>=total||busy" @click="page++;load()">下一页</el-button>
<el-drawer v-model="opened" title="订单详情（只读）"><template v-if="detail"><p>编号：{{detail.orderNo||detail.paymentNo}}</p><p>金额：{{formatMoney(detail.amountCent,detail.currency)}}</p><p>状态：{{detail.status}}</p><p>提供方：{{detail.provider||'不适用'}}</p><p>截止时间：{{detail.paymentDeadline||detail.expiresAt}}</p><p>结清时间：{{detail.paidAt||detail.successAt||'未结清'}}</p><p>版本：{{detail.version}}</p></template></el-drawer></section></template>
