<script setup lang="ts">
/* eslint-disable @typescript-eslint/no-explicit-any */
import { ref } from 'vue';
import { ElMessage,ElMessageBox } from 'element-plus';
import http from '../api/http';
const pharmacyId=ref<number|undefined>(),status=ref('SUBMITTED'),rows=ref<any[]>([]),loading=ref(false),error=ref('');
async function load(){if(!pharmacyId.value){error.value='请输入已授权药房 ID';return}loading.value=true;error.value='';try{rows.value=(await http.get('/pharmacy/prescriptions',{params:{pharmacyId:pharmacyId.value,status:status.value}})).data.data}catch(e:any){error.value=e.response?.data?.message??'无法读取药房队列'}finally{loading.value=false}}
async function review(row:any,decision:'APPROVED'|'REJECTED'){if(!pharmacyId.value)return;try{let reason='';if(decision==='REJECTED')reason=(await ElMessageBox.prompt('拒绝处方必须填写原因。','药师审方',{inputPattern:/\S+/})).value;await http.post(`/pharmacy/prescriptions/${row.id}/review`,{pharmacyId:pharmacyId.value,decision,reasonCode:decision==='REJECTED'?'PHARMACIST_REJECTED':null,reason});ElMessage.success('审核已完成');await load()}catch(e:any){if(e!=='cancel')ElMessage.error(e.response?.data?.message??'审核失败')}}
async function dispense(row:any){if(!pharmacyId.value)return;try{await http.post(`/pharmacy/prescriptions/${row.id}/dispense`,{pharmacyId:pharmacyId.value});ElMessage.success('已完成发药');await load()}catch(e:any){ElMessage.error(e.response?.data?.message??'发药失败')}}
</script>
<template><section><h1>药房工作台</h1><p>仅处理已授权药房范围内的处方；药师不能修改医生已签署的药品内容。</p><el-form inline><el-form-item label="药房 ID"><el-input-number v-model="pharmacyId" :min="1"/></el-form-item><el-form-item label="状态"><el-select v-model="status"><el-option label="待审核" value="SUBMITTED"/><el-option label="已通过待发药" value="PHARMACY_APPROVED"/><el-option label="已发药" value="DISPENSED"/><el-option label="已拒绝" value="PHARMACY_REJECTED"/></el-select></el-form-item><el-button type="primary" :loading="loading" @click="load">查询</el-button></el-form><el-alert v-if="error" :title="error" type="warning" show-icon/><el-table :data="rows"><el-table-column prop="prescriptionNo" label="处方号"/><el-table-column prop="status" label="状态"/><el-table-column label="药品"><template #default="s"><div v-for="i in s.row.items" :key="i.id">{{i.drugName}} · {{i.strength}} · {{i.quantity}}{{i.quantityUnit}}</div></template></el-table-column><el-table-column label="安全提示"><template #default="s"><el-tag v-for="a in s.row.alerts" :key="a.ruleCode" :type="a.severity==='BLOCK'?'danger':'warning'">{{a.severity}}</el-tag></template></el-table-column><el-table-column label="操作"><template #default="s"><el-button v-if="s.row.status==='SUBMITTED'" type="success" link @click="review(s.row,'APPROVED')">通过</el-button><el-button v-if="s.row.status==='SUBMITTED'" type="danger" link @click="review(s.row,'REJECTED')">拒绝</el-button><el-button v-if="s.row.status==='PHARMACY_APPROVED'" type="primary" link @click="dispense(s.row)">发药</el-button></template></el-table-column></el-table></section></template>
