<script setup lang="ts">
import { computed, onMounted, ref } from 'vue';
import { useAuthStore } from '../stores/auth';
import { paymentApi, formatMoney, type FeeRule } from '../api/payment';
import http from '../api/http';
const auth=useAuthStore(), rows=ref<FeeRule[]>([]), error=ref(''), busy=ref(false), opened=ref(false);
const canCreate=computed(()=>auth.session?.permissions.includes('hospital:fee:create'));
const canUpdate=computed(()=>auth.session?.permissions.includes('hospital:fee:update'));
const fresh=():FeeRule=>({ruleCode:'',hospitalId:1,campusId:null,departmentId:null,clinicTypeId:null,doctorTitleId:null,amountCent:0,currency:'CNY',effectiveFrom:new Date().toISOString(),effectiveTo:null,status:1,priority:0,version:0});
const form=ref<FeeRule>(fresh());
const amountYuan=ref('0.00');
type Policy={id:number;name:string;paymentRequired:boolean|number;version:number};
const policies=ref<Policy[]>([]);
async function load(){busy.value=true;try{rows.value=(await paymentApi.fees()).data.data;policies.value=(await http.get('/admin/fee-rules/clinic-policies')).data.data;error.value='';}catch{error.value='加载失败，请检查权限或网络。';}finally{busy.value=false;}}
function centToYuan(value:number){return (value/100).toFixed(2);}
function yuanToCent(value:string){if(!/^\d+(\.\d{1,2})?$/.test(value))throw new Error('INVALID_MONEY');const [whole,fraction='']=value.split('.');const cents=Number(whole)*100+Number((fraction+'00').slice(0,2));if(!Number.isSafeInteger(cents)||cents>1_000_000_000_000)throw new Error('INVALID_MONEY');return cents;}
function utcInstant(value:string|null){if(!value)return null;return /(?:Z|[+-]\d{2}:\d{2})$/.test(value)?value:`${value}Z`;}
function edit(row?:FeeRule){form.value=row?{...row}:fresh();amountYuan.value=centToYuan(form.value.amountCent);opened.value=true;}
async function save(){if(busy.value)return;try{form.value.amountCent=yuanToCent(amountYuan.value);}catch{error.value='金额仅支持最多两位小数，例如 10.50。';return;}busy.value=true;try{await paymentApi.save({...form.value,effectiveFrom:utcInstant(form.value.effectiveFrom)!,effectiveTo:utcInstant(form.value.effectiveTo)});opened.value=false;await load();}catch{error.value='保存失败：请检查字段、引用 ID 和有效期；版本冲突时请刷新后编辑。';}finally{busy.value=false;}}
async function toggle(row:FeeRule){try{await paymentApi.save({...row,status:row.status===1?0:1,effectiveFrom:utcInstant(row.effectiveFrom)!,effectiveTo:utcInstant(row.effectiveTo)});await load();}catch{error.value='状态修改失败，请刷新后重试。';}}
async function policy(row:Policy){try{await http.put(`/admin/fee-rules/clinic-policies/${row.id}`,{paymentRequired:!row.paymentRequired,version:row.version});await load();}catch{error.value='收费策略更新失败，请刷新检查版本。';}}
onMounted(load);
</script>
<template><section><h1>挂号费规则</h1><p>金额以“元”录入，提交时会精确转换为“分”。匹配顺序：职称、门诊类型、科室、院区的精细规则优先；同级按优先级降序、ID 升序。订单创建后金额不随规则变化。</p><p v-if="error" role="alert">{{error}}</p><el-button v-if="canCreate" type="primary" @click="edit()">新增规则</el-button><el-button @click="load" :loading="busy">刷新</el-button>
<el-table :data="rows" v-loading="busy"><el-table-column prop="ruleCode" label="规则编号"/><el-table-column prop="hospitalId" label="医院 ID"/><el-table-column prop="clinicTypeId" label="门诊类型 ID"/><el-table-column label="金额"><template #default="{row}">{{formatMoney(row.amountCent,row.currency)}}</template></el-table-column><el-table-column prop="priority" label="优先级"/><el-table-column prop="effectiveFrom" label="生效时间"/><el-table-column prop="effectiveTo" label="截止时间（不含）"/><el-table-column label="状态"><template #default="{row}">{{row.status===1?'启用':'停用'}}</template></el-table-column><el-table-column label="操作"><template #default="{row}"><el-button v-if="canUpdate" text @click="edit(row)">编辑</el-button><el-button v-if="canUpdate" text @click="toggle(row)">{{row.status===1?'停用':'启用'}}</el-button></template></el-table-column></el-table>
<h2>门诊收费策略</h2><p>开启“必须配置价格”后，未匹配有效规则将拒绝生成收费订单；关闭时无规则兼容为零元。</p><el-table :data="policies"><el-table-column prop="id" label="ID"/><el-table-column prop="name" label="门诊类型"/><el-table-column label="必须配置价格"><template #default="{row}">{{row.paymentRequired?'是':'否'}} <el-button v-if="canUpdate" text @click="policy(row)">切换</el-button></template></el-table-column></el-table>
<el-dialog v-model="opened" title="挂号费规则" width="640px"><el-form label-width="150px" @submit.prevent="save"><el-form-item label="规则编号"><el-input v-model="form.ruleCode" maxlength="64"/></el-form-item><el-form-item label="医院 ID"><el-input-number v-model="form.hospitalId" :min="1" :precision="0"/></el-form-item><el-form-item v-for="field in (['campusId','departmentId','clinicTypeId','doctorTitleId'] as const)" :key="field" :label="({campusId:'院区 ID（可空）',departmentId:'科室 ID（可空）',clinicTypeId:'门诊类型 ID（可空）',doctorTitleId:'职称 ID（可空）'})[field]"><el-input-number v-model="form[field]" :min="1" :precision="0"/></el-form-item><el-form-item label="金额（元 / CNY）"><el-input v-model.trim="amountYuan" inputmode="decimal" placeholder="例如 10.50"/><span>{{formatMoney((/^\d+(\.\d{1,2})?$/.test(amountYuan)?Math.round(Number(amountYuan)*100):0))}}</span></el-form-item><el-form-item label="生效时间"><el-date-picker v-model="form.effectiveFrom" type="datetime" value-format="YYYY-MM-DDTHH:mm:ssZ"/></el-form-item><el-form-item label="截止时间（可空）"><el-date-picker v-model="form.effectiveTo" type="datetime" value-format="YYYY-MM-DDTHH:mm:ssZ" clearable/></el-form-item><el-form-item label="优先级"><el-input-number v-model="form.priority" :precision="0"/></el-form-item><el-form-item label="状态"><el-select v-model="form.status"><el-option :value="1" label="启用"/><el-option :value="0" label="停用"/></el-select></el-form-item><el-button type="primary" native-type="submit" :loading="busy">保存</el-button></el-form></el-dialog></section></template>
