package com.hospital.platform.iam.interfaces;
import com.hospital.platform.common.api.ApiResponse; import com.hospital.platform.common.trace.TraceId; import com.hospital.platform.iam.application.AuthService; import jakarta.validation.Valid; import jakarta.validation.constraints.NotBlank; import jakarta.validation.constraints.Size; import java.util.List; import java.util.Map; import org.springframework.security.access.prepost.PreAuthorize; import org.springframework.web.bind.annotation.*;
@RestController @RequestMapping("/api/v1/admin") public class AdminController { private final AuthService auth; private final AdminQueryService query; public AdminController(AuthService auth,AdminQueryService query){this.auth=auth;this.query=query;}
 @GetMapping("/users") @PreAuthorize("hasAuthority('system:user:list')") public ApiResponse<List<Map<String,Object>>> users(@org.springframework.security.core.annotation.AuthenticationPrincipal com.hospital.platform.common.security.AuthenticatedUser user,@RequestParam(required=false) Long departmentId,@RequestParam(required=false) Long organizationId,@RequestParam(required=false) Long userId){return ApiResponse.success(auth.users(user,departmentId,organizationId,userId),TraceId.get());}
 @PostMapping("/users") @PreAuthorize("hasAuthority('system:user:create')") public ApiResponse<Void> create(@Valid @RequestBody CreateUserRequest r){auth.createUser(r.username(),r.password(),r.displayName());return ApiResponse.success(null,TraceId.get());}
 @PutMapping("/users/{id}") @PreAuthorize("hasAuthority('system:user:update')") public ApiResponse<Void> update(@PathVariable long id,@Valid @RequestBody UpdateUserRequest r){auth.updateUser(id,r.displayName());return ApiResponse.success(null,TraceId.get());}
 @PutMapping("/users/{id}/roles") @PreAuthorize("hasAuthority('system:user:update')") public ApiResponse<Void> userRoles(@PathVariable long id,@RequestBody RoleAssignment r){auth.assignRoles(id,r.roleIds());return ApiResponse.success(null,TraceId.get());}
 @PostMapping("/users/{id}/disable") @PreAuthorize("hasAuthority('system:user:disable')") public ApiResponse<Void> disable(@PathVariable long id){auth.disableUser(id);return ApiResponse.success(null,TraceId.get());}
 @GetMapping("/roles") @PreAuthorize("hasAuthority('system:role:list')") public ApiResponse<List<Map<String,Object>>> roles(){return ApiResponse.success(query.roles(),TraceId.get());}
 @PostMapping("/roles") @PreAuthorize("hasAuthority('system:role:create')") public ApiResponse<Void> createRole(@Valid @RequestBody CreateRoleRequest r){query.createRole(r.roleCode(),r.roleName(),r.dataScope());return ApiResponse.success(null,TraceId.get());}
 @GetMapping("/roles/{id}/permissions") @PreAuthorize("hasAuthority('system:role:list')") public ApiResponse<List<Long>> rolePermissionIds(@PathVariable long id){return ApiResponse.success(query.rolePermissionIds(id),TraceId.get());}
 @PutMapping("/roles/{id}/permissions") @PreAuthorize("hasAuthority('system:role:update')") public ApiResponse<Void> rolePermissions(@PathVariable long id,@RequestBody PermissionAssignment r){query.replaceRolePermissions(id,r.permissionIds());return ApiResponse.success(null,TraceId.get());}
 @GetMapping("/permissions") @PreAuthorize("hasAuthority('system:permission:list')") public ApiResponse<List<Map<String,Object>>> permissions(){return ApiResponse.success(query.permissions(),TraceId.get());}
 @GetMapping("/menus") @PreAuthorize("hasAuthority('system:menu:list')") public ApiResponse<List<Map<String,Object>>> menus(){return ApiResponse.success(query.menus(),TraceId.get());}
 @GetMapping("/organizations") @PreAuthorize("hasAuthority('system:organization:list')") public ApiResponse<List<Map<String,Object>>> organizations(){return ApiResponse.success(query.organizations(),TraceId.get());}
 public record CreateUserRequest(@NotBlank @Size(max=64) String username,@NotBlank @Size(min=12,max=128) String password,@NotBlank @Size(max=128) String displayName){} public record UpdateUserRequest(@NotBlank @Size(max=128) String displayName){} public record RoleAssignment(List<Long> roleIds){} public record CreateRoleRequest(@NotBlank @Size(max=64) String roleCode,@NotBlank @Size(max=128) String roleName,@NotBlank @Size(max=32) String dataScope){} public record PermissionAssignment(List<Long> permissionIds){}
}
