package com.hospital.platform.iam.interfaces;
import com.hospital.platform.common.api.ApiResponse; import com.hospital.platform.common.security.AuthenticatedUser; import com.hospital.platform.common.trace.TraceId; import com.hospital.platform.iam.application.AuthService; import com.hospital.platform.iam.application.TokenService; import jakarta.servlet.http.HttpServletRequest; import jakarta.validation.Valid; import jakarta.validation.constraints.NotBlank; import jakarta.validation.constraints.Size; import java.util.Map; import org.springframework.http.HttpStatus; import org.springframework.security.core.annotation.AuthenticationPrincipal; import org.springframework.web.bind.annotation.*;
@RestController @RequestMapping("/api/v1/auth") public class AuthController { private final AuthService auth; public AuthController(AuthService auth){this.auth=auth;}
 @PostMapping("/login") public ApiResponse<TokenService.TokenPair> login(@Valid @RequestBody LoginRequest r,HttpServletRequest req){return ApiResponse.success(auth.login(r.username(),r.password(),r.clientType(),ip(req),req.getHeader("User-Agent")),TraceId.get());}
 @PostMapping("/refresh") public ApiResponse<TokenService.TokenPair> refresh(@Valid @RequestBody RefreshRequest r,HttpServletRequest req){return ApiResponse.success(auth.refresh(r.refreshToken(),r.clientType(),ip(req),req.getHeader("User-Agent")),TraceId.get());}
 @PostMapping("/logout") @ResponseStatus(HttpStatus.NO_CONTENT) public void logout(@Valid @RequestBody LogoutRequest r){auth.logout(r.refreshToken());}
 @GetMapping("/me") public ApiResponse<Map<String,Object>> me(@AuthenticationPrincipal AuthenticatedUser user){return ApiResponse.success(auth.me(user),TraceId.get());}
 @PutMapping("/password") @ResponseStatus(HttpStatus.NO_CONTENT) public void password(@AuthenticationPrincipal AuthenticatedUser user,@Valid @RequestBody ChangePasswordRequest r){auth.password(user,r.oldPassword(),r.newPassword());}
 private String ip(HttpServletRequest r){String x=r.getHeader("X-Forwarded-For");return x==null?r.getRemoteAddr():x.split(",")[0].trim();}
 public record LoginRequest(@NotBlank @Size(max=64) String username,@NotBlank @Size(min=12,max=128) String password,@NotBlank @Size(max=32) String clientType){} public record RefreshRequest(@NotBlank String refreshToken,@NotBlank @Size(max=32) String clientType){} public record LogoutRequest(@NotBlank String refreshToken){} public record ChangePasswordRequest(@NotBlank String oldPassword,@NotBlank @Size(min=12,max=128) String newPassword){}
}
