package com.hospital.platform.patient;

import com.hospital.platform.common.api.PageResponse;
import com.hospital.platform.common.error.BusinessException;
import com.hospital.platform.common.error.ErrorCode;
import com.hospital.platform.iam.application.PatientTokenService;
import com.hospital.platform.iam.application.RedisRateLimiter;
import java.time.Duration;
import java.time.LocalDate;
import java.util.*;
import org.springframework.dao.DuplicateKeyException;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Service
public class PatientIdentityService {
  private static final Set<String> RELATIONSHIPS = Set.of("SELF", "CHILD", "PARENT", "SPOUSE", "OTHER");
  private static final Set<String> ID_TYPES = Set.of("CN_ID", "PASSPORT", "HK_MACAU", "TAIWAN", "OTHER");
  private final JdbcTemplate jdbc; private final PatientCrypto crypto; private final SmsCodeProvider sms; private final RedisRateLimiter limiter; private final org.springframework.data.redis.core.StringRedisTemplate redis; private final PatientTokenService tokens;
  public PatientIdentityService(JdbcTemplate jdbc, PatientCrypto crypto, SmsCodeProvider sms, RedisRateLimiter limiter, org.springframework.data.redis.core.StringRedisTemplate redis, PatientTokenService tokens) { this.jdbc=jdbc;this.crypto=crypto;this.sms=sms;this.limiter=limiter;this.redis=redis;this.tokens=tokens; }

  public SendCodeResult sendCode(String mobile, String ip) {
    String normalized = mobile(mobile); String mobileHash=crypto.hmac(normalized);
    limiter.check("hospital:patient:sms:mobile:"+mobileHash,1,Duration.ofSeconds(60)); limiter.check("hospital:patient:sms:ip:"+ip,10,Duration.ofMinutes(1));
    SmsCodeProvider.SentCode sent=sms.send(normalized); redis.opsForValue().set(smsKey(mobileHash),crypto.hmac("sms:"+sent.code())+"|0",Duration.ofSeconds(sent.expiresInSeconds()));
    return new SendCodeResult(sent.expiresInSeconds(),sent.testOnly()?sent.code():null);
  }
  @Transactional public PatientTokenService.TokenPair login(String mobile, String code, String client, String ip, String userAgent) {
    if (!Set.of("WEB_PATIENT","MINI_PROGRAM_PATIENT").contains(client)) throw new BusinessException(ErrorCode.VALIDATION);
    String normalized=mobile(mobile), mobileHash=crypto.hmac(normalized), key=smsKey(mobileHash), value=redis.opsForValue().get(key);
    if (value==null) throw new BusinessException(ErrorCode.SMS_CODE_EXPIRED); String[] parts=value.split("\\|",-1);
    if (parts.length!=2 || !parts[0].equals(crypto.hmac("sms:"+code))) { int attempts=parts.length==2?Integer.parseInt(parts[1])+1:5; if(attempts>=5)redis.delete(key);else redis.opsForValue().set(key,parts[0]+"|"+attempts,Duration.ofSeconds(300)); throw new BusinessException(ErrorCode.SMS_CODE_INVALID); }
    redis.delete(key); Long id=jdbc.query("select id from patient where mobile_hash=? and deleted=0",(rs,n)->rs.getLong(1),mobileHash).stream().findFirst().orElse(null);
    if(id==null){String patientNo="P"+UUID.randomUUID().toString().replace("-","").toUpperCase(Locale.ROOT);jdbc.update("insert into patient(patient_no,name_ciphertext,mobile_encrypted,mobile_hash,real_name_status) values(?,?,?,?, 'UNVERIFIED')",patientNo,crypto.encrypt("未设置"),crypto.encrypt(normalized),mobileHash);id=jdbc.queryForObject("select id from patient where patient_no=?",Long.class,patientNo);}
    return tokens.issue(id,client,ip,userAgent);
  }
  public PatientTokenService.TokenPair refresh(String refresh,String client,String ip,String ua){return tokens.refresh(refresh,client,ip,ua);} public void logout(String refresh){tokens.revoke(refresh);}
  public PatientSelfDto me(long patientId){Map<String,Object> row=patient(patientId);return new PatientSelfDto(text(row,"patient_no"),crypto.decrypt(text(row,"name_ciphertext")),text(row,"gender"),date(row,"birth_date"),maskMobile(crypto.decrypt(text(row,"mobile_encrypted"))),text(row,"real_name_status"),number(row,"default_member_id"));}
  @Transactional public void updateProfile(long patientId, ProfileRequest request){if(request.name()==null||request.name().isBlank())throw new BusinessException(ErrorCode.VALIDATION);jdbc.update("update patient set name_ciphertext=?,gender=?,birth_date=? where id=? and status=1 and deleted=0",crypto.encrypt(text(request.name())),gender(request.gender()),request.birthDate(),patientId);}
  public List<MemberDto> members(long patientId){return jdbc.queryForList("select * from patient_member where patient_id=? and deleted=0 order by is_self desc,id",patientId).stream().map(this::memberDto).toList();}
  public MemberDto member(long patientId,long memberId){return memberDto(owned(patientId,memberId));}
  @Transactional public long createMember(long patientId, MemberRequest request){return saveMember(patientId,null,request);}
  @Transactional public void updateMember(long patientId,long memberId,MemberRequest request){saveMember(patientId,memberId,request);}
  @Transactional public void disableMember(long patientId,long memberId){owned(patientId,memberId);jdbc.update("update patient_member set status='DISABLED',version=version+1 where id=?",memberId);jdbc.update("update patient set default_member_id=null where id=? and default_member_id=?",patientId,memberId);}
  @Transactional public void defaultMember(long patientId,long memberId){Map<String,Object> member=owned(patientId,memberId);if(!"ACTIVE".equals(text(member,"status")))throw new BusinessException(ErrorCode.VALIDATION);jdbc.update("update patient set default_member_id=? where id=?",memberId,patientId);}
  public PageResponse<AdminPatientDto> adminPatients(String patientNo,String mobile,String idNumber,int page,int pageSize){List<Object> args=new ArrayList<>();String where="p.deleted=0";if(patientNo!=null&&!patientNo.isBlank()){where+=" and p.patient_no=?";args.add(patientNo.trim());}if(mobile!=null&&!mobile.isBlank()){where+=" and p.mobile_hash=?";args.add(crypto.hmac(mobile(mobile)));}if(idNumber!=null&&!idNumber.isBlank()){where+=" and exists(select 1 from patient_member pm where pm.patient_id=p.id and pm.deleted=0 and pm.id_number_hash=?)";args.add(crypto.hmac(identity(idNumber)));}Long total=jdbc.queryForObject("select count(*) from patient p where "+where,Long.class,args.toArray());List<Object> rows=new ArrayList<>(args);rows.add(pageSize);rows.add((page-1)*pageSize);return new PageResponse<>(page,pageSize,total,jdbc.queryForList("select p.*, (select count(*) from patient_member pm where pm.patient_id=p.id and pm.deleted=0) member_count from patient p where "+where+" order by p.id desc limit ? offset ?",rows.toArray()).stream().map(this::adminDto).toList());}
  public AdminPatientDto adminPatient(long id){return adminDto(patient(id));}
  @Transactional public void disablePatient(long id){patient(id);jdbc.update("update patient set status=0,token_version=token_version+1 where id=?",id);tokens.revokeAll(id);}
  private long saveMember(long patientId,Long memberId,MemberRequest r){if(!RELATIONSHIPS.contains(r.relationship()))throw new BusinessException(ErrorCode.VALIDATION);boolean self="SELF".equals(r.relationship()); if(self&&memberId==null&&jdbc.queryForObject("select count(*) from patient_member where patient_id=? and is_self=1 and deleted=0",Long.class,patientId)>0)throw new BusinessException(ErrorCode.MEMBER_SELF_DUPLICATED);String name=text(r.name());if(name==null||name.isBlank())throw new BusinessException(ErrorCode.VALIDATION);String nameHash=crypto.hmac(name.trim());String idType=r.idType()==null?null:r.idType().trim();String normalizedId=r.idNumber()==null||r.idNumber().isBlank()?null:identity(r.idNumber());if(normalizedId!=null){if(!ID_TYPES.contains(idType))throw new BusinessException(ErrorCode.IDENTITY_INVALID);validateIdentity(idType,normalizedId,r.birthDate(),r.gender());if(memberId==null&&jdbc.queryForObject("select count(*) from patient_member where id_number_hash=? and deleted=0 and status='ACTIVE'",Long.class,crypto.hmac(normalizedId))>0)throw new BusinessException(ErrorCode.IDENTITY_DUPLICATED);}String mobile=r.mobile()==null||r.mobile().isBlank()?null:mobile(r.mobile());if("CHILD".equals(r.relationship())&&r.guardianMemberId()!=null)owned(patientId,r.guardianMemberId());try{if(memberId==null){String no="M"+UUID.randomUUID().toString().replace("-","").toUpperCase(Locale.ROOT);jdbc.update("insert into patient_member(patient_id,member_no,relationship_code,name_encrypted,name_hash,gender,birth_date,id_type,id_number_encrypted,id_number_hash,mobile_encrypted,mobile_hash,is_self,real_name_status,status,guardian_member_id) values(?,?,?,?,?,?,?,?,?,?,?,?,?,'UNVERIFIED','ACTIVE',?)",patientId,no,r.relationship(),crypto.encrypt(name),nameHash,gender(r.gender()),r.birthDate(),idType,crypto.encrypt(normalizedId),normalizedId==null?null:crypto.hmac(normalizedId),crypto.encrypt(mobile),mobile==null?null:crypto.hmac(mobile),self?1:0,r.guardianMemberId());return jdbc.queryForObject("select id from patient_member where member_no=?",Long.class,no);}owned(patientId,memberId);jdbc.update("update patient_member set relationship_code=?,name_encrypted=?,name_hash=?,gender=?,birth_date=?,id_type=?,id_number_encrypted=coalesce(?,id_number_encrypted),id_number_hash=coalesce(?,id_number_hash),mobile_encrypted=coalesce(?,mobile_encrypted),mobile_hash=coalesce(?,mobile_hash),guardian_member_id=?,version=version+1 where id=?",r.relationship(),crypto.encrypt(name),nameHash,gender(r.gender()),r.birthDate(),idType,crypto.encrypt(normalizedId),normalizedId==null?null:crypto.hmac(normalizedId),crypto.encrypt(mobile),mobile==null?null:crypto.hmac(mobile),r.guardianMemberId(),memberId);return memberId;}catch(DuplicateKeyException e){throw new BusinessException(self?ErrorCode.MEMBER_SELF_DUPLICATED:ErrorCode.IDENTITY_DUPLICATED);}}
  private Map<String,Object> patient(long id){return jdbc.queryForList("select * from patient where id=? and deleted=0",id).stream().findFirst().orElseThrow(()->new BusinessException(ErrorCode.PATIENT_NOT_FOUND));} private Map<String,Object> owned(long patientId,long memberId){Map<String,Object> row=jdbc.queryForList("select * from patient_member where id=? and deleted=0",memberId).stream().findFirst().orElseThrow(()->new BusinessException(ErrorCode.MEMBER_NOT_FOUND));if(number(row,"patient_id")!=patientId)throw new BusinessException(ErrorCode.MEMBER_NOT_OWNED);return row;}
  private MemberDto memberDto(Map<String,Object> row){String mobile=crypto.decrypt(text(row,"mobile_encrypted")), id=crypto.decrypt(text(row,"id_number_encrypted"));return new MemberDto(number(row,"id"),text(row,"member_no"),text(row,"relationship_code"),crypto.decrypt(text(row,"name_encrypted")),text(row,"gender"),date(row,"birth_date"),maskMobile(mobile),maskId(id),Boolean.TRUE.equals(row.get("is_self"))||number(row,"is_self")==1,text(row,"real_name_status"),text(row,"status"),"ACTIVE".equals(text(row,"status")));} private AdminPatientDto adminDto(Map<String,Object> row){return new AdminPatientDto(number(row,"id"),text(row,"patient_no"),maskName(crypto.decrypt(text(row,"name_ciphertext"))),maskMobile(crypto.decrypt(text(row,"mobile_encrypted"))),text(row,"real_name_status"),number(row,"status")==1,number(row,"member_count"),String.valueOf(row.get("created_at")));}
  private void validateIdentity(String type,String id,LocalDate birth,String gender){if(!"CN_ID".equals(type))return;if(!id.matches("[0-9]{17}[0-9X]"))throw new BusinessException(ErrorCode.IDENTITY_INVALID);int[] weights={7,9,10,5,8,4,2,1,6,3,7,9,10,5,8,4,2};String checks="10X98765432";int sum=0;for(int i=0;i<17;i++)sum+=(id.charAt(i)-'0')*weights[i];if(checks.charAt(sum%11)!=id.charAt(17))throw new BusinessException(ErrorCode.IDENTITY_INVALID);LocalDate fromId;try{fromId=LocalDate.parse(id.substring(6,14),java.time.format.DateTimeFormatter.BASIC_ISO_DATE);}catch(Exception e){throw new BusinessException(ErrorCode.IDENTITY_INVALID);}if(birth!=null&&!birth.equals(fromId))throw new BusinessException(ErrorCode.IDENTITY_INVALID);String expected=(id.charAt(16)-'0')%2==0?"FEMALE":"MALE";if(gender!=null&&!gender.isBlank()&&!expected.equals(gender(gender)))throw new BusinessException(ErrorCode.IDENTITY_INVALID);}
  private String mobile(String raw){String value=raw==null?"":raw.replaceAll("[\\s-]","");if(value.startsWith("+86"))value=value.substring(3);if(!value.matches("1[3-9]\\d{9}"))throw new BusinessException(ErrorCode.VALIDATION);return value;}private String identity(String raw){return raw.replaceAll("\\s","").toUpperCase(Locale.ROOT);}private String gender(String value){if(value==null||value.isBlank())return null;String normalized=value.toUpperCase(Locale.ROOT);if(!Set.of("MALE","FEMALE","UNKNOWN").contains(normalized))throw new BusinessException(ErrorCode.VALIDATION);return normalized;}private String smsKey(String hash){return "hospital:patient:sms:"+hash;}private static String text(Object o){return o==null?null:o.toString();}private static String text(Map<String,Object> m,String k){return text(m.get(k));}private static long number(Map<String,Object> m,String k){Object x=m.get(k);return x instanceof Number n?n.longValue():x==null?0:Long.parseLong(x.toString());}private static LocalDate date(Map<String,Object> m,String k){Object x=m.get(k);return x instanceof java.sql.Date d?d.toLocalDate():x instanceof LocalDate d?d:null;}private static String maskMobile(String value){return value==null?null:value.length()<7?"***":value.substring(0,3)+"****"+value.substring(value.length()-4);}private static String maskId(String value){return value==null?null:value.length()<8?"***":value.substring(0,3)+"***********"+value.substring(value.length()-4);}private static String maskName(String value){return value==null?null:value.length()<2?"*":value.charAt(0)+"*";}
  public record SendCodeResult(long expiresIn,String testCode){} public record PatientSelfDto(String patientNo,String name,String gender,LocalDate birthDate,String mobile,String realNameStatus,long defaultMemberId){} public record MemberDto(long id,String memberNo,String relationship,String name,String gender,LocalDate birthDate,String mobile,String idNumber,boolean self,String realNameStatus,String status,boolean usableForAppointment){} public record AdminPatientDto(long id,String patientNo,String name,String mobile,String realNameStatus,boolean active,long memberCount,String createdAt){} public record ProfileRequest(String name,String gender,LocalDate birthDate){} public record MemberRequest(String relationship,String name,String gender,LocalDate birthDate,String idType,String idNumber,String mobile,Long guardianMemberId){}
}
