package com.hospital.platform.iam.infrastructure;
import java.time.Instant; import java.util.List; import java.util.Map; import java.util.Optional; import org.springframework.jdbc.core.JdbcTemplate; import org.springframework.jdbc.core.RowMapper; import org.springframework.stereotype.Repository;
@Repository public class UserRepository {
  private final JdbcTemplate jdbc; private final RowMapper<UserRow> mapper=(rs,n)->new UserRow(rs.getLong("id"),rs.getString("username"),rs.getString("password_hash"),rs.getString("display_name"),rs.getInt("status"),rs.getInt("token_version"),rs.getInt("login_fail_count"),rs.getTimestamp("locked_until")==null?null:rs.getTimestamp("locked_until").toInstant());
  public UserRepository(JdbcTemplate jdbc){this.jdbc=jdbc;}
  public Optional<UserRow> findByUsername(String username){return jdbc.query("select * from sys_user where username=? and deleted=0",mapper,username).stream().findFirst();}
  public Optional<UserRow> findById(long id){return jdbc.query("select * from sys_user where id=? and deleted=0",mapper,id).stream().findFirst();}
  public List<String> permissions(long id){return jdbc.queryForList("select distinct p.permission_code from sys_permission p join sys_role_permission rp on p.id=rp.permission_id join sys_user_role ur on ur.role_id=rp.role_id join sys_role r on r.id=ur.role_id where ur.user_id=? and p.status=1 and r.status=1",String.class,id);}
  public List<String> roles(long id){return jdbc.queryForList("select r.role_code from sys_role r join sys_user_role ur on r.id=ur.role_id where ur.user_id=? and r.status=1",String.class,id);}
  public List<Map<String,Object>> menus(long id){return jdbc.queryForList("select distinct m.id,m.menu_code,m.menu_name,m.route_path,m.component,m.icon,m.sort_order from sys_menu m left join sys_permission p on p.id=m.permission_id left join sys_role_permission rp on rp.permission_id=p.id left join sys_user_role ur on ur.role_id=rp.role_id where m.status=1 and (m.permission_id is null or ur.user_id=?) order by m.sort_order",id);}
  public void loginSuccess(long id){jdbc.update("update sys_user set login_fail_count=0,locked_until=null,last_login_at=now(3) where id=?",id);}
  public void loginFailure(long id){jdbc.update("update sys_user set login_fail_count=login_fail_count+1, locked_until=case when login_fail_count+1>=5 then date_add(now(3), interval 15 minute) else locked_until end where id=?",id);}
  public void changePassword(long id,String hash){jdbc.update("update sys_user set password_hash=?,token_version=token_version+1,login_fail_count=0,locked_until=null where id=?",hash,id);}
  public void create(String username,String hash,String displayName){jdbc.update("insert into sys_user(username,password_hash,display_name) values(?,?,?)",username,hash,displayName);}
  public void update(long id,String displayName){jdbc.update("update sys_user set display_name=? where id=? and deleted=0",displayName,id);}
  public void assignRoles(long userId,List<Long> roleIds){jdbc.update("delete from sys_user_role where user_id=?",userId);if(roleIds!=null)for(Long roleId:roleIds)jdbc.update("insert into sys_user_role(user_id,role_id) select ?,id from sys_role where id=? and status=1 and deleted=0",userId,roleId);}
  public void logLogin(Long userId,String username,boolean success,String client,String ip,String reason){jdbc.update("insert into sys_login_log(user_id,username,success,client_type,ip_address,failure_reason,trace_id) values(?,?,?,?,?,?,?)",userId,username,success,client,ip,reason,com.hospital.platform.common.trace.TraceId.get());}
  public void disable(long id){jdbc.update("update sys_user set status=0,token_version=token_version+1 where id=?",id);}
  public List<Map<String,Object>> users(){return jdbc.queryForList("select id,username,display_name,status,created_at from sys_user where deleted=0 order by id desc");}
  public List<Map<String,Object>> usersByIds(List<Long> ids){if(ids.isEmpty())return List.of();String marks=String.join(",",java.util.Collections.nCopies(ids.size(),"?"));return jdbc.queryForList("select id,username,display_name,status,created_at from sys_user where deleted=0 and id in ("+marks+") order by id desc",ids.toArray());}
  public com.hospital.platform.common.api.PageResponse<Map<String,Object>> pageByIds(List<Long> ids,String keyword,long page,long pageSize){if(ids.isEmpty())return new com.hospital.platform.common.api.PageResponse<>(page,pageSize,0,List.of());String marks=String.join(",",java.util.Collections.nCopies(ids.size(),"?"));String where=" deleted=0 and id in ("+marks+")"+(keyword==null||keyword.isBlank()?"":" and username like ?");java.util.List<Object> args=new java.util.ArrayList<>(ids);if(keyword!=null&&!keyword.isBlank())args.add("%"+keyword+"%");Long total=jdbc.queryForObject("select count(*) from sys_user where"+where,Long.class,args.toArray());args.add(pageSize);args.add((page-1)*pageSize);return new com.hospital.platform.common.api.PageResponse<>(page,pageSize,total,jdbc.queryForList("select id,username,display_name,status,created_at from sys_user where"+where+" order by id limit ? offset ?",args.toArray()));}
  public record UserRow(long id,String username,String passwordHash,String displayName,int status,int tokenVersion,int failedCount,Instant lockedUntil){}
}
