<script setup lang="ts">
import { onShow } from '@dcloudio/uni-app';
import { ref } from 'vue';
import { clearSession, patientSession, request } from '../../api/http';
const mobile = ref(''), code = ref(''), testCode = ref(''), profile = ref<any>(null), members = ref<any[]>([]), name = ref(''), relationship = ref('SELF'), tip = ref('');
function options() { return (getCurrentPages()[getCurrentPages().length - 1] as any)?.options || {}; }
function returnToBooking(memberId?: number) { const target = options().returnTo; if (!target) return null; const separator = String(target).includes('?') ? '&' : '?'; return memberId ? String(target) + separator + 'memberId=' + memberId : String(target); }
async function load() { profile.value = (await request<any>({ url: '/patient/me' })).data; members.value = (await request<any>({ url: '/patient/members' })).data; }
async function send() { const response = await request<any>({ url: '/patient/auth/send-code', method: 'POST', data: { mobile: mobile.value } }); testCode.value = response.data.testCode || ''; tip.value = testCode.value ? '开发验证码由后端测试服务提供' : '验证码已发送'; }
async function login() { const response = await request<any>({ url: '/patient/auth/login', method: 'POST', data: { mobile: mobile.value, code: code.value, clientType: 'MINI_PROGRAM_PATIENT' } }); const keys = patientSession(); uni.setStorageSync(keys.accessKey, response.data.accessToken); uni.setStorageSync(keys.refreshKey, response.data.refreshToken); await load(); const target = returnToBooking(); if (target) uni.redirectTo({ url: target }); }
async function add() { const response = await request<any>({ url: '/patient/members', method: 'POST', data: { relationship: relationship.value, name: name.value, gender: 'UNKNOWN' } }); name.value = ''; await load(); const target = returnToBooking(Number(response.data)); if (target) uni.redirectTo({ url: target }); }
async function choose(id: number) { await request<any>({ url: '/patient/members/' + id + '/default', method: 'POST' }); await load(); }
async function logout() { try { const refresh = uni.getStorageSync(patientSession().refreshKey); if (refresh) await request<any>({ url: '/patient/auth/logout', method: 'POST', data: { refreshToken: refresh } }); } finally { clearSession(); profile.value = null; members.value = []; } }
function openAppointments() { uni.navigateTo({ url: '/pages/appointments/index' }); }
function openPayments() { uni.navigateTo({ url: '/pages/payments/index' }); }
onShow(() => { if (uni.getStorageSync(patientSession().accessKey)) void load().catch(logout); });
</script>
<template><view class="page"><view v-if="!profile" class="card"><text class="title">患者中心</text><input v-model="mobile" placeholder="手机号"/><button @click="send">发送验证码</button><text v-if="testCode">开发验证码：{{ testCode }}</text><input v-model="code" placeholder="验证码"/><button @click="login">登录</button><text class="tip">{{ tip }}</text></view><view v-else><view class="card"><text class="title">{{ profile.name }}</text><text>{{ profile.mobile }} · {{ profile.realNameStatus }}</text><button @click="openAppointments">我的预约</button><button @click="openPayments">我的缴费</button><button @click="logout">退出登录</button></view><view class="card"><text class="title">就诊人</text><view v-for="member in members" :key="member.id" class="member"><text>{{ member.name }} · {{ member.relationship }} · {{ member.idNumber||'未绑定证件' }}</text><button v-if="profile.defaultMemberId!==member.id" @click="choose(member.id)">设为默认</button></view></view><view class="card"><text class="title">添加就诊人</text><picker :range="['SELF','CHILD','PARENT','SPOUSE','OTHER']" @change="relationship=['SELF','CHILD','PARENT','SPOUSE','OTHER'][$event.detail.value]"><view>{{ relationship }}</view></picker><input v-model="name" placeholder="姓名"/><button @click="add">保存</button></view></view></view></template>
<style scoped>.page{padding:28rpx}.card{display:flex;flex-direction:column;gap:20rpx;background:#fff;border-radius:16rpx;padding:28rpx;margin-bottom:20rpx}.title{font-size:38rpx;font-weight:700}.member{display:flex;justify-content:space-between;gap:12rpx;padding:16rpx 0;border-bottom:1px solid #eef2f5}input{border:1px solid #d7e1e8;border-radius:10rpx;padding:16rpx}.tip{color:#b45309}</style>
