package com.hospital.platform.bootstrap;
import static org.assertj.core.api.Assertions.assertThat; import com.hospital.platform.iam.application.DataScopeQueryService; import java.util.*; import org.junit.jupiter.api.*; import org.springframework.beans.factory.annotation.Autowired; import org.springframework.boot.test.context.SpringBootTest; import org.springframework.jdbc.core.JdbcTemplate;
@SpringBootTest class DataScopeIntegrationTest { @Autowired JdbcTemplate jdbc; @Autowired DataScopeQueryService scopes; @Autowired com.hospital.platform.iam.infrastructure.UserRepository users; String p="ds_"+UUID.randomUUID().toString().substring(0,8); long orgA,orgB,a,a1,a11,a2,b,b1,ua,ua1,ua11,ua2,ub,ub1,all,self,dept,children,org,custom;
 long id(String sql,Object...args){return jdbc.queryForObject(sql,Long.class,args);} long user(String n){jdbc.update("insert into sys_user(username,password_hash,display_name) values(?,?,?)",n,"x",n);return id("select id from sys_user where username=?",n);} long dept(long org,Long parent,String code){jdbc.update("insert into sys_department(organization_id,parent_id,dept_code,dept_name,dept_type) values(?,?,?,?,?)",org,parent,code,code,"TEST");return id("select id from sys_department where organization_id=? and dept_code=?",org,code);} long role(String scope){String code=p+scope+UUID.randomUUID().toString().substring(0,8);jdbc.update("insert into sys_role(role_code,role_name,data_scope) values(?,?,?)",code,code,scope);return id("select id from sys_role where role_code=?",code);} void bind(long u,long r,long d){jdbc.update("insert into sys_user_role(user_id,role_id) values(?,?)",u,r);jdbc.update("insert into sys_user_department(user_id,department_id,is_primary) values(?,?,1)",u,d);}
 @BeforeEach void setup(){jdbc.update("insert into sys_organization(org_code,org_name,org_type) values(?,?,?)",p+"A","A","TEST");orgA=id("select id from sys_organization where org_code=?",p+"A");jdbc.update("insert into sys_organization(org_code,org_name,org_type) values(?,?,?)",p+"B","B","TEST");orgB=id("select id from sys_organization where org_code=?",p+"B");a=dept(orgA,null,"A");a1=dept(orgA,a,"A1");a11=dept(orgA,a1,"A11");a2=dept(orgA,a,"A2");b=dept(orgB,null,"B");b1=dept(orgB,b,"B1");ua=user(p+"ua");ua1=user(p+"ua1");ua11=user(p+"ua11");ua2=user(p+"ua2");ub=user(p+"ub");ub1=user(p+"ub1");all=user(p+"all");self=user(p+"self");dept=user(p+"dept");children=user(p+"children");org=user(p+"org");custom=user(p+"custom");long rAll=role("ALL"),rSelf=role("SELF"),rDept=role("DEPARTMENT"),rChild=role("DEPARTMENT_AND_CHILDREN"),rOrg=role("ORGANIZATION"),rCustom=role("CUSTOM");bind(ua,rAll,a);bind(ua1,rAll,a1);bind(ua11,rAll,a11);bind(ua2,rAll,a2);bind(ub,rAll,b);bind(ub1,rAll,b1);bind(all,rAll,a);bind(self,rSelf,a1);bind(dept,rDept,a1);bind(children,rChild,a);bind(org,rOrg,a2);bind(custom,rCustom,a2);jdbc.update("insert into sys_role_data_scope(role_id,target_type,target_id) values(?,?,?),(?,?,?)",rCustom,"DEPARTMENT",a1,rCustom,"DEPARTMENT",b1);}
 @AfterEach void clean(){jdbc.update("delete ds from sys_role_data_scope ds join sys_role r on r.id=ds.role_id where r.role_code like ?",p+"%");jdbc.update("delete ur from sys_user_role ur join sys_user u on u.id=ur.user_id where u.username like ?",p+"%");jdbc.update("delete from sys_user_department where user_id in (select id from sys_user where username like ?)",p+"%");jdbc.update("delete from sys_role where role_code like ?",p+"%");jdbc.update("delete from sys_user where username like ?",p+"%");jdbc.update("delete from sys_department where dept_code in ('A','A1','A11','A2','B','B1') and organization_id in (?,?)",orgA,orgB);jdbc.update("delete from sys_organization where id in (?,?)",orgA,orgB);}
 @Test void enforcesAllSixScopesAndClientFilters(){Set<Long> targets=Set.of(ua,ua1,ua11,ua2,ub,ub1);assertThat(scopes.visibleUserIds(all,null,null,null)).containsAll(targets);assertThat(scopes.visibleUserIds(self,null,null,null)).containsExactly(self);assertThat(scopes.visibleUserIds(dept,null,null,null)).contains(ua1,dept).doesNotContain(ua11,ub);assertThat(scopes.visibleUserIds(children,null,null,null)).contains(ua,ua1,ua11,ua2,children).doesNotContain(ub);assertThat(scopes.visibleUserIds(org,null,null,null)).contains(ua,ua1,ua11,ua2,org).doesNotContain(ub);assertThat(scopes.visibleUserIds(custom,null,null,null)).contains(ua1,ub1).doesNotContain(ua,ua2,ub);assertThat(scopes.visibleUserIds(dept,b1,null,null)).isEmpty();assertThat(scopes.visibleUserIds(org,null,orgB,null)).isEmpty();assertThat(scopes.visibleUserIds(self,null,null,ua1)).isEmpty();}
 @Test void pagesOnlyAuthorizedSqlResultsAndMergesRoles(){for(int i=0;i<12;i++){long extra=user(p+"page"+i);jdbc.update("insert into sys_user_department(user_id,department_id) values(?,?)",extra,a1);}var ids=scopes.visibleUserIds(dept,null,null,null);var first=users.pageByIds(ids,p+"page",1,5);var second=users.pageByIds(ids,p+"page",2,5);assertThat(first.total()).isEqualTo(12);assertThat(first.records()).hasSize(5);assertThat(second.records()).hasSize(5);
  long rA2=role("DEPARTMENT");jdbc.update("insert into sys_user_role(user_id,role_id) values(?,?)",dept,rA2);jdbc.update("insert into sys_user_department(user_id,department_id) values(?,?)",dept,a2);assertThat(scopes.visibleUserIds(dept,null,null,null)).contains(ua1,ua2);
  long rOrgB=role("ORGANIZATION");jdbc.update("insert into sys_user_role(user_id,role_id) values(?,?)",org,rOrgB);jdbc.update("insert into sys_user_department(user_id,department_id) values(?,?)",org,b1);assertThat(scopes.visibleUserIds(org,null,null,null)).contains(ua1,ub1);
  long rAll=role("ALL");jdbc.update("insert into sys_user_role(user_id,role_id) values(?,?)",dept,rAll);assertThat(scopes.visibleUserIds(dept,null,null,null)).contains(ub1);
  long forward=user(p+"orderForward"),reverse=user(p+"orderReverse"),rDept=role("DEPARTMENT"),rOrganization=role("ORGANIZATION");jdbc.update("insert into sys_user_department(user_id,department_id) values(?,?),(?,?)",forward,a1,reverse,a1);jdbc.update("insert into sys_user_role(user_id,role_id) values(?,?),(?,?)",forward,rDept,forward,rOrganization);jdbc.update("insert into sys_user_role(user_id,role_id) values(?,?),(?,?)",reverse,rOrganization,reverse,rDept);var forwardIds=new HashSet<>(scopes.visibleUserIds(forward,null,null,null));var reverseIds=new HashSet<>(scopes.visibleUserIds(reverse,null,null,null));forwardIds.removeAll(Set.of(forward,reverse));reverseIds.removeAll(Set.of(forward,reverse));assertThat(forwardIds).isEqualTo(reverseIds);
  long noRole=user(p+"norole");assertThat(scopes.visibleUserIds(noRole,null,null,null)).isEmpty();}}
