package com.hospital.platform.clinical;

import com.hospital.platform.common.error.BusinessException;
import com.hospital.platform.common.error.ErrorCode;
import com.hospital.platform.common.trace.TraceId;
import com.hospital.platform.patient.PatientCrypto;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.sql.Timestamp;
import java.time.Instant;
import java.util.*;
import org.springframework.dao.DuplicateKeyException;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

/** Owns clinical documents, versions, structured observations and longitudinal allergy facts. No clinical body is logged. */
@Service public class ClinicalService {
  private final JdbcTemplate jdbc; private final DiagnosisCatalogProvider catalogue; private final ClinicalSignatureProvider signatures; private final PatientCrypto crypto;
  public ClinicalService(JdbcTemplate jdbc,DiagnosisCatalogProvider catalogue,ClinicalSignatureProvider signatures,PatientCrypto crypto){this.jdbc=jdbc;this.catalogue=catalogue;this.signatures=signatures;this.crypto=crypto;}

  @Transactional public RecordView draft(long actor,long encounterId) {
    Map<String,Object> encounter=doctorEncounter(actor,encounterId);
    List<Map<String,Object>> records=jdbc.queryForList("select * from outpatient_medical_record where encounter_id=? and deleted=0",encounterId);
    if(records.isEmpty()) {
      requireInConsultation(encounter);
      String no="MR"+UUID.randomUUID().toString().replace("-","").substring(0,24).toUpperCase(Locale.ROOT);
      jdbc.update("insert into outpatient_medical_record(record_no,encounter_id,patient_id,member_id,doctor_id,department_id,status,created_by,updated_by) values(?,?,?,?,?,?, 'DRAFT',?,?)",no,encounterId,num(encounter,"patient_id"),num(encounter,"member_id"),num(encounter,"doctor_id"),num(encounter,"department_id"),actor,actor);
      long record=requiredLong(jdbc.queryForObject("select id from outpatient_medical_record where encounter_id=?",Long.class,encounterId));
      long revision=insertRevision(record,1,null,"INITIAL",null,actor,null);
      jdbc.update("update outpatient_medical_record set current_revision_id=? where id=?",revision,record);
      audit(actor,"CREATE_DRAFT","MEDICAL_RECORD",record,revision); return view(record,revision);
    }
    Map<String,Object> record=records.getFirst(); long revision=num(record,"current_revision_id"); audit(actor,"VIEW_MEDICAL_RECORD","MEDICAL_RECORD",num(record,"id"),revision); return view(num(record,"id"),revision);
  }

  @Transactional public RecordView saveDraft(long actor,long encounterId,SaveDraft input) {
    RecordView existing=draft(actor,encounterId); Map<String,Object> revision=revision(existing.revisionId());
    if(!"DRAFT".equals(text(revision,"status"))) throw new BusinessException(ErrorCode.CLINICAL_RECORD_IMMUTABLE);
    validateText(input);
    int updated=jdbc.update("update outpatient_medical_record_revision set chief_complaint=?,present_illness=?,past_history=?,personal_history=?,family_history=?,physical_examination=?,treatment_plan=?,doctor_note=?,version=version+1 where id=? and status='DRAFT' and version=?",input.chiefComplaint(),input.presentIllness(),input.pastHistory(),input.personalHistory(),input.familyHistory(),input.physicalExamination(),input.treatmentPlan(),input.doctorNote(),existing.revisionId(),input.version());
    if(updated!=1) throw new BusinessException(ErrorCode.CLINICAL_RECORD_VERSION_CONFLICT);
    replaceDiagnoses(actor,encounterId,existing.revisionId(),input.diagnoses());
    jdbc.update("update outpatient_medical_record set version=version+1,updated_by=? where id=?",actor,existing.recordId()); audit(actor,"EDIT_DRAFT","MEDICAL_RECORD",existing.recordId(),existing.revisionId()); return view(existing.recordId(),existing.revisionId());
  }

  @Transactional public RecordView sign(long actor,long encounterId,SignRequest input) {
    RecordView record=draft(actor,encounterId); Map<String,Object> revision=revisionForUpdate(record.revisionId());
    if(!"DRAFT".equals(text(revision,"status"))) throw new BusinessException(ErrorCode.CLINICAL_RECORD_IMMUTABLE);
    if(input.version()!=num(revision,"version")) throw new BusinessException(ErrorCode.CLINICAL_RECORD_VERSION_CONFLICT);
    required(revision,"chief_complaint"); required(revision,"present_illness"); required(revision,"physical_examination");
    Long primary=jdbc.queryForObject("select count(*) from encounter_diagnosis where medical_record_revision_id=? and diagnosis_type='PRIMARY' and status in ('PROVISIONAL','CONFIRMED') and deleted=0",Long.class,record.revisionId());
    if(primary==null||primary!=1) throw new BusinessException(ErrorCode.CLINICAL_REQUIRED_FIELD);
    String hash=hash(revision,diagnoses(record.revisionId()));
    int changed=jdbc.update("update outpatient_medical_record_revision set status='SIGNED',content_hash=?,signed_by=?,signed_at=current_timestamp(3),signature_type=?,external_signature_reference=?,version=version+1 where id=? and status='DRAFT' and version=?",hash,actor,signatures.type(),signatures.externalReference(),record.revisionId(),input.version());
    if(changed!=1) throw new BusinessException(ErrorCode.CLINICAL_RECORD_VERSION_CONFLICT);
    jdbc.update("update outpatient_medical_record set status='SIGNED',version=version+1,updated_by=? where id=?",actor,record.recordId()); audit(actor,"SIGN","MEDICAL_RECORD",record.recordId(),record.revisionId()); return view(record.recordId(),record.revisionId());
  }

  @Transactional public RecordView amend(long actor,long encounterId,AmendRequest input) {
    Map<String,Object> encounter=doctorEncounter(actor,encounterId); Map<String,Object> record=recordForEncounter(encounterId); long current=num(record,"current_revision_id"); Map<String,Object> old=revisionForUpdate(current);
    if(!"SIGNED".equals(text(old,"status"))) throw new BusinessException(ErrorCode.CLINICAL_RECORD_IMMUTABLE); if(blank(input.reason())||input.reason().length()>512||containsMarkup(input.reason()))throw new BusinessException(ErrorCode.CLINICAL_AMEND_REASON_REQUIRED);
    int next=requiredLong(jdbc.queryForObject("select coalesce(max(revision_no),0)+1 from outpatient_medical_record_revision where medical_record_id=?",Long.class,num(record,"id"))).intValue();
    long id=insertRevision(num(record,"id"),next,current,"AMENDMENT",input.reason(),actor,old);
    jdbc.update("update outpatient_medical_record set current_revision_id=?,status='DRAFT',version=version+1,updated_by=? where id=?",id,actor,num(record,"id")); audit(actor,"CREATE_AMENDMENT","MEDICAL_RECORD",num(record,"id"),id); return view(num(record,"id"),id);
  }

  @Transactional public VitalView vital(long actor,long encounterId,VitalInput input) {
    Map<String,Object> e=doctorEncounter(actor,encounterId); validVital(input); Long previous=input.correctedFromId();
    if(previous!=null){Long found=jdbc.queryForObject("select count(*) from clinical_vital_sign where id=? and encounter_id=?",Long.class,previous,encounterId);if(found==null||found==0)throw new BusinessException(ErrorCode.NOT_FOUND);jdbc.update("update clinical_vital_sign set status='CORRECTED',version=version+1 where id=? and status='ACTIVE'",previous);}
    BigDecimal bmi=bmi(input.heightCm(),input.weightKg());
    jdbc.update("insert into clinical_vital_sign(encounter_id,patient_id,member_id,measured_at,temperature_celsius,pulse_bpm,respiratory_rate,systolic_bp,diastolic_bp,spo2_percent,height_cm,weight_kg,bmi,source,recorded_by,corrected_from_id,status) values(?,?,?,coalesce(?,current_timestamp(3)),?,?,?,?,?,?,?,?,?,?,?,?,'ACTIVE')",encounterId,num(e,"patient_id"),num(e,"member_id"),input.measuredAt()==null?null:Timestamp.from(input.measuredAt()),input.temperatureCelsius(),input.pulseBpm(),input.respiratoryRate(),input.systolicBp(),input.diastolicBp(),input.spo2Percent(),input.heightCm(),input.weightKg(),bmi,input.source()==null?"MANUAL":input.source(),actor,previous);
    long id=requiredLong(jdbc.queryForObject("select last_insert_id()",Long.class)); audit(actor,previous==null?"CREATE_VITAL":"CORRECT_VITAL","VITAL",id,null); return vitalView(one("select * from clinical_vital_sign where id=?",id));
  }

  @Transactional public AllergyView allergy(long actor,long encounterId,AllergyInput input) {
    Map<String,Object> e=doctorEncounter(actor,encounterId); validAllergy(input); long patient=num(e,"patient_id"),member=num(e,"member_id");
    jdbc.update("insert into patient_allergy(patient_id,member_id,allergen_type,allergen_code,allergen_name,reaction,severity,clinical_status,verification_status,recorded_by,verified_by,verified_at,source) values(?,?,?,?,?,?,?,'ACTIVE',?, ?,?,current_timestamp(3),?)",patient,member,input.allergenType(),input.allergenCode(),input.allergenName().trim(),input.reaction(),input.severity(),input.verificationStatus()==null?"CLINICIAN_RECORDED":input.verificationStatus(),actor,actor,input.source()==null?"MANUAL":input.source());
    profile(patient,member,"HAS_ALLERGIES",actor); long id=requiredLong(jdbc.queryForObject("select last_insert_id()",Long.class));audit(actor,"CREATE_ALLERGY","ALLERGY",id,null);return allergyView(one("select * from patient_allergy where id=?",id));
  }
  @Transactional public void setAllergyStatus(long actor,long encounterId,String status) { Map<String,Object> e=doctorEncounter(actor,encounterId); if(!Set.of("UNKNOWN","NO_KNOWN_ALLERGIES","HAS_ALLERGIES").contains(status))throw new BusinessException(ErrorCode.VALIDATION); long patient=num(e,"patient_id"),member=num(e,"member_id");Long active=jdbc.queryForObject("select count(*) from patient_allergy where patient_id=? and member_id=? and clinical_status='ACTIVE' and deleted=0",Long.class,patient,member);if("NO_KNOWN_ALLERGIES".equals(status)&&active!=null&&active>0)throw new BusinessException(ErrorCode.VALIDATION);profile(patient,member,status,actor);audit(actor,"SET_ALLERGY_STATUS","ALLERGY_PROFILE",member,null); }

  @Transactional public EncounterClinicalView detail(long actor,boolean auditor,long encounterId) { Map<String,Object> e=readEncounter(actor,auditor,encounterId); Map<String,Object> record=jdbc.queryForList("select * from outpatient_medical_record where encounter_id=? and deleted=0",encounterId).stream().findFirst().orElse(null); List<RecordRevisionView> history=record==null?List.of():jdbc.queryForList("select * from outpatient_medical_record_revision where medical_record_id=? and deleted=0 order by revision_no",num(record,"id")).stream().map(this::revisionView).toList(); List<VitalView> vitals=jdbc.queryForList("select * from clinical_vital_sign where encounter_id=? order by measured_at desc,id desc",encounterId).stream().map(this::vitalView).toList(); long patient=num(e,"patient_id"),member=num(e,"member_id");String allergyStatus=jdbc.queryForList("select allergy_status from patient_allergy_profile where patient_id=? and member_id=?",patient,member).stream().findFirst().map(x->text(x,"allergy_status")).orElse("UNKNOWN");List<AllergyView> allergies=jdbc.queryForList("select * from patient_allergy where patient_id=? and member_id=? and deleted=0 order by id desc",patient,member).stream().map(this::allergyView).toList();audit(actor,"VIEW_MEDICAL_RECORD","VISIT_ENCOUNTER",encounterId,record==null?null:number(record,"current_revision_id"));return new EncounterClinicalView(encounterHeader(e),record==null?null:view(num(record,"id"),num(record,"current_revision_id")),history,vitals,allergyStatus,allergies); }
  @Transactional public boolean verifyIntegrity(long actor,boolean auditor,long encounterId,long revisionId) { readEncounter(actor,auditor,encounterId); Map<String,Object> r=revision(revisionId); Map<String,Object> record=recordForEncounter(encounterId); if(num(r,"medical_record_id")!=num(record,"id"))throw new BusinessException(ErrorCode.CLINICAL_ACCESS_DENIED); String saved=text(r,"content_hash"); boolean ok="SIGNED".equals(text(r,"status"))&&saved!=null&&saved.equals(hash(r,diagnoses(revisionId)));audit(actor,ok?"VERIFY_INTEGRITY":"INTEGRITY_FAILURE","MEDICAL_RECORD",num(r,"medical_record_id"),revisionId);return ok; }
  public List<DiagnosisCatalogItem> catalogue(String query){return catalogue.search(query);}
  public boolean hasSignedRecordForEncounter(long encounterId){Long count=jdbc.queryForObject("select count(*) from outpatient_medical_record r join outpatient_medical_record_revision v on v.id=r.current_revision_id where r.encounter_id=? and r.deleted=0 and v.status='SIGNED'",Long.class,encounterId);return count!=null&&count>0;}

  private long insertRevision(long record,int no,Long parent,String type,String reason,long actor,Map<String,Object> copy){jdbc.update("insert into outpatient_medical_record_revision(medical_record_id,revision_no,parent_revision_id,revision_type,status,chief_complaint,present_illness,past_history,personal_history,family_history,physical_examination,treatment_plan,doctor_note,amend_reason,created_by) values(?,?,?,?, 'DRAFT',?,?,?,?,?,?,?,?,?,?)",record,no,parent,type,copy==null?null:text(copy,"chief_complaint"),copy==null?null:text(copy,"present_illness"),copy==null?null:text(copy,"past_history"),copy==null?null:text(copy,"personal_history"),copy==null?null:text(copy,"family_history"),copy==null?null:text(copy,"physical_examination"),copy==null?null:text(copy,"treatment_plan"),copy==null?null:text(copy,"doctor_note"),reason,actor);return requiredLong(jdbc.queryForObject("select last_insert_id()",Long.class));}
  private void replaceDiagnoses(long actor,long encounter,long revision,List<DiagnosisInput> values){values=values==null?List.of():values;if(values.stream().filter(x->"PRIMARY".equals(x.diagnosisType())&&Set.of("PROVISIONAL","CONFIRMED").contains(x.status())).count()>1)throw new BusinessException(ErrorCode.CLINICAL_PRIMARY_DIAGNOSIS_CONFLICT);jdbc.update("delete from encounter_diagnosis where medical_record_revision_id=? and deleted=0",revision);int order=0;try{for(DiagnosisInput x:values){validDiagnosis(x);DiagnosisCatalogItem item=catalogue.require(x.codeSystem(),x.diagnosisCode());jdbc.update("insert into encounter_diagnosis(encounter_id,medical_record_revision_id,diagnosis_type,code_system,diagnosis_code,diagnosis_name_snapshot,status,sort_order,entered_by) values(?,?,?,?,?,?,?,?,?)",encounter,revision,x.diagnosisType(),item.codeSystem(),item.code(),item.name(),x.status(),order++,actor);}}catch(DuplicateKeyException e){throw new BusinessException(ErrorCode.CLINICAL_PRIMARY_DIAGNOSIS_CONFLICT);}}
  private Map<String,Object> doctorEncounter(long user,long encounter){long doctor=doctor(user);return jdbc.queryForList("select * from visit_encounter where id=? and doctor_id=? and deleted=0",encounter,doctor).stream().findFirst().orElseThrow(()->new BusinessException(ErrorCode.CLINICAL_ACCESS_DENIED));}
  private Map<String,Object> readEncounter(long user,boolean auditor,long encounter){if(auditor)return one("select * from visit_encounter where id=? and deleted=0",encounter);return doctorEncounter(user,encounter);}
  private long doctor(long user){Long id=jdbc.query("select id from doctor where user_id=? and deleted=0 and status=1 and published=1",(rs,row)->rs.getLong(1),user).stream().findFirst().orElse(null);if(id==null)throw new BusinessException(ErrorCode.CLINICAL_ACCESS_DENIED);return id;}
  private Map<String,Object> recordForEncounter(long encounter){return jdbc.queryForList("select * from outpatient_medical_record where encounter_id=? and deleted=0",encounter).stream().findFirst().orElseThrow(()->new BusinessException(ErrorCode.NOT_FOUND));}
  private Map<String,Object> revision(long id){return one("select * from outpatient_medical_record_revision where id=? and deleted=0",id);} private Map<String,Object> revisionForUpdate(long id){return one("select * from outpatient_medical_record_revision where id=? and deleted=0 for update",id);} private Map<String,Object> one(String sql,Object...args){return jdbc.queryForList(sql,args).stream().findFirst().orElseThrow(()->new BusinessException(ErrorCode.NOT_FOUND));}
  private RecordView view(long record,long revision){Map<String,Object> r=revision(revision);return new RecordView(record,revision,text(r,"status"),num(r,"revision_no"),num(r,"version"),revisionView(r),diagnoses(revision));}
  private RecordRevisionView revisionView(Map<String,Object> r){return new RecordRevisionView(num(r,"id"),num(r,"revision_no"),number(r,"parent_revision_id"),text(r,"revision_type"),text(r,"status"),text(r,"chief_complaint"),text(r,"present_illness"),text(r,"past_history"),text(r,"personal_history"),text(r,"family_history"),text(r,"physical_examination"),text(r,"treatment_plan"),text(r,"doctor_note"),text(r,"amend_reason"),number(r,"signed_by"),instant(r.get("signed_at")),text(r,"signature_type"),num(r,"version"));}
  private List<DiagnosisView> diagnoses(long revision){return jdbc.queryForList("select * from encounter_diagnosis where medical_record_revision_id=? and deleted=0 order by sort_order,id",revision).stream().map(x->new DiagnosisView(num(x,"id"),text(x,"diagnosis_type"),text(x,"code_system"),text(x,"diagnosis_code"),text(x,"diagnosis_name_snapshot"),text(x,"status"),num(x,"sort_order"))).toList();}
  private VitalView vitalView(Map<String,Object> x){return new VitalView(num(x,"id"),instant(x.get("measured_at")),decimal(x,"temperature_celsius"),integer(x,"pulse_bpm"),integer(x,"respiratory_rate"),integer(x,"systolic_bp"),integer(x,"diastolic_bp"),decimal(x,"spo2_percent"),decimal(x,"height_cm"),decimal(x,"weight_kg"),decimal(x,"bmi"),text(x,"status"),number(x,"corrected_from_id"),num(x,"version"));}
  private AllergyView allergyView(Map<String,Object>x){return new AllergyView(num(x,"id"),text(x,"allergen_type"),text(x,"allergen_code"),text(x,"allergen_name"),text(x,"reaction"),text(x,"severity"),text(x,"clinical_status"),text(x,"verification_status"),num(x,"version"));}
  private EncounterHeader encounterHeader(Map<String,Object> e){Map<String,Object> p=one("select p.patient_no,m.name_encrypted,m.gender,m.birth_date from patient p join patient_member m on m.id=? and m.patient_id=p.id where p.id=?",num(e,"member_id"),num(e,"patient_id"));return new EncounterHeader(num(e,"id"),text(e,"encounter_no"),crypto.decrypt(text(p,"name_encrypted")),text(p,"gender"),p.get("birth_date")==null?null:String.valueOf(p.get("birth_date")),text(p,"patient_no"),text(e,"status"));}
  private void profile(long patient,long member,String status,long actor){jdbc.update("insert into patient_allergy_profile(patient_id,member_id,allergy_status,updated_by) values(?,?,?,?) on duplicate key update allergy_status=values(allergy_status),updated_by=values(updated_by),version=version+1",patient,member,status,actor);}
  private void requireInConsultation(Map<String,Object> e){if(!"IN_CONSULTATION".equals(text(e,"status")))throw new BusinessException(ErrorCode.APPOINTMENT_INVALID_STATE);}
  private void validVital(VitalInput x){if(x==null||bad(x.temperatureCelsius())||bad(x.pulseBpm())||bad(x.respiratoryRate())||bad(x.systolicBp())||bad(x.diastolicBp())||bad(x.spo2Percent())||bad(x.heightCm())||bad(x.weightKg())||(x.systolicBp()!=null&&x.diastolicBp()!=null&&x.systolicBp()<x.diastolicBp())||x.measuredAt()!=null&&x.measuredAt().isAfter(Instant.now().plusSeconds(300)))throw new BusinessException(ErrorCode.VALIDATION);}
  private void validAllergy(AllergyInput x){if(x==null||!Set.of("DRUG","FOOD","ENVIRONMENT","OTHER").contains(x.allergenType())||blank(x.allergenName())||x.allergenName().length()>256||containsMarkup(x.allergenName())||containsMarkup(x.reaction())||(x.severity()!=null&&!Set.of("MILD","MODERATE","SEVERE").contains(x.severity())))throw new BusinessException(ErrorCode.VALIDATION);}
  private void validDiagnosis(DiagnosisInput x){if(x==null||!Set.of("PRIMARY","SECONDARY").contains(x.diagnosisType())||!Set.of("PROVISIONAL","CONFIRMED","RULED_OUT").contains(x.status())||blank(x.codeSystem())||blank(x.diagnosisCode())||x.codeSystem().length()>64||x.diagnosisCode().length()>64)throw new BusinessException(ErrorCode.VALIDATION);}
  private void validateText(SaveDraft x){if(x==null||badText(x.chiefComplaint(),1024)||badText(x.presentIllness(),20000)||badText(x.pastHistory(),10000)||badText(x.personalHistory(),10000)||badText(x.familyHistory(),10000)||badText(x.physicalExamination(),20000)||badText(x.treatmentPlan(),20000)||badText(x.doctorNote(),10000))throw new BusinessException(ErrorCode.VALIDATION);}
  private String hash(Map<String,Object> r,List<DiagnosisView> ds){StringBuilder b=new StringBuilder();for(String key:List.of("chief_complaint","present_illness","past_history","personal_history","family_history","physical_examination","treatment_plan","doctor_note"))b.append(key).append('=').append(canonical(text(r,key))).append('\n');for(DiagnosisView d:ds)b.append("diagnosis=").append(d.type()).append('|').append(d.codeSystem()).append('|').append(d.code()).append('|').append(d.name()).append('|').append(d.status()).append('|').append(d.sortOrder()).append('\n');try{return java.util.HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(b.toString().getBytes(StandardCharsets.UTF_8)));}catch(Exception e){throw new IllegalStateException(e);}}
  private static String canonical(String value){return value==null?"<NULL>":value.replace("\r\n","\n").replace('\r','\n');} private static boolean badText(String x,int max){return x!=null&&(x.length()>max||containsMarkup(x));}private static boolean containsMarkup(String x){return x!=null&&(x.contains("<")||x.contains(">"));}private static boolean blank(String x){return x==null||x.trim().isEmpty();}private static boolean bad(Number x){return x!=null&&new BigDecimal(x.toString()).signum()<0;}private static BigDecimal bmi(BigDecimal h,BigDecimal w){if(h==null||w==null||h.signum()<=0||w.signum()<0)return null;return w.divide(h.divide(BigDecimal.valueOf(100),8,RoundingMode.HALF_UP).pow(2),2,RoundingMode.HALF_UP);}private static long num(Map<String,Object>x,String k){return ((Number)x.get(k)).longValue();}private static Long number(Map<String,Object>x,String k){Object v=x.get(k);return v instanceof Number n?n.longValue():null;}private static Integer integer(Map<String,Object>x,String k){Object v=x.get(k);return v instanceof Number n?n.intValue():null;}private static BigDecimal decimal(Map<String,Object>x,String k){Object v=x.get(k);return v==null?null:new BigDecimal(v.toString());}private static String text(Map<String,Object>x,String k){Object v=x.get(k);return v==null?null:String.valueOf(v);}private static Instant instant(Object x){return x instanceof Timestamp t?t.toInstant():x instanceof java.time.LocalDateTime t?t.toInstant(java.time.ZoneOffset.UTC):null;}private static Long requiredLong(Long x){if(x==null)throw new BusinessException(ErrorCode.SYSTEM);return x;}private static void required(Map<String,Object>x,String key){if(blank(text(x,key)))throw new BusinessException(ErrorCode.CLINICAL_REQUIRED_FIELD);}private void audit(long actor,String action,String type,long resource,Long revision){jdbc.update("insert into clinical_access_audit(actor_id,action,resource_type,resource_id,revision_id,trace_id) values(?,?,?,?,?,?)",actor,action,type,resource,revision,TraceId.get());}

  public record SaveDraft(int version,String chiefComplaint,String presentIllness,String pastHistory,String personalHistory,String familyHistory,String physicalExamination,String treatmentPlan,String doctorNote,List<DiagnosisInput> diagnoses){} public record SignRequest(int version){} public record AmendRequest(String reason){} public record DiagnosisInput(String diagnosisType,String codeSystem,String diagnosisCode,String status){} public record VitalInput(Instant measuredAt,BigDecimal temperatureCelsius,Integer pulseBpm,Integer respiratoryRate,Integer systolicBp,Integer diastolicBp,BigDecimal spo2Percent,BigDecimal heightCm,BigDecimal weightKg,String source,Long correctedFromId){} public record AllergyInput(String allergenType,String allergenCode,String allergenName,String reaction,String severity,String verificationStatus,String source){} public record DiagnosisCatalogItem(String codeSystem,String code,String name){} public record DiagnosisView(long id,String type,String codeSystem,String code,String name,String status,long sortOrder){} public record RecordRevisionView(long id,long revisionNo,Long parentRevisionId,String revisionType,String status,String chiefComplaint,String presentIllness,String pastHistory,String personalHistory,String familyHistory,String physicalExamination,String treatmentPlan,String doctorNote,String amendReason,Long signedBy,Instant signedAt,String signatureType,long version){} public record RecordView(long recordId,long revisionId,String status,long revisionNo,long version,RecordRevisionView revision,List<DiagnosisView> diagnoses){} public record VitalView(long id,Instant measuredAt,BigDecimal temperatureCelsius,Integer pulseBpm,Integer respiratoryRate,Integer systolicBp,Integer diastolicBp,BigDecimal spo2Percent,BigDecimal heightCm,BigDecimal weightKg,BigDecimal bmi,String status,Long correctedFromId,long version){} public record AllergyView(long id,String allergenType,String allergenCode,String allergenName,String reaction,String severity,String clinicalStatus,String verificationStatus,long version){} public record EncounterHeader(long encounterId,String encounterNo,String memberName,String gender,String birthDate,String patientNo,String status){} public record EncounterClinicalView(EncounterHeader encounter,RecordView currentRecord,List<RecordRevisionView> revisions,List<VitalView> vitals,String allergyStatus,List<AllergyView> allergies){}
}
