package com.hospital.platform.payment;
import com.hospital.platform.common.api.ApiResponse;
import com.hospital.platform.common.api.PageResponse;
import com.hospital.platform.common.security.AuthenticatedUser;
import com.hospital.platform.iam.application.DataScopeQueryService;
import java.util.*;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.security.core.annotation.AuthenticationPrincipal;
import org.springframework.web.bind.annotation.*;
@RestController @RequestMapping("/api/v1/admin") public class RefundAdminController {
  private final JdbcTemplate db; private final DataScopeQueryService scopes; private final RefundService refunds; private final PaymentReconciliationService reconciliation;
  public RefundAdminController(JdbcTemplate db,DataScopeQueryService scopes,RefundService refunds,PaymentReconciliationService reconciliation){this.db=db;this.scopes=scopes;this.refunds=refunds;this.reconciliation=reconciliation;}
  @GetMapping("/refund-orders") @PreAuthorize("hasAuthority('hospital:refund:list')") public ApiResponse<?> list(@AuthenticationPrincipal AuthenticatedUser user,@RequestParam(defaultValue="1") long page,@RequestParam(defaultValue="20") long pageSize,@RequestParam(required=false) String status){long current=Math.max(1,page),size=Math.min(100,Math.max(1,pageSize));var all=scoped(user.id(),"select f.* from refund_order f join appointment a on a.id=f.appointment_id join doctor_schedule s on s.id=a.schedule_id join outpatient_department od on od.id=s.outpatient_department_id join department d on d.id=od.department_id"+(status==null||status.isBlank()?"":" where f.status='"+status.replace("'","")+"'"));long from=(current-1)*size,to=Math.min(all.size(),from+size);return PatientPaymentController.ok(new PageResponse<>(current,size,all.size(),from>=all.size()?List.of():all.subList((int)from,(int)to).stream().map(PaymentViews::refund).toList()));}
  @GetMapping("/refund-orders/{id}") @PreAuthorize("hasAuthority('hospital:refund:view')") public ApiResponse<?> detail(@AuthenticationPrincipal AuthenticatedUser user,@PathVariable long id){var rows=scoped(user.id(),"select f.* from refund_order f join appointment a on a.id=f.appointment_id join doctor_schedule s on s.id=a.schedule_id join outpatient_department od on od.id=s.outpatient_department_id join department d on d.id=od.department_id where f.id="+id);if(rows.isEmpty())throw new PaymentException("REFUND_RESOURCE_NOT_FOUND",404);return PatientPaymentController.ok(PaymentViews.refund(rows.getFirst()));}
  @PostMapping("/refund-orders/{id}/retry") @PreAuthorize("hasAuthority('hospital:refund:retry')") public ApiResponse<?> retry(@AuthenticationPrincipal AuthenticatedUser user,@PathVariable long id){return PatientPaymentController.ok(refunds.retry(id,user.id()));}
  @GetMapping("/reconciliation-anomalies") @PreAuthorize("hasAuthority('hospital:reconciliation:list')") public ApiResponse<?> anomalies(@AuthenticationPrincipal AuthenticatedUser user){List<Long> ids=scopes.visibleAdministrativeDepartmentIds(user.id());if(ids.isEmpty())return PatientPaymentController.ok(List.of());String marks=String.join(",",Collections.nCopies(ids.size(),"?"));String department="d.administrative_department_id in ("+marks+")";String scope="((x.resource_type='PAYMENT_ORDER' and exists(select 1 from payment_order p join registration_order r on r.id=p.registration_order_id join appointment a on a.id=r.appointment_id join doctor_schedule s on s.id=a.schedule_id join outpatient_department od on od.id=s.outpatient_department_id join department d on d.id=od.department_id where p.id=x.resource_id and "+department+")) or (x.resource_type='REGISTRATION_ORDER' and exists(select 1 from registration_order r join appointment a on a.id=r.appointment_id join doctor_schedule s on s.id=a.schedule_id join outpatient_department od on od.id=s.outpatient_department_id join department d on d.id=od.department_id where r.id=x.resource_id and "+department+")) or (x.resource_type='APPOINTMENT' and exists(select 1 from appointment a join doctor_schedule s on s.id=a.schedule_id join outpatient_department od on od.id=s.outpatient_department_id join department d on d.id=od.department_id where a.id=x.resource_id and "+department+")))";List<Object> args=new ArrayList<>();for(int i=0;i<3;i++)args.addAll(ids);return PatientPaymentController.ok(db.queryForList("select x.* from payment_reconciliation_record x where x.status='OPEN' and "+scope+" order by x.detected_at desc limit 200",args.toArray()));}
  @PostMapping("/reconciliation/run") @PreAuthorize("hasAuthority('hospital:reconciliation:list')") public ApiResponse<?> run(){return PatientPaymentController.ok(Map.of("detected",reconciliation.reconcile()));}
  private List<Map<String,Object>> scoped(long user,String sql){List<Long> ids=scopes.visibleAdministrativeDepartmentIds(user);if(ids.isEmpty())return List.of();String marks=String.join(",",Collections.nCopies(ids.size(),"?"));String glue=sql.contains(" where ")?" and ":" where ";return db.queryForList(sql+glue+"d.administrative_department_id in ("+marks+")",ids.toArray());}
}
