package com.hospital.platform.scheduling;

import com.hospital.platform.common.api.PageResponse;
import com.hospital.platform.common.error.BusinessException;
import com.hospital.platform.common.error.ErrorCode;
import com.hospital.platform.common.trace.TraceId;
import com.hospital.platform.appointment.AppointmentService;
import com.hospital.platform.iam.application.DataScopeQueryService;
import java.time.DayOfWeek;
import java.time.LocalDate;
import java.time.LocalTime;
import java.util.ArrayList;
import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.UUID;
import org.springframework.dao.DuplicateKeyException;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.context.annotation.Lazy;
import org.springframework.data.redis.core.StringRedisTemplate;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.transaction.support.TransactionSynchronization;
import org.springframework.transaction.support.TransactionSynchronizationManager;

/** MySQL is the source of truth for all quota mutations; Redis is a rebuildable read cache. */
@Service
public class SchedulingService {
  private final JdbcTemplate jdbc; private final DataScopeQueryService scopes; private final StringRedisTemplate redis; private final AppointmentService appointments; private final int publicMaxQueryDays;
  public SchedulingService(JdbcTemplate jdbc,DataScopeQueryService scopes,StringRedisTemplate redis,@Lazy AppointmentService appointments,@Value("${hospital.scheduling.public-max-query-days:31}") int publicMaxQueryDays){this.jdbc=jdbc;this.scopes=scopes;this.redis=redis;this.appointments=appointments;this.publicMaxQueryDays=publicMaxQueryDays;}

  public List<Map<String,Object>> sessions(Long hospitalId,boolean publicOnly){String sql="select id,hospital_id hospitalId,code,name,start_time startTime,end_time endTime,sort_order sortOrder,status,version from schedule_session_definition where deleted=0"+(hospitalId==null?"":" and hospital_id=?")+(publicOnly?" and status=1":"")+" order by sort_order,id";return hospitalId==null?jdbc.queryForList(sql):jdbc.queryForList(sql,hospitalId);}
  @Transactional public long createSession(SessionRequest r){validTime(r.startTime(),r.endTime());exists("hospital",r.hospitalId());try{jdbc.update("insert into schedule_session_definition(hospital_id,code,name,start_time,end_time,sort_order,status) values(?,?,?,?,?,?,?)",r.hospitalId(),code(r.code(),32),text(r.name()),r.startTime(),r.endTime(),sort(r.sortOrder()),on(r.status()));return id("select id from schedule_session_definition where hospital_id=? and code=?",r.hospitalId(),r.code());}catch(DuplicateKeyException e){throw new BusinessException(ErrorCode.SCHEDULE_CONFLICT);}}
  @Transactional public void updateSession(long id,SessionRequest r){validTime(r.startTime(),r.endTime());int n=jdbc.update("update schedule_session_definition set name=?,start_time=?,end_time=?,sort_order=?,status=?,version=version+1 where id=? and deleted=0 and version=?",text(r.name()),r.startTime(),r.endTime(),sort(r.sortOrder()),on(r.status()),id,r.version());updated(n);}

  public List<Map<String,Object>> templates(long actor){List<Long> allowed=scopes.visibleAdministrativeDepartmentIds(actor);if(allowed.isEmpty())return List.of();String marks=marks(allowed.size());return jdbc.queryForList("select t.id,t.template_code templateCode,t.name,t.doctor_id doctorId,t.campus_id campusId,t.outpatient_department_id outpatientDepartmentId,t.clinic_type_id clinicTypeId,t.valid_from validFrom,t.valid_to validTo,t.quota_per_session quotaPerSession,t.slot_duration_minutes slotDurationMinutes,t.slot_quota slotQuota,t.status,t.published,t.version from schedule_template t join outpatient_department od on od.id=t.outpatient_department_id join department d on d.id=od.department_id where t.deleted=0 and d.deleted=0 and d.administrative_department_id in ("+marks+") order by t.id desc",allowed.toArray());}
  @Transactional public long createTemplate(TemplateRequest r,long actor){assertOutpatientScope(actor,r.outpatientDepartmentId());validTemplate(r);try{jdbc.update("insert into schedule_template(template_code,name,doctor_id,campus_id,outpatient_department_id,clinic_type_id,valid_from,valid_to,quota_per_session,slot_duration_minutes,slot_quota,status,published,created_by,updated_by) values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",code(r.code(),64),text(r.name()),r.doctorId(),r.campusId(),r.outpatientDepartmentId(),r.clinicTypeId(),r.validFrom(),r.validTo(),quota(r.quotaPerSession()),r.slotDurationMinutes(),r.slotQuota(),on(r.status()),on(r.published()),actor,actor);long template=id("select id from schedule_template where template_code=?",r.code());replaceRules(template,r.rules());return template;}catch(DuplicateKeyException e){throw new BusinessException(ErrorCode.SCHEDULE_CONFLICT);}}
  @Transactional public void updateTemplate(long id,TemplateRequest r,long actor){assertOutpatientScope(actor,r.outpatientDepartmentId());validTemplate(r);int n=jdbc.update("update schedule_template set name=?,doctor_id=?,campus_id=?,outpatient_department_id=?,clinic_type_id=?,valid_from=?,valid_to=?,quota_per_session=?,slot_duration_minutes=?,slot_quota=?,status=?,published=?,updated_by=?,version=version+1 where id=? and deleted=0 and version=?",text(r.name()),r.doctorId(),r.campusId(),r.outpatientDepartmentId(),r.clinicTypeId(),r.validFrom(),r.validTo(),quota(r.quotaPerSession()),r.slotDurationMinutes(),r.slotQuota(),on(r.status()),on(r.published()),actor,id,r.version());updated(n);replaceRules(id,r.rules());}
  public List<Map<String,Object>> previewTemplate(long id,LocalDate from,LocalDate to){Map<String,Object> t=one("select * from schedule_template where id=? and deleted=0",id);if(from.isAfter(to)||from.isBefore(((java.sql.Date)t.get("valid_from")).toLocalDate())||to.isAfter(((java.sql.Date)t.get("valid_to")).toLocalDate()))throw new BusinessException(ErrorCode.SCHEDULE_INVALID);List<Map<String,Object>> rules=jdbc.queryForList("select day_of_week dayOfWeek,session_definition_id sessionDefinitionId from schedule_template_rule where template_id=? and deleted=0 and status=1",id);List<Map<String,Object>> result=new ArrayList<>();for(LocalDate d=from;!d.isAfter(to);d=d.plusDays(1))for(Map<String,Object> rule:rules)if(((Number)rule.get("dayOfWeek")).intValue()==d.getDayOfWeek().getValue()){Map<String,Object> x=new LinkedHashMap<>();x.put("date",d);x.put("sessionDefinitionId",rule.get("sessionDefinitionId"));result.add(x);}return result;}
  @Transactional public List<Long> generateTemplate(long id,LocalDate from,LocalDate to,long actor){Map<String,Object> t=one("select * from schedule_template where id=? and deleted=0 and status=1",id);List<Long> result=new ArrayList<>();for(Map<String,Object> item:previewTemplate(id,from,to)){long session=((Number)item.get("sessionDefinitionId")).longValue();Map<String,Object> sessionRow=one("select start_time,end_time from schedule_session_definition where id=? and status=1 and deleted=0",session);ScheduleRequest request=new ScheduleRequest(null,((Number)t.get("doctor_id")).longValue(),((Number)t.get("campus_id")).longValue(),((Number)t.get("outpatient_department_id")).longValue(),number(t.get("clinic_type_id")),((LocalDate)item.get("date")),session,((java.sql.Time)sessionRow.get("start_time")).toLocalTime(),((java.sql.Time)sessionRow.get("end_time")).toLocalTime(),"TEMPLATE",id,((Number)t.get("quota_per_session")).intValue(),false,0);try{result.add(createSchedule(request,actor));}catch(BusinessException e){if(e.errorCode()==ErrorCode.SCHEDULE_CONFLICT)continue;throw e;}}return result;}

  public PageResponse<Map<String,Object>> schedules(long actor,ScheduleFilter f,boolean publicOnly){
    if(publicOnly) validatePublicRange(f);
    List<Long> allowed=publicOnly?List.of():scopes.visibleAdministrativeDepartmentIds(actor);
    if(!publicOnly&&allowed.isEmpty())return new PageResponse<>(Math.max(1,f.page()),Math.max(1,f.pageSize()),0,List.of());
    String scope=publicOnly?"":" and d.administrative_department_id in ("+marks(allowed.size())+")";
    String publicState=publicOnly?" and s.schedule_status='PUBLISHED' and s.schedule_date>=current_date() and od.deleted=0 and od.status=1 and od.published=1 and d.deleted=0 and d.status=1 and d.published=1 and campus.deleted=0 and campus.status=1 and campus.published=1 and dr.deleted=0 and dr.status=1 and dr.published=1 and sd.deleted=0 and sd.status=1 and (ct.id is null or (ct.deleted=0 and ct.status=1 and ct.published=1))":"";
    List<Object> args=new ArrayList<>(allowed);String where=" s.deleted=0"+publicState+scope;
    if(f.doctorId()!=null){where+=" and s.doctor_id=?";args.add(f.doctorId());}if(f.departmentId()!=null){where+=" and d.id=?";args.add(f.departmentId());}if(f.campusId()!=null){where+=" and s.campus_id=?";args.add(f.campusId());}if(f.clinicTypeId()!=null){where+=" and s.clinic_type_id=?";args.add(f.clinicTypeId());}if(f.from()!=null){where+=" and s.schedule_date>=?";args.add(f.from());}if(f.to()!=null){where+=" and s.schedule_date<=?";args.add(f.to());}
    long page=Math.max(1,f.page()),size=Math.min(100,Math.max(1,f.pageSize()));
    String joins=" from doctor_schedule s join outpatient_department od on od.id=s.outpatient_department_id join department d on d.id=od.department_id join hospital_campus campus on campus.id=s.campus_id join doctor dr on dr.id=coalesce(s.substitute_doctor_id,s.doctor_id) join schedule_session_definition sd on sd.id=s.session_definition_id left join clinic_type ct on ct.id=s.clinic_type_id left join clinic_room room on room.id=s.clinic_room_id left join doctor original_dr on original_dr.id=s.original_doctor_id";
    Long total=jdbc.queryForObject("select count(*)"+joins+" where "+where,Long.class,args.toArray());
    List<Object> pageArgs=new ArrayList<>(args);pageArgs.add(size);pageArgs.add((page-1)*size);
    String sql="select s.id,s.schedule_no scheduleNo,s.doctor_id doctorId,coalesce(s.substitute_doctor_id,s.doctor_id) displayDoctorId,s.original_doctor_id originalDoctorId,s.substitute_doctor_id substituteDoctorId,original_dr.name originalDoctorName,s.campus_id campusId,campus.name campusName,d.id departmentId,d.department_name departmentName,od.name outpatientDepartmentName,ct.name clinicType,dr.name doctorName,sd.name sessionName,s.schedule_date scheduleDate,s.start_time startTime,s.end_time endTime,s.total_quota totalQuota,s.total_quota-s.reserved_quota-s.booked_quota availableQuota,s.reserved_quota reservedQuota,s.booked_quota bookedQuota,s.slot_mode slotMode,s.schedule_status scheduleStatus,s.source,s.template_id templateId,s.clinic_room_id clinicRoomId,room.room_code clinicRoomCode,room.room_name clinicRoomName,room.room_number clinicRoomNumber,s.version"+joins+" where "+where+" order by s.schedule_date,s.start_time,s.id limit ? offset ?";
    List<Map<String,Object>> rows=jdbc.queryForList(sql,pageArgs.toArray());for(Map<String,Object> row:rows){List<Map<String,Object>> scheduleSlots=slots(((Number)row.get("id")).longValue(),publicOnly);row.put("slots",scheduleSlots);if(((Number)row.get("slotMode")).intValue()==1){int totalQuota=0,reservedQuota=0,bookedQuota=0;for(Map<String,Object> slot:scheduleSlots){totalQuota+=((Number)slot.get("totalQuota")).intValue();reservedQuota+=((Number)slot.get("reservedQuota")).intValue();bookedQuota+=((Number)slot.get("bookedQuota")).intValue();}row.put("totalQuota",totalQuota);row.put("reservedQuota",reservedQuota);row.put("bookedQuota",bookedQuota);row.put("availableQuota",totalQuota-reservedQuota-bookedQuota);}}return new PageResponse<>(page,size,total==null?0:total,rows);
  }
  @Transactional public long createSchedule(ScheduleRequest r,long actor){assertOutpatientScope(actor,r.outpatientDepartmentId());validSchedule(r);conflict(r.doctorId(),r.date(),r.startTime(),r.endTime(),null);try{jdbc.update("insert into doctor_schedule(schedule_no,doctor_id,campus_id,outpatient_department_id,clinic_type_id,schedule_date,session_definition_id,start_time,end_time,schedule_status,source,template_id,total_quota,slot_mode,created_by,updated_by) values(?,?,?,?,?,?,?,?,?,'DRAFT',?,?,?,?,?,?)","SC"+UUID.randomUUID().toString().replace("-","").substring(0,16),r.doctorId(),r.campusId(),r.outpatientDepartmentId(),r.clinicTypeId(),r.date(),r.sessionDefinitionId(),r.startTime(),r.endTime(),r.source(),r.templateId(),quota(r.totalQuota()),r.slotMode()?1:0,actor,actor);long id=id("select id from doctor_schedule where doctor_id=? and schedule_date=? and session_definition_id=? and campus_id=? and outpatient_department_id=? and clinic_type_unique_id=coalesce(?,0)",r.doctorId(),r.date(),r.sessionDefinitionId(),r.campusId(),r.outpatientDepartmentId(),r.clinicTypeId());change(id,"CREATE",null,"quota="+r.totalQuota(),null,null,actor);return id;}catch(DuplicateKeyException e){throw new BusinessException(ErrorCode.SCHEDULE_CONFLICT);}}
  @Transactional public void publish(long id,long version,long actor){Map<String,Object> row=one("select * from doctor_schedule where id=? and deleted=0",id);if(!"DRAFT".equals(row.get("schedule_status")))throw new BusinessException(ErrorCode.SCHEDULE_INVALID);validPublished(row);int n=jdbc.update("update doctor_schedule set schedule_status='PUBLISHED',version=version+1,updated_by=? where id=? and version=?",actor,id,version);updated(n);change(id,"PUBLISH","DRAFT","PUBLISHED",null,null,actor);rebuild(id);}
  @Transactional public void unpublish(long id,long version,long actor){Long active=jdbc.queryForObject("select count(*) from appointment where schedule_id=? and deleted=0 and status in ('HOLDING','BOOKED')",Long.class,id);if(active!=null&&active>0)throw new BusinessException(ErrorCode.SCHEDULE_HAS_ACTIVE_APPOINTMENTS);int n=jdbc.update("update doctor_schedule set schedule_status='DRAFT',version=version+1,updated_by=? where id=? and schedule_status='PUBLISHED' and version=?",actor,id,version);updated(n);change(id,"UNPUBLISH","PUBLISHED","DRAFT",null,null,actor);redis.delete(key(id));}
  @Transactional public void stop(long id,String reasonCode,String reason,long version,long actor){int n=jdbc.update("update doctor_schedule set schedule_status='STOPPED',version=version+1,updated_by=? where id=? and schedule_status in ('DRAFT','PUBLISHED') and version=?",actor,id,version);updated(n);change(id,"STOP",null,"STOPPED",reasonCode,text(reason),actor);appointments.cancelForStoppedSchedule(id,actor);redis.delete(key(id));}
  @Transactional public void substitute(long id,long substituteDoctorId,String reason,long version,long actor){Map<String,Object> row=one("select * from doctor_schedule where id=? and deleted=0",id);Long active=jdbc.queryForObject("select count(*) from doctor where id=? and deleted=0 and status=1 and published=1",Long.class,substituteDoctorId);if(active==null||active==0)throw new BusinessException(ErrorCode.SCHEDULE_INVALID);LocalDate date=((java.sql.Date)row.get("schedule_date")).toLocalDate();conflict(substituteDoctorId,date,((java.sql.Time)row.get("start_time")).toLocalTime(),((java.sql.Time)row.get("end_time")).toLocalTime(),id);long previous=row.get("substitute_doctor_id")==null?((Number)row.get("doctor_id")).longValue():((Number)row.get("substitute_doctor_id")).longValue();int n=jdbc.update("update doctor_schedule set original_doctor_id=coalesce(original_doctor_id,doctor_id),substitute_doctor_id=?,version=version+1,updated_by=? where id=? and version=?",substituteDoctorId,actor,id,version);updated(n);change(id,"SUBSTITUTE","doctor="+previous,"substituteDoctor="+substituteDoctorId,null,text(reason),actor);}
  @Transactional public void adjustQuota(long id,int total,String reason,long version,long actor){Map<String,Object> row=one("select total_quota,reserved_quota,booked_quota from doctor_schedule where id=? and deleted=0",id);int before=((Number)row.get("total_quota")).intValue(), minimum=((Number)row.get("reserved_quota")).intValue()+((Number)row.get("booked_quota")).intValue();if(total<minimum||total<0)throw new BusinessException(ErrorCode.QUOTA_NOT_ENOUGH);int n=jdbc.update("update doctor_schedule set total_quota=?,version=version+1,updated_by=? where id=? and version=?",total,actor,id,version);updated(n);change(id,total>=before?"ADD_QUOTA":"REDUCE_QUOTA","quota="+before,"quota="+total,null,text(reason),actor);rebuild(id);}
  @Transactional public List<Map<String,Object>> generateSlots(long scheduleId,int duration,int eachQuota,long actor){Map<String,Object> s=one("select * from doctor_schedule where id=? and deleted=0",scheduleId);if(duration<=0||eachQuota<0)throw new BusinessException(ErrorCode.SCHEDULE_INVALID);LocalTime start=((java.sql.Time)s.get("start_time")).toLocalTime(),end=((java.sql.Time)s.get("end_time")).toLocalTime();List<Map<String,Object>> slots=new ArrayList<>();for(LocalTime cursor=start;cursor.plusMinutes(duration).compareTo(end)<=0;cursor=cursor.plusMinutes(duration)){Map<String,Object> x=new LinkedHashMap<>();x.put("startTime",cursor);x.put("endTime",cursor.plusMinutes(duration));x.put("totalQuota",eachQuota);slots.add(x);}replaceSlots(scheduleId,slots,actor);return slots(scheduleId,false);}
  @Transactional public void replaceSlots(long scheduleId,List<Map<String,Object>> requests,long actor){Map<String,Object> s=one("select * from doctor_schedule where id=? and deleted=0",scheduleId);Long active=jdbc.queryForObject("select count(*) from appointment where schedule_id=? and deleted=0 and status in ('HOLDING','BOOKED')",Long.class,scheduleId);if(active!=null&&active>0)throw new BusinessException(ErrorCode.SLOT_HAS_ACTIVE_APPOINTMENTS);Long history=jdbc.queryForObject("select count(*) from appointment where schedule_id=? and deleted=0",Long.class,scheduleId);if(history!=null&&history>0)throw new BusinessException(ErrorCode.SLOT_HAS_APPOINTMENT_HISTORY);LocalTime scheduleStart=((java.sql.Time)s.get("start_time")).toLocalTime(),scheduleEnd=((java.sql.Time)s.get("end_time")).toLocalTime();int sum=0;List<SlotValue> values=new ArrayList<>();for(Map<String,Object> r:requests){LocalTime a=LocalTime.parse(String.valueOf(r.get("startTime"))),b=LocalTime.parse(String.valueOf(r.get("endTime")));int q=((Number)r.get("totalQuota")).intValue();if(!a.isBefore(b)||a.isBefore(scheduleStart)||b.isAfter(scheduleEnd)||q<0)throw new BusinessException(ErrorCode.SLOT_OVERLAP);values.add(new SlotValue(a,b,q));sum+=q;}for(int i=0;i<values.size();i++)for(int j=i+1;j<values.size();j++)if(values.get(i).start.isBefore(values.get(j).end)&&values.get(i).end.isAfter(values.get(j).start))throw new BusinessException(ErrorCode.SLOT_OVERLAP);if(sum!=((Number)s.get("total_quota")).intValue())throw new BusinessException(ErrorCode.SCHEDULE_INVALID);jdbc.update("delete from schedule_slot where schedule_id=?",scheduleId);int i=1;for(SlotValue v:values)jdbc.update("insert into schedule_slot(schedule_id,slot_no,start_time,end_time,total_quota,sort_order) values(?,?,?,?,?,?)",scheduleId,"S"+i,v.start,v.end,v.quota,i++);jdbc.update("update doctor_schedule set slot_mode=1,version=version+1 where id=?",scheduleId);change(scheduleId,"SLOT_CHANGE",null,"slots="+values.size(),null,null,actor);rebuild(scheduleId);}
  @Transactional public boolean reserve(long scheduleId,Long slotId,int quantity){if(quantity<=0)throw new BusinessException(ErrorCode.QUOTA_NOT_ENOUGH);String table=slotId==null?"doctor_schedule":"schedule_slot";String idColumn="id";int n=jdbc.update("update "+table+" set reserved_quota=reserved_quota+?,version=version+1 where "+idColumn+"=? and deleted=0 and total_quota-reserved_quota-booked_quota>=?",quantity,slotId==null?scheduleId:slotId,quantity);if(n==0)return false;rebuild(scheduleId);return true;}
  /** Final reservation fence for patient booking: published schedule and active slot are checked in the same SQL write. */
  @Transactional public boolean reserveBookable(long scheduleId,Long slotId,int quantity){if(quantity<=0)throw new BusinessException(ErrorCode.QUOTA_NOT_ENOUGH);int n;if(slotId==null)n=jdbc.update("update doctor_schedule set reserved_quota=reserved_quota+?,version=version+1 where id=? and deleted=0 and schedule_status='PUBLISHED' and schedule_date>=current_date() and total_quota-reserved_quota-booked_quota>=?",quantity,scheduleId,quantity);else n=jdbc.update("update schedule_slot sl join doctor_schedule s on s.id=sl.schedule_id set sl.reserved_quota=sl.reserved_quota+?,sl.version=sl.version+1 where sl.id=? and sl.schedule_id=? and sl.deleted=0 and sl.status='ACTIVE' and s.deleted=0 and s.schedule_status='PUBLISHED' and s.schedule_date>=current_date() and sl.total_quota-sl.reserved_quota-sl.booked_quota>=?",quantity,slotId,scheduleId,quantity);if(n==0)return false;rebuild(scheduleId);return true;}
  @Transactional public void release(long scheduleId,Long slotId,int quantity){quotaMove(scheduleId,slotId,quantity,"reserved_quota=reserved_quota-?", "reserved_quota>=?");}
  @Transactional public void commit(long scheduleId,Long slotId,int quantity){if(quantity<=0)throw new BusinessException(ErrorCode.QUOTA_NOT_ENOUGH);String table=slotId==null?"doctor_schedule":"schedule_slot";int n=jdbc.update("update "+table+" set reserved_quota=reserved_quota-?,booked_quota=booked_quota+?,version=version+1 where id=? and deleted=0 and reserved_quota>=?",quantity,quantity,slotId==null?scheduleId:slotId,quantity);if(n==0)throw new BusinessException(ErrorCode.QUOTA_NOT_ENOUGH);rebuild(scheduleId);}
  @Transactional public void releaseBooked(long scheduleId,Long slotId,int quantity){quotaMove(scheduleId,slotId,quantity,"booked_quota=booked_quota-?", "booked_quota>=?");}
  private void quotaMove(long scheduleId,Long slotId,int quantity,String set,String check){if(quantity<=0)throw new BusinessException(ErrorCode.QUOTA_NOT_ENOUGH);String table=slotId==null?"doctor_schedule":"schedule_slot";int n=jdbc.update("update "+table+" set "+set+",version=version+1 where id=? and deleted=0 and "+check,quantity,slotId==null?scheduleId:slotId,quantity);if(n==0)throw new BusinessException(ErrorCode.QUOTA_NOT_ENOUGH);rebuild(scheduleId);}
  /** Never publish an uncommitted MySQL quota value to Redis. */
  public void rebuild(long scheduleId){if(TransactionSynchronizationManager.isActualTransactionActive()){TransactionSynchronizationManager.registerSynchronization(new TransactionSynchronization(){@Override public void afterCommit(){try{rebuildNow(scheduleId);}catch(RuntimeException ignored){/* MySQL committed; scheduled/manual rebuild will restore this cache. */}}});return;}rebuildNow(scheduleId);}
  private void rebuildNow(long scheduleId){Map<String,Object> row=one("select total_quota-reserved_quota-booked_quota available from doctor_schedule where id=? and deleted=0",scheduleId);redis.opsForValue().set(key(scheduleId),String.valueOf(row.get("available")));for(Map<String,Object> slot:slots(scheduleId,false))redis.opsForValue().set(slotKey(((Number)slot.get("id")).longValue()),String.valueOf(slot.get("availableQuota")));}
  /** Clears only the scheduling cache namespace, then repopulates it from MySQL for effective published schedules. */
  @Transactional public int rebuildPublishedQuotaCaches(){java.util.Set<String> keys=redis.keys("hospital:dev:schedule:*");if(keys!=null&&!keys.isEmpty())redis.delete(keys);List<Long> ids=jdbc.queryForList("select id from doctor_schedule where deleted=0 and schedule_status='PUBLISHED' and schedule_date>=current_date()",Long.class);for(Long id:ids)rebuild(id);return ids.size();}
  public List<Map<String,Object>> changes(long scheduleId){return jdbc.queryForList("select id,action,before_summary beforeSummary,after_summary afterSummary,reason_code reasonCode,reason,operator_id operatorId,trace_id traceId,created_at createdAt from schedule_change_log where schedule_id=? order by id desc",scheduleId);}
  private List<Map<String,Object>> slots(long scheduleId,boolean publicOnly){return jdbc.queryForList("select id,slot_no slotNo,start_time startTime,end_time endTime,total_quota totalQuota,reserved_quota reservedQuota,booked_quota bookedQuota,total_quota-reserved_quota-booked_quota availableQuota,status,sort_order sortOrder,version from schedule_slot where schedule_id=? and deleted=0"+(publicOnly?" and status='ACTIVE'":"")+" order by start_time,id",scheduleId);}
  private void replaceRules(long templateId,List<TemplateRule> rules){if(rules==null||rules.isEmpty())throw new BusinessException(ErrorCode.SCHEDULE_INVALID);jdbc.update("delete from schedule_template_rule where template_id=?",templateId);for(TemplateRule rule:rules){if(rule.dayOfWeek()<1||rule.dayOfWeek()>7)throw new BusinessException(ErrorCode.SCHEDULE_INVALID);exists("schedule_session_definition",rule.sessionDefinitionId());jdbc.update("insert into schedule_template_rule(template_id,day_of_week,session_definition_id,sort_order,status) values(?,?,?,?,1)",templateId,rule.dayOfWeek(),rule.sessionDefinitionId(),sort(rule.sortOrder()));}}
  private void validTemplate(TemplateRequest r){exists("doctor",r.doctorId());exists("hospital_campus",r.campusId());exists("outpatient_department",r.outpatientDepartmentId());if(r.clinicTypeId()!=null)exists("clinic_type",r.clinicTypeId());if(r.validFrom()==null||r.validTo()==null||r.validFrom().isAfter(r.validTo())||r.quotaPerSession()<0)throw new BusinessException(ErrorCode.SCHEDULE_INVALID);if(r.slotDurationMinutes()!=null&&r.slotDurationMinutes()<=0)throw new BusinessException(ErrorCode.SCHEDULE_INVALID);}
  private void validatePublicRange(ScheduleFilter f){LocalDate from=f.from()==null?LocalDate.now():f.from();LocalDate to=f.to()==null?from.plusDays(publicMaxQueryDays):f.to();if(to.isBefore(from)||from.isBefore(LocalDate.now())||java.time.temporal.ChronoUnit.DAYS.between(from,to)>publicMaxQueryDays)throw new BusinessException(ErrorCode.SCHEDULE_INVALID);}
  private void validSchedule(ScheduleRequest r){exists("doctor",r.doctorId());exists("hospital_campus",r.campusId());exists("outpatient_department",r.outpatientDepartmentId());exists("schedule_session_definition",r.sessionDefinitionId());if(r.clinicTypeId()!=null)exists("clinic_type",r.clinicTypeId());if(r.date()==null||r.date().isBefore(LocalDate.now())||r.source()==null||!List.of("MANUAL","TEMPLATE","IMPORT","SYSTEM_GENERATED").contains(r.source()))throw new BusinessException(ErrorCode.SCHEDULE_INVALID);validTime(r.startTime(),r.endTime());quota(r.totalQuota());}
  private void validPublished(Map<String,Object> s){if(((Number)s.get("total_quota")).intValue()<((Number)s.get("reserved_quota")).intValue()+((Number)s.get("booked_quota")).intValue())throw new BusinessException(ErrorCode.QUOTA_NOT_ENOUGH);if(((Number)s.get("slot_mode")).intValue()==1){Long sum=jdbc.queryForObject("select coalesce(sum(total_quota),0) from schedule_slot where schedule_id=? and deleted=0 and status='ACTIVE'",Long.class,((Number)s.get("id")).longValue());if(sum==null||sum.intValue()!=((Number)s.get("total_quota")).intValue())throw new BusinessException(ErrorCode.SCHEDULE_INVALID);}}
  private void conflict(long doctor,LocalDate date,LocalTime start,LocalTime end,Long ignore){Long count=jdbc.queryForObject("select count(*) from doctor_schedule where doctor_id=? and schedule_date=? and deleted=0 and schedule_status not in ('STOPPED','CANCELLED') and start_time<? and end_time>?"+(ignore==null?"":" and id<>?"),Long.class,ignore==null?new Object[]{doctor,date,end,start}:new Object[]{doctor,date,end,start,ignore});if(count!=null&&count>0)throw new BusinessException(ErrorCode.SCHEDULE_CONFLICT);}
  private void assertOutpatientScope(long actor,long outpatient){Long administrative=jdbc.queryForObject("select d.administrative_department_id from outpatient_department od join department d on d.id=od.department_id where od.id=? and od.deleted=0 and d.deleted=0",Long.class,outpatient);if(administrative==null||!scopes.visibleAdministrativeDepartmentIds(actor).contains(administrative))throw new BusinessException(ErrorCode.FORBIDDEN);}
  private void change(long schedule,String action,String before,String after,String reasonCode,String reason,long actor){jdbc.update("insert into schedule_change_log(schedule_id,action,before_summary,after_summary,reason_code,reason,operator_id,trace_id) values(?,?,?,?,?,?,?,?)",schedule,action,before,after,reasonCode,reason,actor,TraceId.get());}
  private Map<String,Object> one(String sql,Object...args){List<Map<String,Object>> rows=jdbc.queryForList(sql,args);if(rows.isEmpty())throw new BusinessException(ErrorCode.NOT_FOUND);return rows.getFirst();}
  private void exists(String table,Long id){if(id==null)throw new BusinessException(ErrorCode.SCHEDULE_INVALID);Long count=jdbc.queryForObject("select count(*) from "+table+" where id=? and deleted=0",Long.class,id);if(count==null||count==0)throw new BusinessException(ErrorCode.SCHEDULE_INVALID);}
  private long id(String sql,Object...args){Long value=jdbc.queryForObject(sql,Long.class,args);if(value==null)throw new BusinessException(ErrorCode.NOT_FOUND);return value;} private void updated(int n){if(n==0)throw new BusinessException(ErrorCode.MASTER_CONFLICT);} private int on(Boolean x){return x==null||x?1:0;} private int sort(Integer x){return x==null?0:Math.max(0,x);} private int quota(int x){if(x<0)throw new BusinessException(ErrorCode.QUOTA_NOT_ENOUGH);return x;} private String text(String x){if(x==null||x.isBlank()||x.length()>255||x.contains("<")||x.contains(">"))throw new BusinessException(ErrorCode.SCHEDULE_INVALID);return x;} private String code(String x,int limit){if(x==null||x.isBlank()||x.length()>limit||!x.matches("[A-Za-z0-9_-]+"))throw new BusinessException(ErrorCode.SCHEDULE_INVALID);return x;} private void validTime(LocalTime start,LocalTime end){if(start==null||end==null||!start.isBefore(end))throw new BusinessException(ErrorCode.SCHEDULE_INVALID);} private String marks(int size){return String.join(",",Collections.nCopies(size,"?"));} private Long number(Object value){return value==null?null:((Number)value).longValue();} private String key(long id){return "hospital:dev:schedule:quota:"+id;} private String slotKey(long id){return "hospital:dev:schedule:slot:quota:"+id;}
  private record SlotValue(LocalTime start,LocalTime end,int quota){}
  public record SessionRequest(Long hospitalId,String code,String name,LocalTime startTime,LocalTime endTime,Integer sortOrder,Boolean status,int version){}
  public record TemplateRule(int dayOfWeek,Long sessionDefinitionId,Integer sortOrder){}
  public record TemplateRequest(String code,String name,Long doctorId,Long campusId,Long outpatientDepartmentId,Long clinicTypeId,LocalDate validFrom,LocalDate validTo,int quotaPerSession,Integer slotDurationMinutes,Integer slotQuota,Boolean status,Boolean published,List<TemplateRule> rules,int version){}
  public record ScheduleRequest(String scheduleNo,Long doctorId,Long campusId,Long outpatientDepartmentId,Long clinicTypeId,LocalDate date,Long sessionDefinitionId,LocalTime startTime,LocalTime endTime,String source,Long templateId,int totalQuota,boolean slotMode,int version){}
  public record ScheduleFilter(Long doctorId,Long departmentId,Long campusId,Long clinicTypeId,LocalDate from,LocalDate to,long page,long pageSize){}
}
