package com.hospital.platform.iam.application;
import com.hospital.platform.common.error.BusinessException; import com.hospital.platform.common.error.ErrorCode; import com.hospital.platform.common.security.AuthenticatedUser; import com.hospital.platform.iam.infrastructure.UserRepository; import java.time.Duration; import java.time.Instant; import java.util.List; import java.util.Map; import org.springframework.security.crypto.password.PasswordEncoder; import org.springframework.stereotype.Service;
@Service public class AuthService { private final UserRepository users; private final TokenService tokens; private final PasswordEncoder passwords; private final RedisRateLimiter rateLimiter; private final DataScopeQueryService dataScopes;
 public AuthService(UserRepository users,TokenService tokens,PasswordEncoder passwords,RedisRateLimiter rateLimiter,DataScopeQueryService dataScopes){this.users=users;this.tokens=tokens;this.passwords=passwords;this.rateLimiter=rateLimiter;this.dataScopes=dataScopes;}
 public TokenService.TokenPair login(String username,String password,String client,String ip,String ua){rateLimiter.check("hospital:development:iam:rate:login:"+ip,10,Duration.ofMinutes(1));var user=users.findByUsername(username).orElse(null);if(user==null){users.logLogin(null,username,false,client,ip,"INVALID_CREDENTIALS");throw new BusinessException(ErrorCode.AUTH_001);} if(user.status()!=1||(user.lockedUntil()!=null&&user.lockedUntil().isAfter(Instant.now()))){users.loginFailure(user.id());users.logLogin(user.id(),username,false,client,ip,"DISABLED_OR_LOCKED");throw new BusinessException(ErrorCode.AUTH_002);} if(!passwords.matches(password,user.passwordHash())){users.loginFailure(user.id());users.logLogin(user.id(),username,false,client,ip,"INVALID_CREDENTIALS");throw new BusinessException(ErrorCode.AUTH_001);}users.loginSuccess(user.id());users.logLogin(user.id(),username,true,client,ip,null);return tokens.issue(user,client,ip,ua);}
 public TokenService.TokenPair refresh(String refresh,String client,String ip,String ua){rateLimiter.check("hospital:development:iam:rate:refresh:"+ip,20,Duration.ofMinutes(1));return tokens.refresh(refresh,client,ip,ua);} public void logout(String refresh){tokens.revoke(refresh);} public void password(AuthenticatedUser actor,String oldPassword,String newPassword){var user=users.findById(actor.id()).orElseThrow(()->new BusinessException(ErrorCode.AUTH_003));if(!passwords.matches(oldPassword,user.passwordHash()))throw new BusinessException(ErrorCode.AUTH_001);users.changePassword(user.id(),passwords.encode(newPassword));tokens.revokeAll(user.id());}
 public Map<String,Object> me(AuthenticatedUser u){return Map.of("id",Long.toString(u.id()),"username",u.username(),"clientType",u.clientType(),"roles",users.roles(u.id()),"permissions",u.permissions(),"menus",users.menus(u.id()));}
 public void createUser(String username,String password,String displayName){users.create(username,passwords.encode(password),displayName);} public void updateUser(long id,String displayName){users.update(id,displayName);} public void assignRoles(long id,List<Long> roleIds){users.assignRoles(id,roleIds);} public void disableUser(long id){users.disable(id);tokens.revokeAll(id);} public List<Map<String,Object>> users(AuthenticatedUser actor,Long departmentId,Long organizationId,Long userId){return users.usersByIds(dataScopes.visibleUserIds(actor.id(),departmentId,organizationId,userId));}
}
