package com.hospital.platform.iam.application;
import com.hospital.platform.iam.domain.DataScope; import java.util.*; import org.springframework.jdbc.core.JdbcTemplate; import org.springframework.stereotype.Service;
/** Resolves role scopes from persisted memberships. Multiple roles are unioned; ALL dominates. Every branch constrains SQL before user records are read. */
@Service public class DataScopeQueryService { private final JdbcTemplate jdbc; public DataScopeQueryService(JdbcTemplate jdbc){this.jdbc=jdbc;}
 public List<Long> visibleUserIds(long actorId,Long requestedDepartmentId,Long requestedOrganizationId,Long requestedUserId){Set<DataScope> scopes=new HashSet<>();for(String value:jdbc.queryForList("select distinct r.data_scope from sys_role r join sys_user_role ur on ur.role_id=r.id where ur.user_id=? and r.status=1 and r.deleted=0",String.class,actorId)){try{scopes.add(DataScope.valueOf(value));}catch(Exception ignored){}}if(scopes.contains(DataScope.ALL))return filter(all(),requestedDepartmentId,requestedOrganizationId,requestedUserId);Set<Long> ids=new LinkedHashSet<>();for(DataScope scope:scopes)ids.addAll(idsFor(scope,actorId));return filter(new ArrayList<>(ids),requestedDepartmentId,requestedOrganizationId,requestedUserId);}
 public List<Long> visibleAdministrativeDepartmentIds(long actorId){Set<DataScope> scopes=scopes(actorId);if(scopes.contains(DataScope.ALL))return jdbc.queryForList("select id from sys_department where status=1 and deleted=0",Long.class);List<Long> own=jdbc.queryForList("select department_id from sys_user_department where user_id=?",Long.class,actorId);Set<Long> result=new LinkedHashSet<>();if(scopes.contains(DataScope.SELF)||scopes.contains(DataScope.DEPARTMENT))result.addAll(own);if(scopes.contains(DataScope.DEPARTMENT_AND_CHILDREN))for(Long id:own)result.addAll(jdbc.queryForList("with recursive tree as (select id from sys_department where id=? and status=1 and deleted=0 union all select d.id from sys_department d join tree t on d.parent_id=t.id where d.status=1 and d.deleted=0) select id from tree",Long.class,id));if(scopes.contains(DataScope.ORGANIZATION)&&!own.isEmpty()){String marks=String.join(",",Collections.nCopies(own.size(),"?"));result.addAll(jdbc.queryForList("select id from sys_department where organization_id in (select distinct organization_id from sys_department where id in ("+marks+")) and status=1 and deleted=0",Long.class,own.toArray()));}if(scopes.contains(DataScope.CUSTOM))result.addAll(jdbc.queryForList("select distinct ds.target_id from sys_role_data_scope ds join sys_user_role ur on ur.role_id=ds.role_id join sys_role r on r.id=ur.role_id where ur.user_id=? and r.status=1 and r.deleted=0 and r.data_scope='CUSTOM' and ds.target_type='DEPARTMENT'",Long.class,actorId));return new ArrayList<>(result);}
 private Set<DataScope> scopes(long actorId){Set<DataScope> scopes=new HashSet<>();for(String value:jdbc.queryForList("select distinct r.data_scope from sys_role r join sys_user_role ur on ur.role_id=r.id where ur.user_id=? and r.status=1 and r.deleted=0",String.class,actorId)){try{scopes.add(DataScope.valueOf(value));}catch(Exception ignored){}}return scopes;}
 public List<Long> idsFor(DataScope scope,long actorId){List<Long> depts=jdbc.queryForList("select department_id from sys_user_department where user_id=?",Long.class,actorId);return switch(scope){case ALL->all();case SELF->List.of(actorId);case DEPARTMENT->depts.isEmpty()?List.of():usersInDepartments(depts,false);case DEPARTMENT_AND_CHILDREN->depts.isEmpty()?List.of():usersInDepartments(depts,true);case ORGANIZATION->depts.isEmpty()?List.of():usersInOrganizations(depts);case CUSTOM->custom(actorId);};}
 private List<Long> all(){return jdbc.queryForList("select id from sys_user where deleted=0",Long.class);} private List<Long> usersInDepartments(List<Long> ids,boolean descendants){if(ids.isEmpty())return List.of();String marks=String.join(",",Collections.nCopies(ids.size(),"?"));String sql=descendants?"with recursive tree as (select id from sys_department where id in ("+marks+") and status=1 and deleted=0 union all select d.id from sys_department d join tree t on d.parent_id=t.id where d.status=1 and d.deleted=0) select distinct u.id from sys_user u join sys_user_department ud on ud.user_id=u.id join tree t on t.id=ud.department_id where u.deleted=0":"select distinct u.id from sys_user u join sys_user_department ud on ud.user_id=u.id join sys_department d on d.id=ud.department_id where ud.department_id in ("+marks+") and d.status=1 and d.deleted=0 and u.deleted=0";return jdbc.queryForList(sql,Long.class,ids.toArray());}
 private List<Long> usersInOrganizations(List<Long> depts){String marks=String.join(",",Collections.nCopies(depts.size(),"?"));return jdbc.queryForList("select distinct u.id from sys_user u join sys_user_department ud on ud.user_id=u.id join sys_department d on d.id=ud.department_id where d.organization_id in (select organization_id from sys_department where id in ("+marks+")) and d.status=1 and d.deleted=0 and u.deleted=0",Long.class,depts.toArray());}
 private List<Long> custom(long actor){List<Long> targets=jdbc.queryForList("select distinct ds.target_id from sys_role_data_scope ds join sys_user_role ur on ur.role_id=ds.role_id join sys_role r on r.id=ur.role_id where ur.user_id=? and r.status=1 and r.deleted=0 and r.data_scope='CUSTOM' and ds.target_type='DEPARTMENT'",Long.class,actor);return usersInDepartments(targets,false);}
 private List<Long> filter(List<Long> source,Long department,Long organization,Long user){if(source.isEmpty())return List.of();Set<Long> allowed=new LinkedHashSet<>(source);if(user!=null)allowed.retainAll(Set.of(user));if(department!=null)allowed.retainAll(new HashSet<>(usersInDepartments(List.of(department),false)));if(organization!=null){List<Long> orgUsers=jdbc.queryForList("select distinct u.id from sys_user u join sys_user_department ud on ud.user_id=u.id join sys_department d on d.id=ud.department_id where d.organization_id=? and d.status=1 and d.deleted=0 and u.deleted=0",Long.class,organization);allowed.retainAll(orgUsers);}return new ArrayList<>(allowed);}}
