package com.hospital.platform.iam.application;
import com.hospital.platform.common.error.BusinessException; import com.hospital.platform.common.error.ErrorCode; import com.hospital.platform.common.security.AuthenticatedUser; import com.hospital.platform.iam.infrastructure.UserRepository; import io.jsonwebtoken.Claims; import io.jsonwebtoken.Jwts; import io.jsonwebtoken.security.Keys; import java.nio.charset.StandardCharsets; import java.security.MessageDigest; import java.security.SecureRandom; import java.time.Instant; import java.time.temporal.ChronoUnit; import java.util.Base64; import java.util.Date; import java.util.List; import java.util.Set; import javax.crypto.SecretKey; import org.springframework.beans.factory.annotation.Value; import org.springframework.jdbc.core.JdbcTemplate; import org.springframework.stereotype.Service;
@Service public class TokenService { private final UserRepository users; private final JdbcTemplate jdbc; private final SecretKey key; private final long accessMinutes; private final long refreshDays;
 public TokenService(UserRepository users,JdbcTemplate jdbc,@Value("${hospital.security.jwt-secret}") String secret,@Value("${hospital.security.access-token-minutes:15}") long accessMinutes,@Value("${hospital.security.refresh-token-days:7}") long refreshDays){this.users=users;this.jdbc=jdbc;this.accessMinutes=accessMinutes;this.refreshDays=refreshDays; byte[] bytes=Base64.getDecoder().decode(secret); if(bytes.length<32)throw new IllegalStateException("JWT secret must contain at least 32 bytes");this.key=Keys.hmacShaKeyFor(bytes);}
 public TokenPair issue(UserRepository.UserRow user,String client,String ip,String ua){String access=Jwts.builder().id(java.util.UUID.randomUUID().toString()).issuer("hospital-platform").subject(Long.toString(user.id())).claim("username",user.username()).claim("client",client).claim("type","access").claim("ver",user.tokenVersion()).audience().add("hospital-api").and().issuedAt(new Date()).expiration(Date.from(Instant.now().plus(accessMinutes,ChronoUnit.MINUTES))).signWith(key).compact();String refresh=random();String hash=sha256(refresh);jdbc.update("insert into sys_refresh_token(user_id,token_hash,client_type,audience,token_version,expires_at,ip_address,user_agent) values(?,?,?,?,?,date_add(now(3), interval ? day),?,?)",user.id(),hash,client,"hospital-api",user.tokenVersion(),refreshDays,ip,ua);return new TokenPair(access,refresh,accessMinutes*60);}
 public TokenPair refresh(String raw,String client,String ip,String ua){String hash=sha256(raw);var rows=jdbc.queryForList("select * from sys_refresh_token where token_hash=? and revoked_at is null and expires_at>now(3)",hash);if(rows.isEmpty())throw new BusinessException(ErrorCode.AUTH_004);var row=rows.getFirst();if(!client.equals(row.get("client_type")))throw new BusinessException(ErrorCode.AUTH_004);long userId=((Number)row.get("user_id")).longValue();var user=users.findById(userId).orElseThrow(()->new BusinessException(ErrorCode.AUTH_004));if(user.status()!=1||user.tokenVersion()!=((Number)row.get("token_version")).intValue())throw new BusinessException(ErrorCode.AUTH_004);jdbc.update("update sys_refresh_token set revoked_at=now(3) where token_hash=?",hash);return issue(user,client,ip,ua);}
 public void revoke(String raw){jdbc.update("update sys_refresh_token set revoked_at=now(3) where token_hash=? and revoked_at is null",sha256(raw));}
 public void revokeAll(long id){jdbc.update("update sys_refresh_token set revoked_at=now(3) where user_id=? and revoked_at is null",id);}
 public AuthenticatedUser authenticate(String access){try{Claims c=Jwts.parser().verifyWith(key).requireIssuer("hospital-platform").build().parseSignedClaims(access).getPayload();if(!"access".equals(c.get("type",String.class))||!c.getAudience().contains("hospital-api")||c.getId()==null)throw new BusinessException(ErrorCode.AUTH_003);long id=Long.parseLong(c.getSubject());var u=users.findById(id).orElseThrow(()->new BusinessException(ErrorCode.AUTH_003));int ver=((Number)c.get("ver")).intValue();if(u.status()!=1||u.tokenVersion()!=ver)throw new BusinessException(ErrorCode.AUTH_003);return new AuthenticatedUser(id,u.username(),ver,c.get("client",String.class),Set.copyOf(users.permissions(id)));}catch(BusinessException e){throw e;}catch(Exception e){throw new BusinessException(ErrorCode.AUTH_003);}}
 private String random(){byte[] b=new byte[48];new SecureRandom().nextBytes(b);return Base64.getUrlEncoder().withoutPadding().encodeToString(b);} private String sha256(String s){try{return java.util.HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(s.getBytes(StandardCharsets.UTF_8)));}catch(Exception e){throw new IllegalStateException(e);}}
 public record TokenPair(String accessToken,String refreshToken,long expiresIn){}
}
