<script setup lang="ts">
import { computed, onBeforeUnmount, ref } from 'vue';
import { onShow } from '@dcloudio/uni-app';
import { appointmentApi, type Appointment } from '../../api/appointment';
import RegistrationPaymentStatus from '../../components/RegistrationPaymentStatus.vue';
const item = ref<Appointment | null>(null), tip = ref(''), busy = ref(false), localNow = ref(Date.now()), receivedAt = ref(Date.now()), queueNo = ref(''), queue = ref<{queueNo:string;status:string;roomName?:string;aheadCount:number}|null>(null);
let loading = false, lastPoll = 0;
const labels: Record<string, string> = { HOLDING: '待确认', BOOKED: '已预约', CANCELLED: '已取消', EXPIRED: '已失效' };
const id = () => Number((getCurrentPages()[getCurrentPages().length - 1] as any)?.options?.id);
const left = computed(() => item.value?.holdExpiresAt ? Math.max(0, Date.parse(item.value.holdExpiresAt) - Date.parse(item.value.serverNow) - (localNow.value - receivedAt.value)) : 0);
const clock = computed(() => String(Math.floor(left.value / 60000)).padStart(2, '0') + ':' + String(Math.floor(left.value / 1000) % 60).padStart(2, '0'));
function accept(value: Appointment) { item.value = value; receivedAt.value = localNow.value = Date.now(); if (value.status !== 'HOLDING') uni.removeStorageSync('hospital.booking.key.' + value.scheduleId + '.' + (value.slotId ?? 'session') + '.' + value.memberId); }
function errorMessage(error: any) { const code = error?.data?.code; return ({ APPOINTMENT_004: '号源保留已超时，请重新选择', APPOINTMENT_011: '该门诊已停诊或不可预约，请重新选择', APPOINTMENT_012: '该时段已不可预约，请重新选择' } as Record<string, string>)[code] || '预约状态同步失败，请检查网络后重试'; }
async function load() { if (loading) return; loading = true; try { accept((await appointmentApi.detail(id())).data); const queues=(await appointmentApi.queues()).data; queue.value=queues.find(x=>x.queueNo===queueNo.value)||queues[0]||null; tip.value = ''; } catch (error) { tip.value = errorMessage(error); } finally { loading = false; } }
async function confirm() { if (busy.value || item.value?.status !== 'HOLDING' || left.value === 0) return; busy.value = true; try { accept((await appointmentApi.confirm(id())).data); tip.value = ''; } catch (error) { await load(); const latest = item.value as Appointment | null; if (latest?.status !== 'BOOKED') tip.value = errorMessage(error); } finally { busy.value = false; } }
async function cancel() { if (busy.value || !item.value) return; const appointment = item.value; const confirmed = await new Promise<boolean>(resolve => uni.showModal({ title: '确认取消预约', content: (appointment.memberName || '就诊人') + ' · ' + appointment.doctorName + ' · ' + appointment.scheduleDate + ' ' + appointment.startTime + '-' + appointment.endTime + '\n取消后号源将释放。', success: result => resolve(result.confirm), fail: () => resolve(false) })); if (!confirmed) return; busy.value = true; try { accept((await appointmentApi.cancel(id(), { reasonCode: 'PATIENT_CANCEL', reason: '患者主动取消' })).data); tip.value = ''; } catch { await load(); if (item.value?.status !== 'CANCELLED') tip.value = '取消结果尚未确认，请联网后刷新查看'; } finally { busy.value = false; } }
async function checkIn() { if (!item.value || busy.value) return; busy.value=true; try { const value=(await appointmentApi.checkIn(id())).data; queueNo.value=value.queueNo; await load(); tip.value='已签到，请留意现场叫号'; } catch { tip.value='当前暂不能签到，请以医院服务时间和缴费状态为准。'; } finally { busy.value=false; } }
function restart() { uni.reLaunch({ url: '/pages/index/index' }); } function openList() { uni.navigateTo({ url: '/pages/appointments/index' }); }
const timer = setInterval(() => { localNow.value = Date.now(); if (item.value?.status === 'HOLDING' && left.value === 0 && localNow.value - lastPoll > 3000) { lastPoll = localNow.value; void load(); } if(queue.value&&!['DONE','CANCELLED'].includes(queue.value.status)&&localNow.value-lastPoll>10000){lastPoll=localNow.value;void load();} }, 500);
onShow(load); onBeforeUnmount(() => clearInterval(timer));
</script>
<template><view class="page"><view v-if="!item" class="card"><text v-if="tip" class="tip">{{ tip }}</text><text v-else>正在加载预约…</text><button v-if="tip" @click="load">刷新重试</button></view><view v-else class="card"><text class="title">{{ item.status==='BOOKED'?'预约成功':'预约详情' }}</text><text>预约编号：{{ item.appointmentNo }}</text><text>就诊人：{{ item.memberName||'就诊人' }}</text><text>{{ item.doctorName }} · {{ item.departmentName }} · {{ item.campusName }}</text><text>{{ item.scheduleDate }} · {{ item.sessionName }} · {{ item.startTime }}-{{ item.endTime }}</text><view v-if="item.status==='HOLDING'"><text class="count">号源已为您保留 {{ clock }}</text><button :disabled="busy||left===0" @click="confirm">确认预约</button><button :disabled="busy" @click="cancel">放弃本次预约</button></view><view v-else><button v-if="item.status==='BOOKED'" :disabled="busy" @click="checkIn">到院签到</button><view v-if="queue" class="queue"><text class="count">候诊号 {{ queue.queueNo }}</text><text>状态：{{ queue.status }}</text><text>诊室：{{ queue.roomName||'待安排' }}</text><text v-if="queue.status==='WAITING'">前方候诊 {{ queue.aheadCount }} 人</text></view><button v-if="item.status==='BOOKED'" :disabled="busy" @click="cancel">取消预约</button></view><RegistrationPaymentStatus v-if="item.status!=='HOLDING'" :appointment-id="item.id" :status="item.status" :refresh-at="receivedAt"/><text v-if="tip" class="tip">{{ tip }}</text><button @click="openList">我的预约</button></view></view></template>
<style scoped>.page{padding:28rpx}.card{display:flex;flex-direction:column;gap:20rpx;background:#fff;border-radius:16rpx;padding:28rpx}.title{font-size:40rpx;font-weight:700}.count{font-size:36rpx;color:#176b92;font-weight:700}.tip{color:#b45309}</style>
