package com.hospital.platform.appointment;

import com.hospital.platform.common.api.PageResponse;
import com.hospital.platform.common.error.BusinessException;
import com.hospital.platform.common.error.ErrorCode;
import com.hospital.platform.common.trace.TraceId;
import com.hospital.platform.scheduling.SchedulingService;
import com.hospital.platform.iam.application.DataScopeQueryService;
import com.hospital.platform.patient.PatientCrypto;
import com.hospital.platform.payment.RefundService;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.time.*;
import java.util.*;
import java.util.concurrent.CompletableFuture;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.dao.DuplicateKeyException;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Service;
import org.springframework.transaction.support.TransactionTemplate;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.transaction.annotation.Isolation;
import org.springframework.transaction.support.TransactionSynchronization;
import org.springframework.transaction.support.TransactionSynchronizationManager;

/** MySQL appointment/status rows and conditional quota writes are authoritative; Redis is rebuilt by SchedulingService. */
@Service public class AppointmentService {
  private final JdbcTemplate jdbc; private final SchedulingService quota; private final TransactionTemplate tx; private final DataScopeQueryService scopes; private final PatientCrypto crypto; private final RefundService refunds; private final int ttl,batch,maxAhead,minAdvance,cancelDeadlineMinutes; private final boolean verified;
  public AppointmentService(JdbcTemplate jdbc,SchedulingService quota,TransactionTemplate tx,DataScopeQueryService scopes,PatientCrypto crypto,RefundService refunds,@Value("${hospital.appointment.hold-ttl-seconds:300}")int ttl,@Value("${hospital.appointment.expiration.batch-size:100}")int batch,@Value("${hospital.appointment.booking.max-days-ahead:30}")int maxAhead,@Value("${hospital.appointment.booking.min-advance-minutes:15}")int minAdvance,@Value("${hospital.appointment.cancel.deadline-minutes-before-start:30}")int cancelDeadlineMinutes,@Value("${hospital.appointment.require-verified-identity:false}")boolean verified){this.jdbc=jdbc;this.quota=quota;this.tx=tx;this.scopes=scopes;this.crypto=crypto;this.refunds=refunds;this.tx.setIsolationLevelName("ISOLATION_READ_COMMITTED");this.ttl=ttl;this.batch=batch;this.maxAhead=maxAhead;this.minAdvance=minAdvance;this.cancelDeadlineMinutes=Math.max(0,cancelDeadlineMinutes);this.verified=verified;}
  /** A duplicate insert must roll back its quota mutation before the idempotency replay is read. */
  public View hold(long patientId,HoldRequest r,String key,String source){if(key==null||key.isBlank()||key.length()>128)throw new BusinessException(ErrorCode.VALIDATION);String fp=hash(patientId+":"+r.memberId+":"+r.scheduleId+":"+r.slotId);View replay=replay(patientId,key,fp);if(replay!=null)return replay;try{return tx.execute(s->holdTx(patientId,r,key,fp,source));}catch(DuplicateKeyException e){View concurrent=replay(patientId,key,fp);if(concurrent!=null)return concurrent;throw new BusinessException(ErrorCode.APPOINTMENT_DUPLICATE);}}
  private View holdTx(long patientId,HoldRequest r,String key,String fp,String source){View replay=replay(patientId,key,fp);if(replay!=null)return replay;member(patientId,r.memberId);schedule(r.scheduleId,r.slotId);String active=r.memberId+":"+r.scheduleId;if(!quota.reserveBookable(r.scheduleId,r.slotId,1))throw new BusinessException(ErrorCode.QUOTA_NOT_ENOUGH);String no="AP"+UUID.randomUUID().toString().replace("-","").toUpperCase(Locale.ROOT);Instant expiry=Instant.now().plusSeconds(ttl);jdbc.update("insert into appointment(appointment_no,patient_id,member_id,schedule_id,slot_id,status,source_client,hold_expires_at,idempotency_key,request_fingerprint,active_booking_key,created_by,updated_by) values(?,?,?,?,?,'HOLDING',?,?,?,?,?,?,?)",no,patientId,r.memberId,r.scheduleId,r.slotId,source,java.sql.Timestamp.from(expiry),key,fp,active,patientId,patientId);long id=jdbc.queryForObject("select id from appointment where appointment_no=?",Long.class,no);history(id,null,"HOLDING",null,null,"PATIENT",patientId);return view(one(id));}
  public View confirm(long patientId,long id){ConfirmResult result=tx.execute(s->confirmTx(patientId,id));if(result.expired)throw new BusinessException(ErrorCode.APPOINTMENT_EXPIRED);return result.view;}
  private ConfirmResult confirmTx(long patientId,long id){for(int attempts=0;attempts<3;attempts++){Map<String,Object> a=owned(patientId,id);String status=String.valueOf(a.get("status"));if("BOOKED".equals(status))return new ConfirmResult(view(a),false);if(!"HOLDING".equals(status))throw new BusinessException(ErrorCode.APPOINTMENT_NOT_HOLDING);if(expired(a)){expireRow(a,"TTL");return new ConfirmResult(null,true);}confirmSchedule(num(a,"schedule_id"),number(a,"slot_id"));if(jdbc.update("update appointment set status='BOOKED',booked_at=current_timestamp(3),hold_expires_at=null,version=version+1,updated_by=? where id=? and status='HOLDING'",patientId,id)==1){quota.commit(num(a,"schedule_id"),number(a,"slot_id"),1);history(id,"HOLDING","BOOKED",null,null,"PATIENT",patientId);return new ConfirmResult(view(one(id)),false);}}throw new BusinessException(ErrorCode.APPOINTMENT_INVALID_STATE);}
  @Transactional(isolation=Isolation.READ_COMMITTED) public View cancel(long patientId,long id,String code,String reason){return cancelOwned(patientId,id,code,reason,"PATIENT",patientId);}
  @Transactional(isolation=Isolation.READ_COMMITTED) public View cancelByStaff(long actor,long id,String code,String reason){Map<String,Object>a=adminOne(actor,id);return cancelRow(a,id,code,reason,"STAFF",actor);}
  @Transactional(isolation=Isolation.READ_COMMITTED) public View cancelBySystem(long id,String code,String reason){return cancelRow(one(id),id,code,reason,"SYSTEM",0);}
  /** Called as part of a stop transaction. The status compare-and-set makes retry and recovery idempotent. */
  @Transactional(isolation=Isolation.READ_COMMITTED) public int cancelForStoppedSchedule(long scheduleId,long actor){int cancelled=0;while(true){List<Map<String,Object>> rows=jdbc.queryForList("select * from appointment where schedule_id=? and deleted=0 and status in ('HOLDING','BOOKED') order by id limit ?",scheduleId,batch);if(rows.isEmpty())return cancelled;for(Map<String,Object> row:rows){String before=String.valueOf(row.get("status"));View after=cancelRow(row,num(row,"id"),"SCHEDULE_STOPPED","排班已停诊","SYSTEM",actor);if(!before.equals(after.status()))cancelled++;}}}
  private View cancelOwned(long patientId,long id,String code,String reason,String type,long actor){return cancelRow(owned(patientId,id),id,code,reason,type,actor);}
  private View cancelRow(Map<String,Object>a,long id,String code,String reason,String type,long actor){if(("STAFF".equals(type)&&(reason==null||reason.isBlank()))||(reason!=null&&reason.length()>512))throw new BusinessException(ErrorCode.VALIDATION);for(int attempts=0;attempts<3;attempts++){String status=String.valueOf(a.get("status"));if("CANCELLED".equals(status)||"EXPIRED".equals(status))return view(a);if(!List.of("HOLDING","BOOKED").contains(status))throw new BusinessException(ErrorCode.APPOINTMENT_INVALID_STATE);if("PATIENT".equals(type)&&"BOOKED".equals(status)&&!withinPatientCancellationWindow(num(a,"schedule_id")))throw new BusinessException(ErrorCode.APPOINTMENT_CANCEL_DEADLINE_PASSED);if(jdbc.update("update appointment set status='CANCELLED',cancelled_at=current_timestamp(3),cancel_reason_code=?,cancel_reason=?,active_booking_key=null,version=version+1,updated_by=? where id=? and status=?",code,reason,actor,id,status)==1){if("HOLDING".equals(status))quota.release(num(a,"schedule_id"),number(a,"slot_id"),1);else quota.releaseBooked(num(a,"schedule_id"),number(a,"slot_id"),1);history(id,status,"CANCELLED",code,reason,type,actor);afterCommitRefund(id,code,reason,type,actor);return view(one(id));}a=one(id);}throw new BusinessException(ErrorCode.APPOINTMENT_INVALID_STATE);}
  private void afterCommitRefund(long appointment,String code,String reason,String type,long actor){Runnable work=()->refunds.ensureCancelled(appointment,code,reason,type,actor);if(TransactionSynchronizationManager.isSynchronizationActive())TransactionSynchronizationManager.registerSynchronization(new TransactionSynchronization(){@Override public void afterCommit(){CompletableFuture.runAsync(work);}});else work.run();}
  /** Detail is the authoritative recovery read: it materializes an elapsed HOLD before returning it. */
  public View detail(long patient,long id){return tx.execute(s->{Map<String,Object>a=owned(patient,id);if("HOLDING".equals(a.get("status"))&&expired(a)){expireRow(a,"TTL");a=one(id);}return view(a);});}
  public PageResponse<View> list(long patient,String status,long page,long size){List<Object>a=new ArrayList<>(List.of(patient));String where="a.patient_id=? and a.deleted=0";if(status!=null&&!status.isBlank()){where+=" and a.status=?";a.add(status);}Long total=jdbc.queryForObject("select count(*) from appointment a where "+where,Long.class,a.toArray());a.add(Math.min(100,Math.max(1,size)));a.add((Math.max(1,page)-1)*Math.min(100,Math.max(1,size)));return new PageResponse<>(Math.max(1,page),Math.min(100,Math.max(1,size)),total,jdbc.queryForList(patientSelect()+" where "+where+" order by a.id desc limit ? offset ?",a.toArray()).stream().map(this::view).toList());}
  public PageResponse<AdminListView> adminList(long actor,AdminQuery q){List<Long> allowed=scopes.visibleAdministrativeDepartmentIds(actor);long page=Math.max(1,q.page()),size=Math.min(100,Math.max(1,q.pageSize()));if(allowed.isEmpty())return new PageResponse<>(page,size,0,List.of());String scope=" d.administrative_department_id in ("+marks(allowed.size())+")";List<Object> args=new ArrayList<>(allowed);String where=" a.deleted=0 and "+scope;if(q.appointmentNo()!=null&&!q.appointmentNo().isBlank()){where+=" and a.appointment_no=?";args.add(q.appointmentNo().trim());}if(q.patientNo()!=null&&!q.patientNo().isBlank()){where+=" and p.patient_no=?";args.add(q.patientNo().trim());}if(q.memberName()!=null&&!q.memberName().isBlank()){where+=" and m.name_hash=?";args.add(crypto.hmac(q.memberName().trim()));}if(q.doctorId()!=null){where+=" and coalesce(s.substitute_doctor_id,s.doctor_id)=?";args.add(q.doctorId());}if(q.departmentId()!=null){where+=" and d.id=?";args.add(q.departmentId());}if(q.campusId()!=null){where+=" and s.campus_id=?";args.add(q.campusId());}if(q.clinicTypeId()!=null){where+=" and s.clinic_type_id=?";args.add(q.clinicTypeId());}if(q.scheduleDate()!=null){where+=" and s.schedule_date=?";args.add(q.scheduleDate());}if(q.status()!=null&&!q.status().isBlank()){where+=" and a.status=?";args.add(q.status());}if(q.createdFrom()!=null){where+=" and a.created_at>=?";args.add(q.createdFrom().atStartOfDay());}if(q.createdTo()!=null){where+=" and a.created_at< ?";args.add(q.createdTo().plusDays(1).atStartOfDay());}String joins=adminJoins();Long total=jdbc.queryForObject("select count(*)"+joins+" where "+where,Long.class,args.toArray());List<Object> pageArgs=new ArrayList<>(args);pageArgs.add(size);pageArgs.add((page-1)*size);String sql="select a.id,a.appointment_no appointmentNo,a.status,a.patient_id patientId,p.patient_no patientNo,m.name_encrypted memberNameEncrypted,m.relationship_code relationship,coalesce(s.substitute_doctor_id,s.doctor_id) doctorId,dr.name doctorName,originalDr.name originalDoctorName,s.substitute_doctor_id substituteDoctorId,d.department_name departmentName,campus.name campusName,ct.name clinicType,s.schedule_date scheduleDate,s.start_time startTime,s.end_time endTime,a.hold_expires_at holdExpiresAt,a.booked_at bookedAt,a.cancelled_at cancelledAt,a.created_at createdAt"+joins+" where "+where+" order by a.id desc limit ? offset ?";return new PageResponse<>(page,size,total==null?0:total,jdbc.queryForList(sql,pageArgs.toArray()).stream().map(this::adminListView).toList());}
  public AdminDetailView adminDetail(long actor,long id){Map<String,Object>a=adminOne(actor,id);Map<String,Object> row=jdbc.queryForList("select a.id,a.appointment_no appointmentNo,a.status,a.patient_id patientId,p.patient_no patientNo,m.name_encrypted memberNameEncrypted,m.relationship_code relationship,coalesce(s.substitute_doctor_id,s.doctor_id) doctorId,dr.name doctorName,originalDr.name originalDoctorName,s.substitute_doctor_id substituteDoctorId,d.department_name departmentName,campus.name campusName,ct.name clinicType,s.schedule_date scheduleDate,s.start_time startTime,s.end_time endTime,a.hold_expires_at holdExpiresAt,a.booked_at bookedAt,a.cancelled_at cancelledAt,a.expired_at expiredAt,a.cancel_reason_code cancelReasonCode,a.cancel_reason cancelReason,a.created_at createdAt"+adminJoins()+" where a.id=?",id).getFirst();List<Map<String,Object>> history=jdbc.queryForList("select from_status fromStatus,to_status toStatus,reason_code reasonCode,reason,operator_type operatorType,operator_id operatorId,trace_id traceId,created_at createdAt from appointment_status_history where appointment_id=? order by id",id);List<Map<String,Object>> audit=jdbc.queryForList("select action,result,trace_id traceId,created_at createdAt from sys_audit_log where resource_type='APPOINTMENT' and resource_id=? order by id desc",String.valueOf(id));Map<String,Object> inventory=inventory(a);return new AdminDetailView(adminListView(row),history,inventory,audit);}
  private Map<String,Object> adminOne(long actor,long id){List<Long> allowed=scopes.visibleAdministrativeDepartmentIds(actor);if(allowed.isEmpty())throw new BusinessException(ErrorCode.FORBIDDEN);String sql="select a.* from appointment a join doctor_schedule s on s.id=a.schedule_id join outpatient_department od on od.id=s.outpatient_department_id join department d on d.id=od.department_id where a.id=? and a.deleted=0 and d.administrative_department_id in ("+marks(allowed.size())+")";List<Object> args=new ArrayList<>();args.add(id);args.addAll(allowed);List<Map<String,Object>> rows=jdbc.queryForList(sql,args.toArray());if(rows.isEmpty())throw new BusinessException(ErrorCode.FORBIDDEN);return rows.getFirst();}
  private String adminJoins(){return " from appointment a join patient p on p.id=a.patient_id join patient_member m on m.id=a.member_id join doctor_schedule s on s.id=a.schedule_id join outpatient_department od on od.id=s.outpatient_department_id join department d on d.id=od.department_id join hospital_campus campus on campus.id=s.campus_id join doctor dr on dr.id=coalesce(s.substitute_doctor_id,s.doctor_id) left join doctor originalDr on originalDr.id=s.original_doctor_id left join clinic_type ct on ct.id=s.clinic_type_id";}
  private String patientSelect(){return "select a.*,m.name_encrypted memberNameEncrypted,dr.name doctorName,originalDr.name originalDoctorName,s.substitute_doctor_id substituteDoctorId,d.department_name departmentName,campus.name campusName,ct.name clinicType,s.schedule_date scheduleDate,sd.name sessionName,s.start_time startTime,s.end_time endTime from appointment a left join patient_member m on m.id=a.member_id left join doctor_schedule s on s.id=a.schedule_id left join outpatient_department od on od.id=s.outpatient_department_id left join department d on d.id=od.department_id left join hospital_campus campus on campus.id=s.campus_id left join doctor dr on dr.id=coalesce(s.substitute_doctor_id,s.doctor_id) left join doctor originalDr on originalDr.id=s.original_doctor_id left join schedule_session_definition sd on sd.id=s.session_definition_id left join clinic_type ct on ct.id=s.clinic_type_id";}
  private String maskedName(Object encrypted){String value=encrypted==null?"":crypto.decrypt(String.valueOf(encrypted));return value.length()<2?"*":value.substring(0,1)+"*";} private AdminListView adminListView(Map<String,Object> r){return new AdminListView(num(r,"id"),String.valueOf(r.get("appointmentNo")),String.valueOf(r.get("status")),String.valueOf(r.get("patientNo")),maskedName(r.get("memberNameEncrypted")),String.valueOf(r.get("relationship")),num(r,"doctorId"),String.valueOf(r.get("doctorName")),text(r.get("originalDoctorName")),r.get("substituteDoctorId")!=null,String.valueOf(r.get("departmentName")),String.valueOf(r.get("campusName")),r.get("clinicType")==null?null:String.valueOf(r.get("clinicType")),r.get("scheduleDate"),r.get("startTime"),r.get("endTime"),r.get("holdExpiresAt"),r.get("bookedAt"),r.get("cancelledAt"),r.get("createdAt"));}
  @Scheduled(fixedDelayString="${hospital.appointment.expiration.interval-ms:30000}") @Transactional public void expireDue(){for(Map<String,Object>a:jdbc.queryForList("select * from appointment where status='HOLDING' and hold_expires_at<=current_timestamp(3) order by id limit ?",batch))expireRow(a,"TTL");}
  @Transactional public void expireRow(Map<String,Object>a,String reason){long id=num(a,"id");if(jdbc.update("update appointment set status='EXPIRED',expired_at=current_timestamp(3),active_booking_key=null,version=version+1 where id=? and status='HOLDING'",id)==1){quota.release(num(a,"schedule_id"),number(a,"slot_id"),1);history(id,"HOLDING","EXPIRED",reason,null,"SYSTEM",null);}}
  private void member(long patient,long member){Long active=jdbc.queryForObject("select count(*) from patient where id=? and deleted=0 and status=1",Long.class,patient);if(active==null||active==0)throw new BusinessException(ErrorCode.MEMBER_NOT_ELIGIBLE);Map<String,Object>m=jdbc.queryForList("select * from patient_member where id=? and patient_id=? and deleted=0",member,patient).stream().findFirst().orElseThrow(()->new BusinessException(ErrorCode.MEMBER_NOT_OWNED));if(!"ACTIVE".equals(m.get("status")))throw new BusinessException(ErrorCode.MEMBER_NOT_ELIGIBLE);if(verified&&!"VERIFIED".equals(m.get("real_name_status")))throw new BusinessException(ErrorCode.MEMBER_NOT_ELIGIBLE);}
  private void schedule(long schedule,Long slot){Map<String,Object>s=jdbc.queryForList("select * from doctor_schedule where id=? and deleted=0 and schedule_status='PUBLISHED' and schedule_date>=current_date()",schedule).stream().findFirst().orElseThrow(()->new BusinessException(ErrorCode.SCHEDULE_NOT_BOOKABLE));LocalDate date=((java.sql.Date)s.get("schedule_date")).toLocalDate();LocalTime start=((java.sql.Time)s.get("start_time")).toLocalTime();if(date.isAfter(LocalDate.now().plusDays(maxAhead))||!LocalDateTime.of(date,start).isAfter(LocalDateTime.now().plusMinutes(minAdvance)))throw new BusinessException(ErrorCode.BOOKING_WINDOW_CLOSED);boolean slotMode=num(s,"slot_mode")==1;if(slotMode!= (slot!=null))throw new BusinessException(slotMode?ErrorCode.SLOT_NOT_BOOKABLE:ErrorCode.SCHEDULE_NOT_BOOKABLE);if(slot!=null&&jdbc.queryForObject("select count(*) from schedule_slot where id=? and schedule_id=? and deleted=0 and status='ACTIVE'",Long.class,slot,schedule)==0)throw new BusinessException(ErrorCode.SLOT_NOT_BOOKABLE);}
  private void confirmSchedule(long schedule,Long slot){Long available=jdbc.queryForObject("select count(*) from doctor_schedule where id=? and deleted=0 and schedule_status='PUBLISHED' and schedule_date>=current_date()",Long.class,schedule);if(available==null||available==0)throw new BusinessException(ErrorCode.SCHEDULE_NOT_BOOKABLE);if(slot!=null&&jdbc.queryForObject("select count(*) from schedule_slot where id=? and schedule_id=? and deleted=0 and status='ACTIVE'",Long.class,slot,schedule)==0)throw new BusinessException(ErrorCode.SLOT_NOT_BOOKABLE);}
  private View replay(long patient,String key,String fp){List<Map<String,Object>> rows=jdbc.queryForList("select * from appointment where patient_id=? and idempotency_key=?",patient,key);if(rows.isEmpty())return null;if(!fp.equals(rows.getFirst().get("request_fingerprint")))throw new BusinessException(ErrorCode.APPOINTMENT_IDEMPOTENCY_CONFLICT);return view(rows.getFirst());}
  private Map<String,Object> owned(long patient,long id){Map<String,Object>a=jdbc.queryForList("select * from appointment where id=? and deleted=0",id).stream().findFirst().orElseThrow(()->new BusinessException(ErrorCode.APPOINTMENT_NOT_FOUND));if(num(a,"patient_id")!=patient)throw new BusinessException(ErrorCode.APPOINTMENT_NOT_OWNED);return a;} private Map<String,Object> one(long id){return jdbc.queryForList("select * from appointment where id=?",id).getFirst();}
  private boolean expired(Map<String,Object>a){Object x=a.get("hold_expires_at");if(x instanceof java.sql.Timestamp t)return t.toInstant().compareTo(Instant.now())<=0;if(x instanceof LocalDateTime t)return !t.isAfter(LocalDateTime.now(ZoneOffset.UTC));if(x instanceof Instant t)return !t.isAfter(Instant.now());return false;} private boolean withinPatientCancellationWindow(long scheduleId){Map<String,Object> schedule=jdbc.queryForMap("select schedule_date,start_time from doctor_schedule where id=? and deleted=0",scheduleId);LocalDate date=((java.sql.Date)schedule.get("schedule_date")).toLocalDate();LocalTime start=((java.sql.Time)schedule.get("start_time")).toLocalTime();return LocalDateTime.of(date,start).isAfter(LocalDateTime.now().plusMinutes(cancelDeadlineMinutes));} private void history(long id,String from,String to,String code,String reason,String type,Long operator){jdbc.update("insert into appointment_status_history(appointment_id,from_status,to_status,reason_code,reason,operator_type,operator_id,trace_id) values(?,?,?,?,?,?,?,?)",id,from,to,code,reason,type,operator,TraceId.get());}
  private Map<String,Object> inventory(Map<String,Object>a){Map<String,Object> value=new LinkedHashMap<>();Map<String,Object> schedule=jdbc.queryForMap("select id,total_quota totalQuota,reserved_quota reservedQuota,booked_quota bookedQuota,total_quota-reserved_quota-booked_quota availableQuota,slot_mode slotMode from doctor_schedule where id=?",num(a,"schedule_id"));if(((Number)schedule.get("slotMode")).intValue()==1){Map<String,Object> totals=jdbc.queryForMap("select coalesce(sum(total_quota),0) totalQuota,coalesce(sum(reserved_quota),0) reservedQuota,coalesce(sum(booked_quota),0) bookedQuota,coalesce(sum(total_quota-reserved_quota-booked_quota),0) availableQuota from schedule_slot where schedule_id=? and deleted=0",num(a,"schedule_id"));schedule.putAll(totals);}schedule.remove("slotMode");value.put("schedule",schedule);Long slotId=number(a,"slot_id");if(slotId!=null)value.put("slot",jdbc.queryForMap("select id,total_quota totalQuota,reserved_quota reservedQuota,booked_quota bookedQuota,total_quota-reserved_quota-booked_quota availableQuota from schedule_slot where id=?",slotId));return value;} private View view(Map<String,Object>a){if(!a.containsKey("doctorName")){List<Map<String,Object>> rows=jdbc.queryForList(patientSelect()+" where a.id=?",num(a,"id"));if(!rows.isEmpty())a=rows.getFirst();}return new View(num(a,"id"),String.valueOf(a.get("appointment_no")),String.valueOf(a.get("status")),num(a,"member_id"),num(a,"schedule_id"),number(a,"slot_id"),safeDecrypt(a.get("memberNameEncrypted")),text(a.get("doctorName")),text(a.get("originalDoctorName")),a.get("substituteDoctorId")!=null,text(a.get("departmentName")),text(a.get("campusName")),text(a.get("clinicType")),a.get("scheduleDate"),text(a.get("sessionName")),a.get("startTime"),a.get("endTime"),instant(a.get("created_at")),instant(a.get("hold_expires_at")),instant(a.get("booked_at")),instant(a.get("cancelled_at")),instant(a.get("expired_at")),Instant.now());} private String safeDecrypt(Object encrypted){if(encrypted==null)return null;String value=String.valueOf(encrypted);return value.startsWith("v1:")?crypto.decrypt(value):null;} private String text(Object value){return value==null?null:String.valueOf(value);} private Instant instant(Object value){if(value instanceof java.sql.Timestamp t)return t.toInstant();if(value instanceof LocalDateTime t)return t.toInstant(ZoneOffset.UTC);return value instanceof Instant t?t:null;} private long num(Map<String,Object>a,String k){return ((Number)a.get(k)).longValue();} private Long number(Map<String,Object>a,String k){Object x=a.get(k);return x==null?null:((Number)x).longValue();} private String marks(int size){return String.join(",",Collections.nCopies(size,"?"));} private String hash(String x){try{return java.util.HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(x.getBytes(StandardCharsets.UTF_8)));}catch(Exception e){throw new IllegalStateException(e);}}
  private record ConfirmResult(View view,boolean expired){} public record HoldRequest(long memberId,long scheduleId,Long slotId){} public record View(long id,String appointmentNo,String status,long memberId,long scheduleId,Long slotId,String memberName,String doctorName,String originalDoctorName,boolean substituted,String departmentName,String campusName,String clinicType,Object scheduleDate,String sessionName,Object startTime,Object endTime,Object createdAt,Object holdExpiresAt,Object bookedAt,Object cancelledAt,Object expiredAt,Instant serverNow){} public record AdminQuery(String appointmentNo,String patientNo,String memberName,Long doctorId,Long departmentId,Long campusId,Long clinicTypeId,java.time.LocalDate scheduleDate,String status,java.time.LocalDate createdFrom,java.time.LocalDate createdTo,long page,long pageSize){} public record AdminListView(long id,String appointmentNo,String status,String patientNo,String memberName,String relationship,long doctorId,String doctorName,String originalDoctorName,boolean substituted,String departmentName,String campusName,String clinicType,Object scheduleDate,Object startTime,Object endTime,Object holdExpiresAt,Object bookedAt,Object cancelledAt,Object createdAt){} public record AdminDetailView(AdminListView appointment,List<Map<String,Object>> statusHistory,Map<String,Object> inventory,List<Map<String,Object>> audit){}
}
