package com.hospital.platform.diagnostic;

import com.hospital.platform.common.api.ApiResponse;
import com.hospital.platform.common.error.BusinessException;
import com.hospital.platform.common.error.ErrorCode;
import com.hospital.platform.common.security.AuthenticatedUser;
import com.hospital.platform.common.trace.TraceId;
import java.util.List;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.security.core.annotation.AuthenticationPrincipal;
import org.springframework.web.bind.annotation.*;

/** Doctor, laboratory and imaging endpoints; the actor always comes from SecurityContext. */
@RestController public class DiagnosticController {
  private final DiagnosticService service; public DiagnosticController(DiagnosticService service){this.service=service;}
  @GetMapping("/api/v1/doctor/clinical-service-catalog") @PreAuthorize("hasAuthority('hospital:clinical:order:create')") public ApiResponse<List<DiagnosticService.ServiceItem>> catalog(@RequestParam(defaultValue="")String type){return ok(service.catalog(type));}
  @GetMapping("/api/v1/doctor/visits/{encounterId}/orders") @PreAuthorize("hasAuthority('hospital:clinical:order:view')") public ApiResponse<List<DiagnosticService.OrderView>> list(@AuthenticationPrincipal AuthenticatedUser u,@PathVariable long encounterId){return ok(service.doctorOrders(user(u),encounterId));}
  @PostMapping("/api/v1/doctor/visits/{encounterId}/orders/{type}") @PreAuthorize("hasAuthority('hospital:clinical:order:create')") public ApiResponse<DiagnosticService.OrderView> create(@AuthenticationPrincipal AuthenticatedUser u,@PathVariable long encounterId,@PathVariable String type,@RequestBody DiagnosticService.OrderInput input){return ok(service.create(user(u),encounterId,type,input));}
  @GetMapping("/api/v1/doctor/visits/{encounterId}/orders/{orderId}") @PreAuthorize("hasAuthority('hospital:clinical:order:view')") public ApiResponse<DiagnosticService.OrderView> detail(@AuthenticationPrincipal AuthenticatedUser u,@PathVariable long encounterId,@PathVariable long orderId){return ok(service.detail(user(u),encounterId,orderId));}
  @PostMapping("/api/v1/doctor/visits/{encounterId}/orders/{orderId}/place") @PreAuthorize("hasAuthority('hospital:clinical:order:create')") public ApiResponse<DiagnosticService.OrderView> place(@AuthenticationPrincipal AuthenticatedUser u,@PathVariable long encounterId,@PathVariable long orderId,@RequestBody DiagnosticService.VersionInput input){return ok(service.place(user(u),encounterId,orderId,input));}
  @PostMapping("/api/v1/doctor/visits/{encounterId}/orders/{orderId}/provider-submissions") @PreAuthorize("hasAuthority('hospital:clinical:order:create')") public ApiResponse<DiagnosticService.ProviderSubmission> submit(@AuthenticationPrincipal AuthenticatedUser u,@PathVariable long encounterId,@PathVariable long orderId,@RequestBody DiagnosticService.ProviderSubmissionInput input){return ok(service.submitToProvider(user(u),encounterId,orderId,input));}
  @PostMapping("/api/v1/doctor/visits/{encounterId}/orders/{orderId}/cancel") @PreAuthorize("hasAuthority('hospital:clinical:order:cancel')") public ApiResponse<DiagnosticService.OrderView> cancel(@AuthenticationPrincipal AuthenticatedUser u,@PathVariable long encounterId,@PathVariable long orderId,@RequestBody DiagnosticService.Reason input){return ok(service.cancel(user(u),encounterId,orderId,input));}
  @GetMapping("/api/v1/doctor/visits/{encounterId}/orders/{orderId}/integrity") @PreAuthorize("hasAuthority('hospital:clinical:order:view')") public ApiResponse<Integrity> integrity(@AuthenticationPrincipal AuthenticatedUser u,@PathVariable long encounterId,@PathVariable long orderId){return ok(new Integrity(service.verifyOrder(user(u),encounterId,orderId)));}
  @GetMapping("/api/v1/doctor/diagnostic-reports/pending") @PreAuthorize("hasAuthority('hospital:clinical:result:view')") public ApiResponse<List<DiagnosticService.ReportView>> pending(@AuthenticationPrincipal AuthenticatedUser u){return ok(service.pendingReports(user(u)));}
  @PostMapping("/api/v1/doctor/diagnostic-reports/{reportId}/review") @PreAuthorize("hasAuthority('hospital:clinical:result:review')") public ApiResponse<Void> review(@AuthenticationPrincipal AuthenticatedUser u,@PathVariable long reportId,@RequestBody DiagnosticService.Reason input){service.review(user(u),reportId,input);return ok(null);}
  @PostMapping("/api/v1/doctor/diagnostic-reports/{reportId}/release") @PreAuthorize("hasAuthority('hospital:clinical:result:review')") public ApiResponse<DiagnosticService.ReportView> release(@AuthenticationPrincipal AuthenticatedUser u,@PathVariable long reportId){return ok(service.releaseForPatient(user(u),reportId));}
  @GetMapping("/api/v1/doctor/critical-alerts") @PreAuthorize("hasAuthority('hospital:clinical:result:view')") public ApiResponse<List<DiagnosticService.AlertView>> alerts(@AuthenticationPrincipal AuthenticatedUser u){return ok(service.alerts(user(u)));}
  @PostMapping("/api/v1/doctor/critical-alerts/{alertId}/acknowledge") @PreAuthorize("hasAuthority('hospital:clinical:result:review')") public ApiResponse<DiagnosticService.AlertView> acknowledge(@AuthenticationPrincipal AuthenticatedUser u,@PathVariable long alertId,@RequestBody DiagnosticService.Reason input){return ok(service.acknowledge(user(u),alertId,input));}
  @GetMapping("/api/v1/lab/specimens") @PreAuthorize("hasAnyAuthority('hospital:clinical:lab:specimen:list','hospital:clinical:lab:specimen:collect','hospital:clinical:lab:specimen:receive','hospital:clinical:lab:result:entry','hospital:clinical:lab:result:verify')") public ApiResponse<List<DiagnosticService.SpecimenView>> specimens(@AuthenticationPrincipal AuthenticatedUser u,@RequestParam(defaultValue="")String status){return ok(service.specimens(user(u),status));}
  @PostMapping("/api/v1/lab/specimens/{id}/collect") @PreAuthorize("hasAuthority('hospital:clinical:lab:specimen:collect')") public ApiResponse<DiagnosticService.SpecimenView> collect(@AuthenticationPrincipal AuthenticatedUser u,@PathVariable long id,@RequestBody DiagnosticService.VersionInput input){return ok(service.collect(user(u),id,input));}
  @PostMapping("/api/v1/lab/specimens/{id}/receive") @PreAuthorize("hasAuthority('hospital:clinical:lab:specimen:receive')") public ApiResponse<DiagnosticService.SpecimenView> receive(@AuthenticationPrincipal AuthenticatedUser u,@PathVariable long id,@RequestBody DiagnosticService.VersionInput input){return ok(service.receive(user(u),id,input));}
  @PostMapping("/api/v1/lab/specimens/{id}/reject") @PreAuthorize("hasAuthority('hospital:clinical:lab:specimen:receive')") public ApiResponse<DiagnosticService.SpecimenView> reject(@AuthenticationPrincipal AuthenticatedUser u,@PathVariable long id,@RequestBody DiagnosticService.RejectInput input){return ok(service.reject(user(u),id,input));}
  @PostMapping("/api/v1/lab/specimens/{id}/recollect") @PreAuthorize("hasAuthority('hospital:clinical:lab:specimen:collect')") public ApiResponse<DiagnosticService.SpecimenView> recollect(@AuthenticationPrincipal AuthenticatedUser u,@PathVariable long id){return ok(service.recollect(user(u),id));}
  @PostMapping("/api/v1/lab/results") @PreAuthorize("hasAuthority('hospital:clinical:lab:result:entry')") public ApiResponse<DiagnosticService.ResultView> enter(@AuthenticationPrincipal AuthenticatedUser u,@RequestBody DiagnosticService.ResultInput input){return ok(service.enterResult(user(u),input));}
  @GetMapping("/api/v1/lab/results") @PreAuthorize("hasAnyAuthority('hospital:clinical:lab:result:entry','hospital:clinical:lab:result:verify')") public ApiResponse<List<DiagnosticService.ResultView>> results(@AuthenticationPrincipal AuthenticatedUser u,@RequestParam(defaultValue="")String status){return ok(service.results(user(u),status));}
  @PostMapping("/api/v1/lab/results/{resultId}/verify") @PreAuthorize("hasAuthority('hospital:clinical:lab:result:verify')") public ApiResponse<DiagnosticService.ResultView> verify(@AuthenticationPrincipal AuthenticatedUser u,@PathVariable long resultId){return ok(service.verifyResult(user(u),resultId));}
  @GetMapping("/api/v1/imaging/orders") @PreAuthorize("hasAnyAuthority('hospital:clinical:imaging:study:execute','hospital:clinical:imaging:report:create')") public ApiResponse<List<DiagnosticService.ImagingOrderView>> imagingOrders(@AuthenticationPrincipal AuthenticatedUser u,@RequestParam(defaultValue="")String status){return ok(service.imagingOrders(user(u),status));}
  @PostMapping("/api/v1/imaging/orders/{orderId}/acquire") @PreAuthorize("hasAuthority('hospital:clinical:imaging:study:execute')") public ApiResponse<DiagnosticService.StudyView> acquire(@AuthenticationPrincipal AuthenticatedUser u,@PathVariable long orderId){return ok(service.acquireStudy(user(u),orderId));}
  @PostMapping("/api/v1/imaging/orders/{orderId}/reports") @PreAuthorize("hasAuthority('hospital:clinical:imaging:report:create')") public ApiResponse<DiagnosticService.ReportView> imagingReport(@AuthenticationPrincipal AuthenticatedUser u,@PathVariable long orderId,@RequestBody DiagnosticService.ReportInput input){return ok(service.createImagingReport(user(u),orderId,input));}
  @PostMapping("/api/v1/diagnostic-reports/{reportId}/sign") @PreAuthorize("hasAuthority('hospital:clinical:report:sign')") public ApiResponse<DiagnosticService.ReportView> sign(@AuthenticationPrincipal AuthenticatedUser u,@PathVariable long reportId,@RequestBody DiagnosticService.VersionInput input){return ok(service.signReport(user(u),reportId,input));}
  @PutMapping("/api/v1/diagnostic-reports/{reportId}/draft") @PreAuthorize("hasAuthority('hospital:clinical:report:sign')") public ApiResponse<DiagnosticService.ReportView> updateDraft(@AuthenticationPrincipal AuthenticatedUser u,@PathVariable long reportId,@RequestBody DiagnosticService.DraftReportInput input){return ok(service.updateDraftReport(user(u),reportId,input));}
  @PostMapping("/api/v1/diagnostic-reports/{reportId}/amendments") @PreAuthorize("hasAuthority('hospital:clinical:report:sign')") public ApiResponse<DiagnosticService.ReportView> amend(@AuthenticationPrincipal AuthenticatedUser u,@PathVariable long reportId,@RequestBody DiagnosticService.ReportInput input){return ok(service.amendReport(user(u),reportId,input));}
  @GetMapping("/api/v1/diagnostic-reports/{reportId}") @PreAuthorize("hasAuthority('hospital:clinical:report:sign')") public ApiResponse<DiagnosticService.ReportView> report(@AuthenticationPrincipal AuthenticatedUser u,@PathVariable long reportId){return ok(service.executionReport(user(u),reportId));}
  @GetMapping("/api/v1/diagnostic-reports/{reportId}/audit") @PreAuthorize("hasAuthority('hospital:clinical:result:audit')") public ApiResponse<DiagnosticService.ReportView> auditReport(@PathVariable long reportId){return ok(service.auditReport(reportId));}
  @GetMapping("/api/v1/diagnostic-reports/{reportId}/revisions") @PreAuthorize("hasAuthority('hospital:clinical:report:sign')") public ApiResponse<List<DiagnosticService.ReportRevisionView>> history(@AuthenticationPrincipal AuthenticatedUser u,@PathVariable long reportId){return ok(service.reportHistory(user(u),reportId));}
  @GetMapping("/api/v1/diagnostic-reports/{reportId}/integrity") @PreAuthorize("hasAuthority('hospital:clinical:result:view')") public ApiResponse<Integrity> reportIntegrity(@AuthenticationPrincipal AuthenticatedUser u,@PathVariable long reportId){return ok(new Integrity(service.verifyReport(user(u),reportId)));}
  private static long user(AuthenticatedUser u){if(u==null)throw new BusinessException(ErrorCode.FORBIDDEN);return u.id();} private static <T>ApiResponse<T> ok(T v){return ApiResponse.success(v,TraceId.get());} public record Integrity(boolean valid){}
}
