package com.hospital.platform.diagnostic;

import com.hospital.platform.common.error.BusinessException;
import com.hospital.platform.common.error.ErrorCode;
import com.hospital.platform.common.trace.TraceId;
import java.math.BigDecimal;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.sql.Timestamp;
import java.time.Instant;
import java.util.HexFormat;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Set;
import java.util.UUID;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

/**
 * Outpatient diagnostics source of truth. State transitions use MySQL row locks and conditional
 * updates; provider payloads, credentials and result bodies are deliberately never logged.
 */
@Service public class DiagnosticService {
  private final JdbcTemplate jdbc; private final boolean testProviderEnabled; private final String patientReleasePolicy;
  public DiagnosticService(JdbcTemplate jdbc,@Value("${hospital.clinical.diagnostic.test-provider-enabled:true}") boolean testProviderEnabled,@Value("${hospital.clinical.diagnostic.patient-release-policy:IMMEDIATE_AFTER_FINAL}") String patientReleasePolicy){this.jdbc=jdbc;this.testProviderEnabled=testProviderEnabled;this.patientReleasePolicy=releasePolicy(patientReleasePolicy);}

  public List<ServiceItem> catalog(String type){return jdbc.queryForList("select * from clinical_service_catalog where status='ACTIVE' and (effective_to is null or effective_to>=current_date) and (?='' or service_type=?) order by service_code",type==null?"":type,type==null?"":type).stream().map(this::service).toList();}
  @Transactional public OrderView create(long user,long encounter,String type,OrderInput input){
    Map<String,Object> e=doctorEncounter(user,encounter); requireConsulting(e); validOrder(type,input);
    Map<String,Object> c=one("select * from clinical_service_catalog where id=? and status='ACTIVE'",input.serviceItemId());
    if(!type.equals(text(c,"service_type")))throw new BusinessException(ErrorCode.VALIDATION);
    validAnatomy(c,input); long revision=signedRevision(encounter);
    String no=no("CO"); jdbc.update("insert into clinical_order(order_no,encounter_id,patient_id,member_id,doctor_id,department_id,medical_record_revision_id,order_type,priority,clinical_indication) values(?,?,?,?,?,?,?,?,?,?)",no,encounter,num(e,"patient_id"),num(e,"member_id"),num(e,"doctor_id"),num(e,"department_id"),revision,type,input.priority()==null?"ROUTINE":input.priority(),clean(input.clinicalIndication(),2048)); long id=id();
    jdbc.update("insert into clinical_order_item(clinical_order_id,service_item_id,item_code_snapshot,item_name_snapshot,category_snapshot,specimen_type_snapshot,body_part,laterality,priority,instructions,sort_order) values(?,?,?,?,?,?,?,?,?,?,0)",id,input.serviceItemId(),text(c,"service_code"),text(c,"service_name"),type,text(c,"specimen_type"),clean(input.bodyPart(),128),clean(input.laterality(),16),input.priority()==null?"ROUTINE":input.priority(),clean(input.instructions(),1024)); audit(user,"ORDER_CREATE","CLINICAL_ORDER",id); return order(id);
  }
  @Transactional public OrderView place(long user,long encounter,long orderId,VersionInput input){
    Map<String,Object> o=doctorOrder(user,encounter,orderId,true); version(o,input.version()); if(!"DRAFT".equals(text(o,"status")))throw new BusinessException(ErrorCode.DIAGNOSTIC_IMMUTABLE); String hash=orderHash(o,items(orderId));
    if(jdbc.update("update clinical_order set status='PLACED',signed_by=?,signed_at=current_timestamp(3),content_hash=?,version=version+1 where id=? and status='DRAFT' and version=?",user,hash,orderId,input.version())!=1)throw new BusinessException(ErrorCode.DIAGNOSTIC_VERSION_CONFLICT);
    if("LAB".equals(text(o,"order_type"))){String specimen=no("SP");String type=text(items(orderId).get(0),"specimen_type_snapshot");jdbc.update("insert into lab_specimen(specimen_no,clinical_order_id,patient_id,member_id,specimen_type) values(?,?,?,?,?)",specimen,orderId,num(o,"patient_id"),num(o,"member_id"),type==null?"TEST_SPECIMEN":type);}
    if("IMAGING".equals(text(o,"order_type"))){Map<String,Object> i=items(orderId).get(0);String study=no("IS");jdbc.update("insert into imaging_study(study_no,clinical_order_id,patient_id,accession_no,modality,body_part,laterality,provider) values(?,?,?,?,?,?,?,?)",study,orderId,num(o,"patient_id"),"TACC-"+study.substring(2),"TEST",text(i,"body_part"),text(i,"laterality"),"TestPacsProvider");}
    audit(user,"ORDER_PLACE","CLINICAL_ORDER",orderId);return order(orderId);
  }
  @Transactional public OrderView cancel(long user,long encounter,long orderId,Reason input){Map<String,Object> o=doctorOrder(user,encounter,orderId,true);if(!Set.of("DRAFT","PLACED","ACCEPTED","SCHEDULED").contains(text(o,"status"))||blank(input.reason()))throw new BusinessException(ErrorCode.DIAGNOSTIC_INVALID_STATE);jdbc.update("update clinical_order set status='CANCELLED',cancelled_at=current_timestamp(3),cancel_reason=?,version=version+1 where id=?",clean(input.reason(),512),orderId);audit(user,"ORDER_CANCEL","CLINICAL_ORDER",orderId);return order(orderId);}
  /** Test-provider submission is persisted on the order so retries cannot create another business submission. */
  @Transactional(noRollbackFor=ProviderPending.class) public ProviderSubmission submitToProvider(long user,long encounter,long orderId,ProviderSubmissionInput input){Map<String,Object>o=doctorOrder(user,encounter,orderId,true);if(!testProviderEnabled)throw new BusinessException(ErrorCode.CLINICAL_INTEGRATION_NOT_CONFIGURED);if(!"PLACED".equals(text(o,"status")))throw new BusinessException(ErrorCode.DIAGNOSTIC_INVALID_STATE);String key=clean(input.businessKey(),96);if(blank(key))throw new BusinessException(ErrorCode.DIAGNOSTIC_REQUIRED_FIELD);String existing=text(o,"provider_submission_key");if(existing!=null){if(!existing.equals(key))throw new BusinessException(ErrorCode.DIAGNOSTIC_ACCESS_DENIED);return providerSubmission(o,existing);}testProviderFailure(orderId,key);try{if(jdbc.update("update clinical_order set provider_submission_key=?,version=version+1 where id=? and provider_submission_key is null",key,orderId)!=1)return providerSubmission(one("select * from clinical_order where id=?",orderId),key);}catch(org.springframework.dao.DuplicateKeyException e){throw new BusinessException(ErrorCode.DIAGNOSTIC_VERSION_CONFLICT);}audit(user,"PROVIDER_SUBMIT","CLINICAL_ORDER",orderId);return providerSubmission(one("select * from clinical_order where id=?",orderId),key);}
  public OrderView detail(long user,long encounter,long id){return orderView(doctorOrder(user,encounter,id,false));}
  public List<OrderView> doctorOrders(long user,long encounter){doctorEncounter(user,encounter);return jdbc.queryForList("select * from clinical_order where encounter_id=? order by id desc",encounter).stream().map(this::orderView).toList();}
  public boolean verifyOrder(long user,long encounter,long id){Map<String,Object> o=doctorOrder(user,encounter,id,false);return "PLACED".equals(text(o,"status"))&&text(o,"content_hash").equals(orderHash(o,items(id)));}

  public List<SpecimenView> specimens(long user,String status){return jdbc.queryForList("select s.* from lab_specimen s join clinical_order o on o.id=s.clinical_order_id join clinical_execution_user_scope scope on scope.user_id=? and scope.department_id=o.department_id and scope.service_type='LAB' where (?='' or s.collection_status=?) order by s.id desc",user,status==null?"":status,status==null?"":status).stream().map(this::specimen).toList();}
  /** Reviewer queue is scoped through the order department, not merely the result identifier. */
  public List<ResultView> results(long user,String status){return jdbc.queryForList("select r.* from lab_result r join clinical_order o on o.id=r.clinical_order_id join clinical_execution_user_scope scope on scope.user_id=? and scope.department_id=o.department_id and scope.service_type='LAB' where (?='' or r.status=?) order by r.id desc",user,status==null?"":status,status==null?"":status).stream().map(row->result(num(row,"id"))).toList();}
  @Transactional public SpecimenView collect(long user,long id,VersionInput input){Map<String,Object>s=specimenForUpdate(id);requireExecutionScope(user,orderDepartment(num(s,"clinical_order_id")),"LAB");version(s,input.version());if(jdbc.update("update lab_specimen set collection_status='COLLECTED',collected_by=?,collected_at=current_timestamp(3),version=version+1 where id=? and collection_status='PENDING_COLLECTION' and version=?",user,id,input.version())!=1)throw new BusinessException(ErrorCode.DIAGNOSTIC_VERSION_CONFLICT);audit(user,"SPECIMEN_COLLECT","LAB_SPECIMEN",id);return specimen(id);}
  @Transactional public SpecimenView receive(long user,long id,VersionInput input){Map<String,Object>s=specimenForUpdate(id);requireExecutionScope(user,orderDepartment(num(s,"clinical_order_id")),"LAB");version(s,input.version());if(jdbc.update("update lab_specimen set collection_status='RECEIVED',received_by=?,received_at=current_timestamp(3),version=version+1 where id=? and collection_status='COLLECTED' and version=?",user,id,input.version())!=1)throw new BusinessException(ErrorCode.DIAGNOSTIC_VERSION_CONFLICT);audit(user,"SPECIMEN_RECEIVE","LAB_SPECIMEN",id);return specimen(id);}
  @Transactional public SpecimenView reject(long user,long id,RejectInput input){Map<String,Object>s=specimenForUpdate(id);requireExecutionScope(user,orderDepartment(num(s,"clinical_order_id")),"LAB");version(s,input.version());if(blank(input.reasonCode())||blank(input.reason())||!Set.of("PENDING_COLLECTION","COLLECTED","RECEIVED").contains(text(s,"collection_status")))throw new BusinessException(ErrorCode.DIAGNOSTIC_REQUIRED_FIELD);jdbc.update("update lab_specimen set collection_status='REJECTED',rejected_by=?,rejected_at=current_timestamp(3),rejection_reason_code=?,rejection_reason=?,version=version+1 where id=?",user,clean(input.reasonCode(),64),clean(input.reason(),512),id);audit(user,"SPECIMEN_REJECT","LAB_SPECIMEN",id);return specimen(id);}
  @Transactional public SpecimenView recollect(long user,long id){Map<String,Object>s=specimenForUpdate(id);requireExecutionScope(user,orderDepartment(num(s,"clinical_order_id")),"LAB");if(!"REJECTED".equals(text(s,"collection_status")))throw new BusinessException(ErrorCode.DIAGNOSTIC_INVALID_STATE);String no=no("SP");jdbc.update("insert into lab_specimen(specimen_no,clinical_order_id,patient_id,member_id,specimen_type,replaces_specimen_id) values(?,?,?,?,?,?)",no,num(s,"clinical_order_id"),num(s,"patient_id"),num(s,"member_id"),text(s,"specimen_type"),id);long next=id();audit(user,"SPECIMEN_RECOLLECT","LAB_SPECIMEN",next);return specimen(next);}

  @Transactional public ResultView enterResult(long user,ResultInput input){Map<String,Object>s=specimenForUpdate(input.specimenId());requireExecutionScope(user,orderDepartment(num(s,"clinical_order_id")),"LAB");String providerEventId=clean(input.providerEventId(),96);Map<String,Object> existing=jdbc.queryForList("select * from lab_result where provider_event_id=?",providerEventId).stream().findFirst().orElse(null);if(existing!=null){if(num(existing,"specimen_id")!=input.specimenId())throw new BusinessException(ErrorCode.DIAGNOSTIC_ACCESS_DENIED);return result(num(existing,"id"));}if(!"RECEIVED".equals(text(s,"collection_status")))throw new BusinessException(ErrorCode.DIAGNOSTIC_INVALID_STATE);if(input.items()==null||input.items().isEmpty())throw new BusinessException(ErrorCode.DIAGNOSTIC_REQUIRED_FIELD);String no=no("LR");jdbc.update("insert into lab_result(result_no,provider_event_id,clinical_order_id,specimen_id,patient_id,performed_at) values(?,?,?,?,?,current_timestamp(3))",no,providerEventId,num(s,"clinical_order_id"),input.specimenId(),num(s,"patient_id"));long rid=id();for(ResultItemInput i:input.items()){validResult(i);jdbc.update("insert into lab_result_item(lab_result_id,test_code,test_name_snapshot,value_type,numeric_value,text_value,unit_code,unit_name_snapshot,reference_low,reference_high,reference_text,abnormal_flag,critical_flag) values(?,?,?,?,?,?,?,?,?,?,?,?,?)",rid,clean(i.testCode(),64),clean(i.testName(),256),i.valueType(),i.numericValue(),clean(i.textValue(),2048),clean(i.unitCode(),32),clean(i.unitName(),64),i.referenceLow(),i.referenceHigh(),i.referenceText()==null?null:clean(i.referenceText(),256),i.abnormalFlag()==null?"NORMAL":i.abnormalFlag(),i.criticalFlag());}
    jdbc.update("update lab_specimen set collection_status='PROCESSING',version=version+1 where id=?",input.specimenId());audit(user,"RESULT_ENTER","LAB_RESULT",rid);return result(rid);}
  @Transactional public ResultView verifyResult(long user,long resultId){Map<String,Object>r=oneForUpdate("select * from lab_result where id=?",resultId);requireExecutionScope(user,orderDepartment(num(r,"clinical_order_id")),"LAB");if(!"PRELIMINARY".equals(text(r,"status")))throw new BusinessException(ErrorCode.DIAGNOSTIC_INVALID_STATE);Map<String,Object> o=one("select * from clinical_order where id=?",num(r,"clinical_order_id"));String reportNo=no("DR");jdbc.update("insert into diagnostic_report(report_no,clinical_order_id,patient_id,encounter_id,report_type,release_policy,status) values(?,?,?,?,?,?,'DRAFT')",reportNo,num(o,"id"),num(o,"patient_id"),num(o,"encounter_id"),"LAB",patientReleasePolicy);long report=id();String findings=labFindings(resultId);jdbc.update("insert into diagnostic_report_revision(report_id,revision_no,revision_type,findings,conclusion_text) values(?,1,'INITIAL',?,?)",report,findings,"检验结果已审核");long revision=id();signRevision(user,report,revision);jdbc.update("update lab_result set status='FINAL',verified_by=?,verified_at=current_timestamp(3),report_id=?,version=version+1 where id=?",user,report,resultId);jdbc.update("update lab_result_item set result_status='FINAL',verified_at=current_timestamp(3) where lab_result_id=?",resultId);jdbc.update("update lab_specimen set collection_status='COMPLETED',version=version+1 where id=?",num(r,"specimen_id"));jdbc.update("update clinical_order set status='COMPLETED',completed_at=current_timestamp(3),version=version+1 where id=?",num(r,"clinical_order_id"));createAlerts(resultId,o);audit(user,"RESULT_VERIFY","LAB_RESULT",resultId);return result(resultId);}

  public List<ReportView> patientReports(long patient){return jdbc.queryForList("select * from diagnostic_report where patient_id=? and status='FINAL' and released_at is not null order by issued_at desc",patient).stream().map(this::reportView).toList();}
  public PatientReport patientReport(long patient,long report){Map<String,Object>r=one("select * from diagnostic_report where id=? and patient_id=? and status='FINAL' and released_at is not null",report,patient);Map<String,Object>v=one("select * from diagnostic_report_revision where id=?",num(r,"current_revision_id"));List<Map<String,Object>> labs="LAB".equals(text(r,"report_type"))?jdbc.queryForList("select i.test_name_snapshot,i.value_type,i.numeric_value,i.text_value,i.unit_name_snapshot,i.reference_low,i.reference_high,i.reference_text,i.abnormal_flag from lab_result_item i join lab_result x on x.id=i.lab_result_id where x.report_id=?",report):List.of();return new PatientReport(num(r,"id"),text(r,"report_no"),text(r,"report_type"),instant(r.get("issued_at")),text(v,"findings"),text(v,"impression"),text(v,"conclusion_text"),labs);}
  public List<ReportView> pendingReports(long user){long doctor=doctor(user);return jdbc.queryForList("select r.* from diagnostic_report r join clinical_order o on o.id=r.clinical_order_id left join clinical_result_review v on v.report_id=r.id and v.doctor_id=? where o.doctor_id=? and r.status='FINAL' and v.id is null",doctor,doctor).stream().map(this::reportView).toList();}
  @Transactional public void review(long user,long report,Reason input){Map<String,Object>r=one("select r.* from diagnostic_report r join clinical_order o on o.id=r.clinical_order_id join visit_encounter e on e.id=o.encounter_id where r.id=? and o.doctor_id=? and r.status='FINAL'",report,doctor(user));if(blank(input.reason()))throw new BusinessException(ErrorCode.DIAGNOSTIC_REQUIRED_FIELD);try{jdbc.update("insert into clinical_result_review(report_id,doctor_id,encounter_id,reviewed_at,note) values(?,?,?,current_timestamp(3),?)",report,doctor(user),num(r,"encounter_id"),clean(input.reason(),512));}catch(org.springframework.dao.DuplicateKeyException e){throw new BusinessException(ErrorCode.DIAGNOSTIC_VERSION_CONFLICT);}if("AFTER_DOCTOR_REVIEW".equals(text(r,"release_policy")))jdbc.update("update diagnostic_report set released_at=current_timestamp(3),version=version+1 where id=? and released_at is null",report);audit(user,"RESULT_REVIEW","DIAGNOSTIC_REPORT",report);}
  @Transactional public AlertView acknowledge(long user,long alert,Reason input){Map<String,Object>a=oneForUpdate("select a.* from critical_result_alert a join clinical_order o on o.id=a.clinical_order_id where a.id=? and o.doctor_id=?",alert,doctor(user));if(blank(input.reason()))throw new BusinessException(ErrorCode.DIAGNOSTIC_REQUIRED_FIELD);if(jdbc.update("update critical_result_alert set status='ACKNOWLEDGED',acknowledged_by=?,acknowledged_at=current_timestamp(3),acknowledge_note=?,version=version+1 where id=? and status='NEW'",user,clean(input.reason(),512),alert)!=1)throw new BusinessException(ErrorCode.DIAGNOSTIC_VERSION_CONFLICT);audit(user,"CRITICAL_ACKNOWLEDGE","CRITICAL_ALERT",alert);return alert(alert);}
  public List<AlertView> alerts(long user){long doctor=doctor(user);return jdbc.queryForList("select a.* from critical_result_alert a join clinical_order o on o.id=a.clinical_order_id where o.doctor_id=? and a.status in ('NEW','NOTIFIED') order by a.detected_at",doctor).stream().map(this::alert).toList();}

  @Transactional public StudyView acquireStudy(long user,long orderId){if(!testProviderEnabled)throw new BusinessException(ErrorCode.CLINICAL_INTEGRATION_NOT_CONFIGURED);requireExecutionScope(user,orderDepartment(orderId),"IMAGING");Map<String,Object>s=oneForUpdate("select * from imaging_study where clinical_order_id=?",orderId);if(!"ORDERED".equals(text(s,"study_status")))throw new BusinessException(ErrorCode.DIAGNOSTIC_INVALID_STATE);jdbc.update("update imaging_study set study_status='ACQUIRED',performed_at=current_timestamp(3),external_study_uid=?,version=version+1 where id=?","TEST."+UUID.randomUUID(),num(s,"id"));jdbc.update("update clinical_order set status='IN_PROGRESS',started_at=current_timestamp(3),version=version+1 where id=? and status='PLACED'",orderId);audit(user,"IMAGING_ACQUIRE","IMAGING_STUDY",num(s,"id"));return study(num(s,"id"));}
  /** Both imaging roles receive only orders in their explicit clinical-execution scope. */
  public List<ImagingOrderView> imagingOrders(long user,String status){return jdbc.queryForList("select o.*,s.study_status,r.id report_id from clinical_order o join imaging_study s on s.clinical_order_id=o.id left join diagnostic_report r on r.clinical_order_id=o.id join clinical_execution_user_scope scope on scope.user_id=? and scope.department_id=o.department_id and scope.service_type='IMAGING' where o.order_type='IMAGING' and (?='' or o.status=?) order by o.id desc",user,status==null?"":status,status==null?"":status).stream().map(x->new ImagingOrderView(num(x,"id"),text(x,"order_no"),text(x,"status"),text(x,"study_status"),text(x,"priority"),number(x,"report_id"))).toList();}
  @Transactional public ReportView createImagingReport(long user,long orderId,ReportInput input){Map<String,Object>s=one("select * from imaging_study where clinical_order_id=?",orderId);requireExecutionScope(user,orderDepartment(orderId),"IMAGING");if(!"ACQUIRED".equals(text(s,"study_status"))||blank(input.findings()))throw new BusinessException(ErrorCode.DIAGNOSTIC_INVALID_STATE);Map<String,Object>o=one("select * from clinical_order where id=?",orderId);String no=no("DR");jdbc.update("insert into diagnostic_report(report_no,clinical_order_id,patient_id,encounter_id,report_type,release_policy,status) values(?,?,?,?,?,?,'DRAFT')",no,orderId,num(o,"patient_id"),num(o,"encounter_id"),"IMAGING",patientReleasePolicy);long report=id();jdbc.update("insert into diagnostic_report_revision(report_id,revision_no,revision_type,findings,impression,conclusion_text) values(?,1,'INITIAL',?,?,?)",report,clean(input.findings(),20000),clean(input.impression(),10000),clean(input.conclusion(),10000));long rev=id();jdbc.update("update diagnostic_report set current_revision_id=? where id=?",rev,report);audit(user,"REPORT_CREATE","DIAGNOSTIC_REPORT",report);return report(report);}
  @Transactional public ReportView signReport(long user,long reportId,VersionInput input){Map<String,Object>r=oneForUpdate("select * from diagnostic_report where id=?",reportId);requireExecutionScope(user,orderDepartment(num(r,"clinical_order_id")),text(r,"report_type"));version(r,input.version());Map<String,Object>v=oneForUpdate("select * from diagnostic_report_revision where id=?",num(r,"current_revision_id"));if(!"DRAFT".equals(text(r,"status")))throw new BusinessException(ErrorCode.DIAGNOSTIC_IMMUTABLE);signRevision(user,reportId,num(v,"id"));jdbc.update("update clinical_order set status='COMPLETED',completed_at=current_timestamp(3),version=version+1 where id=?",num(r,"clinical_order_id"));jdbc.update("update imaging_study set study_status='COMPLETED',version=version+1 where clinical_order_id=?",num(r,"clinical_order_id"));audit(user,"REPORT_SIGN","DIAGNOSTIC_REPORT",reportId);return report(reportId);}
  /** Only the current DRAFT revision can be edited; FINAL revisions are immutable even for their signer. */
  @Transactional public ReportView updateDraftReport(long user,long reportId,DraftReportInput input){Map<String,Object>r=oneForUpdate("select * from diagnostic_report where id=?",reportId);requireExecutionScope(user,orderDepartment(num(r,"clinical_order_id")),text(r,"report_type"));version(r,input.version());if(!"DRAFT".equals(text(r,"status"))||blank(input.findings()))throw new BusinessException(ErrorCode.DIAGNOSTIC_IMMUTABLE);Map<String,Object>v=oneForUpdate("select * from diagnostic_report_revision where id=?",num(r,"current_revision_id"));if(!"DRAFT".equals(text(v,"status")))throw new BusinessException(ErrorCode.DIAGNOSTIC_IMMUTABLE);jdbc.update("update diagnostic_report_revision set findings=?,impression=?,conclusion_text=?,version=version+1 where id=? and status='DRAFT'",clean(input.findings(),20000),clean(input.impression(),10000),clean(input.conclusion(),10000),num(v,"id"));if(jdbc.update("update diagnostic_report set version=version+1 where id=? and status='DRAFT' and version=?",reportId,input.version())!=1)throw new BusinessException(ErrorCode.DIAGNOSTIC_VERSION_CONFLICT);audit(user,"REPORT_DRAFT_UPDATE","DIAGNOSTIC_REPORT",reportId);return report(reportId);}
  @Transactional public ReportView amendReport(long user,long reportId,ReportInput input){Map<String,Object>r=oneForUpdate("select * from diagnostic_report where id=?",reportId);requireExecutionScope(user,orderDepartment(num(r,"clinical_order_id")),text(r,"report_type"));if(!"FINAL".equals(text(r,"status"))||blank(input.amendReason()))throw new BusinessException(ErrorCode.DIAGNOSTIC_INVALID_STATE);Map<String,Object>old=one("select * from diagnostic_report_revision where id=?",num(r,"current_revision_id"));int no=(int)num(old,"revision_no")+1;jdbc.update("insert into diagnostic_report_revision(report_id,revision_no,parent_revision_id,revision_type,findings,impression,conclusion_text,amend_reason) values(?,?,?,'AMENDMENT',?,?,?,?)",reportId,no,num(old,"id"),clean(input.findings(),20000),clean(input.impression(),10000),clean(input.conclusion(),10000),clean(input.amendReason(),512));long rev=id();jdbc.update("update diagnostic_report set status='DRAFT',current_revision_id=?,version=version+1 where id=?",rev,reportId);audit(user,"REPORT_AMEND","DIAGNOSTIC_REPORT",reportId);return report(reportId);}
  public ReportView executionReport(long user,long reportId){Map<String,Object>r=one("select * from diagnostic_report where id=?",reportId);requireExecutionScope(user,orderDepartment(num(r,"clinical_order_id")),text(r,"report_type"));return reportView(r);} public List<ReportRevisionView> reportHistory(long user,long reportId){Map<String,Object>r=one("select * from diagnostic_report where id=?",reportId);requireExecutionScope(user,orderDepartment(num(r,"clinical_order_id")),text(r,"report_type"));return jdbc.queryForList("select * from diagnostic_report_revision where report_id=? order by revision_no",reportId).stream().map(v->new ReportRevisionView(num(v,"id"),num(v,"revision_no"),text(v,"revision_type"),text(v,"status"),text(v,"findings"),text(v,"impression"),text(v,"conclusion_text"),text(v,"amend_reason"),number(v,"signed_by"),instant(v.get("signed_at")))).toList();}
  /** Audit access is intentionally limited to an already-finalized report and has no write path. */
  public ReportView auditReport(long reportId){return reportView(one("select * from diagnostic_report where id=? and status='FINAL'",reportId));}
  public boolean verifyReport(long user,long report){Map<String,Object>r=one("select r.* from diagnostic_report r join clinical_order o on o.id=r.clinical_order_id where r.id=? and o.doctor_id=?",report,doctor(user));Map<String,Object>v=one("select * from diagnostic_report_revision where id=?",num(r,"current_revision_id"));return "FINAL".equals(text(r,"status"))&&text(v,"content_hash").equals(reportHash(r,v));}

  @Transactional public ReportView releaseForPatient(long user,long reportId){Map<String,Object>r=one("select r.* from diagnostic_report r join clinical_order o on o.id=r.clinical_order_id where r.id=? and o.doctor_id=? and r.status='FINAL'",reportId,doctor(user));if(!"MANUAL_RELEASE".equals(text(r,"release_policy"))||r.get("released_at")!=null)throw new BusinessException(ErrorCode.DIAGNOSTIC_INVALID_STATE);jdbc.update("update diagnostic_report set released_at=current_timestamp(3),version=version+1 where id=? and released_at is null",reportId);audit(user,"REPORT_RELEASE","DIAGNOSTIC_REPORT",reportId);return report(reportId);}
  private void signRevision(long user,long report,long revision){Map<String,Object>r=oneForUpdate("select * from diagnostic_report where id=?",report);Map<String,Object>v=oneForUpdate("select * from diagnostic_report_revision where id=?",revision);String hash=reportHash(r,v);jdbc.update("update diagnostic_report_revision set status='FINAL',signed_by=?,signed_at=current_timestamp(3),content_hash=?,version=version+1 where id=?",user,hash,revision);jdbc.update("update diagnostic_report set status='FINAL',current_revision_id=?,issued_at=current_timestamp(3),released_at=case when release_policy='IMMEDIATE_AFTER_FINAL' then current_timestamp(3) else null end,version=version+1 where id=?",revision,report);}
  private void createAlerts(long result,Map<String,Object>o){for(Map<String,Object>i:jdbc.queryForList("select * from lab_result_item where lab_result_id=? and critical_flag=1",result)){jdbc.update("insert into critical_result_alert(result_item_id,patient_id,encounter_id,clinical_order_id,severity,source,trace_id,detected_at) values(?,?,?,?,?,?,?,current_timestamp(3))",num(i,"id"),num(o,"patient_id"),num(o,"encounter_id"),num(o,"id"),"TEST_CRITICAL","TestCriticalResultRuleProvider",TraceId.get());}}
  private long orderDepartment(long orderId){return num(one("select department_id from clinical_order where id=?",orderId),"department_id");} private void requireExecutionScope(long user,long department,String serviceType){if(jdbc.queryForObject("select count(*) from clinical_execution_user_scope where user_id=? and department_id=? and service_type=?",Long.class,user,department,serviceType)!=1)throw new BusinessException(ErrorCode.DIAGNOSTIC_ACCESS_DENIED);} private static String releasePolicy(String policy){return Set.of("IMMEDIATE_AFTER_FINAL","AFTER_DOCTOR_REVIEW","MANUAL_RELEASE").contains(policy)?policy:"MANUAL_RELEASE";}
  private Map<String,Object> doctorEncounter(long user,long id){return jdbc.queryForList("select e.* from visit_encounter e join doctor d on d.id=e.doctor_id where e.id=? and d.user_id=? and e.deleted=0",id,user).stream().findFirst().orElseThrow(()->new BusinessException(ErrorCode.DIAGNOSTIC_ACCESS_DENIED));}
  private Map<String,Object> doctorOrder(long user,long encounter,long id,boolean lock){doctorEncounter(user,encounter);return one("select * from clinical_order where id=? and encounter_id=?"+(lock?" for update":""),id,encounter);}
  private long signedRevision(long encounter){Long x=jdbc.query("select r.current_revision_id from outpatient_medical_record r join outpatient_medical_record_revision v on v.id=r.current_revision_id where r.encounter_id=? and v.status='SIGNED'",(rs,n)->rs.getLong(1),encounter).stream().findFirst().orElse(null);if(x==null)throw new BusinessException(ErrorCode.DIAGNOSTIC_REQUIRED_FIELD);return x;}
  private void requireConsulting(Map<String,Object>e){if(!"IN_CONSULTATION".equals(text(e,"status")))throw new BusinessException(ErrorCode.DIAGNOSTIC_INVALID_STATE);} private long doctor(long u){Long d=jdbc.query("select id from doctor where user_id=? and deleted=0 and status=1 and published=1",(rs,n)->rs.getLong(1),u).stream().findFirst().orElse(null);if(d==null)throw new BusinessException(ErrorCode.DIAGNOSTIC_ACCESS_DENIED);return d;}
  private Map<String,Object>one(String s,Object...a){return jdbc.queryForList(s,a).stream().findFirst().orElseThrow(()->new BusinessException(ErrorCode.NOT_FOUND));}private Map<String,Object>oneForUpdate(String s,Object...a){return one(s+" for update",a);}private Map<String,Object>specimenForUpdate(long id){return oneForUpdate("select * from lab_specimen where id=?",id);} private long id(){Long x=jdbc.queryForObject("select last_insert_id()",Long.class);if(x==null)throw new BusinessException(ErrorCode.SYSTEM);return x;}
  /** Test-only fixture failures are explicit, safe and retryable under the same business key. */
  private void testProviderFailure(long orderId,String key){String type=key.startsWith("provider74d-timeout")?"TIMEOUT":key.startsWith("provider74d-unknown")?"UNKNOWN_VENDOR_STATE_74D":null;if(type==null)return;Long seen=jdbc.queryForObject("select count(*) from clinical_integration_anomaly where clinical_order_id=? and external_reference=? and anomaly_type=?",Long.class,orderId,key,type);if(seen!=null&&seen>0)return;jdbc.update("insert into clinical_integration_anomaly(provider,anomaly_type,clinical_order_id,external_reference,detail_safe,trace_id) values('TestDiagnosticProvider',?,?,?,?,?)",type,orderId,key,"retryable test-provider outcome",TraceId.get());throw new ProviderPending();}
  private static final class ProviderPending extends BusinessException { ProviderPending(){super(ErrorCode.DIAGNOSTIC_INTEGRATION_PENDING);} }
  private OrderView order(long id){return orderView(one("select * from clinical_order where id=?",id));}private ProviderSubmission providerSubmission(Map<String,Object>o,String key){return new ProviderSubmission(num(o,"id"),text(o,"order_no"),key,"TEST-"+text(o,"order_type")+"-"+text(o,"order_no"));}private OrderView orderView(Map<String,Object>o){return new OrderView(num(o,"id"),text(o,"order_no"),text(o,"order_type"),text(o,"status"),text(o,"priority"),text(o,"clinical_indication"),num(o,"version"),items(o.get("id") instanceof Number n?n.longValue():num(o,"id")).stream().map(this::item).toList());} private List<Map<String,Object>>items(long id){return jdbc.queryForList("select * from clinical_order_item where clinical_order_id=? order by sort_order,id",id);}
  private ServiceItem service(Map<String,Object>x){return new ServiceItem(num(x,"id"),text(x,"service_code"),text(x,"service_name"),text(x,"service_type"),text(x,"specimen_type"),bool(x,"body_part_required"),bool(x,"laterality_required"));}private OrderItem item(Map<String,Object>x){return new OrderItem(num(x,"id"),text(x,"item_code_snapshot"),text(x,"item_name_snapshot"),text(x,"specimen_type_snapshot"),text(x,"body_part"),text(x,"laterality"));}
  private SpecimenView specimen(long id){return specimen(one("select * from lab_specimen where id=?",id));}private SpecimenView specimen(Map<String,Object>s){return new SpecimenView(num(s,"id"),text(s,"specimen_no"),num(s,"clinical_order_id"),text(s,"specimen_type"),text(s,"collection_status"),num(s,"version"));}
  private ResultView result(long id){Map<String,Object>r=one("select * from lab_result where id=?",id);return new ResultView(num(r,"id"),text(r,"result_no"),text(r,"status"),number(r,"report_id"),jdbc.queryForList("select * from lab_result_item where lab_result_id=?",id).stream().map(this::resultItem).toList());}private ResultItem resultItem(Map<String,Object>x){return new ResultItem(num(x,"id"),text(x,"test_code"),text(x,"test_name_snapshot"),decimal(x,"numeric_value"),text(x,"text_value"),text(x,"unit_name_snapshot"),decimal(x,"reference_low"),decimal(x,"reference_high"),text(x,"reference_text"),text(x,"abnormal_flag"),bool(x,"critical_flag"));}
  private ReportView report(long id){return reportView(one("select * from diagnostic_report where id=?",id));}private ReportView reportView(Map<String,Object>r){Map<String,Object>v=r.get("current_revision_id")==null?null:one("select * from diagnostic_report_revision where id=?",num(r,"current_revision_id"));return new ReportView(num(r,"id"),text(r,"report_no"),text(r,"report_type"),text(r,"status"),num(r,"version"),v==null?null:num(v,"id"),v==null?null:num(v,"revision_no"),v==null?null:text(v,"findings"),v==null?null:text(v,"impression"),v==null?null:text(v,"conclusion_text"));}private AlertView alert(long id){return alert(one("select * from critical_result_alert where id=?",id));}private AlertView alert(Map<String,Object>x){return new AlertView(num(x,"id"),text(x,"severity"),text(x,"status"),instant(x.get("detected_at")));}private StudyView study(long id){Map<String,Object>x=one("select * from imaging_study where id=?",id);return new StudyView(num(x,"id"),text(x,"study_no"),text(x,"study_status"),text(x,"accession_no"));}
  private String orderHash(Map<String,Object>o,List<Map<String,Object>>x){StringBuilder b=new StringBuilder();for(String k:List.of("encounter_id","patient_id","member_id","doctor_id","department_id","order_type","priority","clinical_indication"))b.append(k).append('=').append(text(o,k)).append('\n');for(Map<String,Object>i:x)b.append(text(i,"item_code_snapshot")).append('|').append(text(i,"body_part")).append('|').append(text(i,"laterality")).append('\n');return sha(b.toString());}private String reportHash(Map<String,Object>r,Map<String,Object>v){return sha(text(r,"report_type")+'|'+canonical(text(v,"findings"))+'|'+canonical(text(v,"impression"))+'|'+canonical(text(v,"conclusion_text")));}private String labFindings(long id){return String.join("\n",jdbc.queryForList("select test_name_snapshot,numeric_value,text_value,unit_name_snapshot from lab_result_item where lab_result_id=?",id).stream().map(x->text(x,"test_name_snapshot")+": "+(x.get("numeric_value")!=null?x.get("numeric_value"):text(x,"text_value"))+(text(x,"unit_name_snapshot")==null?"":" "+text(x,"unit_name_snapshot"))).toList());}
  private static String sha(String x){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(x.getBytes(StandardCharsets.UTF_8)));}catch(Exception e){throw new IllegalStateException(e);}} private static String no(String p){return p+UUID.randomUUID().toString().replace("-","").substring(0,24).toUpperCase(Locale.ROOT);}private static void version(Map<String,Object>x,long v){if(num(x,"version")!=v)throw new BusinessException(ErrorCode.DIAGNOSTIC_VERSION_CONFLICT);}private static void validOrder(String t,OrderInput x){if(x==null||!Set.of("LAB","IMAGING","EXAMINATION").contains(t)||x.serviceItemId()==null||blank(x.clinicalIndication())||x.clinicalIndication().length()>2048||!Set.of("ROUTINE","URGENT","STAT").contains(x.priority()==null?"ROUTINE":x.priority()))throw new BusinessException(ErrorCode.DIAGNOSTIC_REQUIRED_FIELD);}private static void validAnatomy(Map<String,Object>c,OrderInput x){if(bool(c,"body_part_required")&&blank(x.bodyPart())||bool(c,"laterality_required")&&blank(x.laterality()))throw new BusinessException(ErrorCode.DIAGNOSTIC_REQUIRED_FIELD);}private static void validResult(ResultItemInput x){if(x==null||blank(x.testCode())||blank(x.testName())||!Set.of("NUMERIC","TEXT","QUALITATIVE","BOOLEAN").contains(x.valueType())||("NUMERIC".equals(x.valueType())&&x.numericValue()==null)||(!"NUMERIC".equals(x.valueType())&&blank(x.textValue()))||x.numericValue()!=null&&x.numericValue().scale()>6)throw new BusinessException(ErrorCode.DIAGNOSTIC_REQUIRED_FIELD);}private void audit(long user,String a,String type,long id){jdbc.update("insert into clinical_diagnostic_audit(actor_id,action,resource_type,resource_id,trace_id) values(?,?,?,?,?)",user,a,type,id,TraceId.get());}
  private static long num(Map<String,Object>x,String k){return ((Number)x.get(k)).longValue();}private static Long number(Map<String,Object>x,String k){return x.get(k) instanceof Number n?n.longValue():null;}private static String text(Map<String,Object>x,String k){return x.get(k)==null?null:String.valueOf(x.get(k));}private static BigDecimal decimal(Map<String,Object>x,String k){return x.get(k)==null?null:new BigDecimal(x.get(k).toString());}private static boolean bool(Map<String,Object>x,String k){return x.get(k) instanceof Number n&&n.intValue()!=0;}private static Instant instant(Object x){return x instanceof Timestamp t?t.toInstant():x instanceof java.time.LocalDateTime t?t.toInstant(java.time.ZoneOffset.UTC):null;}private static String clean(String x,int n){return x==null?null:x.trim().length()>n?x.trim().substring(0,n):x.trim();}private static boolean blank(String x){return x==null||x.trim().isEmpty();}private static String canonical(String x){return x==null?"<NULL>":x.replace("\r\n","\n").replace('\r','\n');}
  public record ServiceItem(long id,String serviceCode,String serviceName,String serviceType,String specimenType,boolean bodyPartRequired,boolean lateralityRequired){} public record OrderInput(Long serviceItemId,String priority,String clinicalIndication,String bodyPart,String laterality,String instructions){} public record VersionInput(long version){} public record ProviderSubmissionInput(String businessKey){} public record ProviderSubmission(long orderId,String orderNo,String businessKey,String externalOrderId){} public record Reason(String reason){} public record RejectInput(long version,String reasonCode,String reason){} public record OrderItem(long id,String code,String name,String specimenType,String bodyPart,String laterality){} public record OrderView(long id,String orderNo,String type,String status,String priority,String clinicalIndication,long version,List<OrderItem> items){} public record SpecimenView(long id,String specimenNo,long orderId,String specimenType,String status,long version){} public record ResultItemInput(String testCode,String testName,String valueType,BigDecimal numericValue,String textValue,String unitCode,String unitName,BigDecimal referenceLow,BigDecimal referenceHigh,String referenceText,String abnormalFlag,boolean criticalFlag){} public record ResultInput(long specimenId,String providerEventId,List<ResultItemInput> items){} public record ResultItem(long id,String testCode,String testName,BigDecimal numericValue,String textValue,String unit,BigDecimal referenceLow,BigDecimal referenceHigh,String referenceText,String abnormalFlag,boolean critical){} public record ResultView(long id,String resultNo,String status,Long reportId,List<ResultItem> items){} public record ReportInput(String findings,String impression,String conclusion,String amendReason){} public record DraftReportInput(long version,String findings,String impression,String conclusion){} public record ReportView(long id,String reportNo,String type,String status,long version,Long revisionId,Long revisionNo,String findings,String impression,String conclusion){} public record ReportRevisionView(long id,long revisionNo,String revisionType,String status,String findings,String impression,String conclusion,String amendReason,Long signedBy,Instant signedAt){} public record PatientReport(long id,String reportNo,String type,Instant issuedAt,String findings,String impression,String conclusion,List<Map<String,Object>> labItems){} public record AlertView(long id,String severity,String status,Instant detectedAt){} public record StudyView(long id,String studyNo,String status,String accessionNo){} public record ImagingOrderView(long id,String orderNo,String status,String studyStatus,String priority,Long reportId){}
}
