package com.hospital.platform.file.application;
import com.hospital.platform.common.error.BusinessException; import com.hospital.platform.common.error.ErrorCode; import com.hospital.platform.common.security.AuthenticatedUser; import io.minio.*; import io.minio.http.Method; import java.io.InputStream; import java.security.MessageDigest; import java.util.HexFormat; import java.util.Set; import java.util.UUID; import org.springframework.beans.factory.annotation.Value; import org.springframework.jdbc.core.JdbcTemplate; import org.springframework.stereotype.Service; import org.springframework.web.multipart.MultipartFile;
@Service public class FileStorageService { private static final long MAX=10*1024*1024; private static final Set<String> ALLOWED=Set.of("image/jpeg","image/png","application/pdf","text/plain"); private final MinioClient minio; private final JdbcTemplate jdbc; private final String bucket;
 public FileStorageService(MinioClient minio,JdbcTemplate jdbc,@Value("${hospital.minio.bucket:hospital-private}") String bucket){this.minio=minio;this.jdbc=jdbc;this.bucket=bucket;}
 public FileView upload(MultipartFile f,AuthenticatedUser user)throws Exception{String ext=extension(f.getOriginalFilename());if(f.isEmpty()||f.getSize()>MAX||!ALLOWED.contains(f.getContentType())||!expectedType(ext).equals(f.getContentType())||!contentMatches(f,ext))throw new BusinessException(ErrorCode.FILE_INVALID);String key="system/"+UUID.randomUUID()+ext;ensureBucket();try(InputStream in=f.getInputStream()){minio.putObject(PutObjectArgs.builder().bucket(bucket).object(key).stream(in,f.getSize(),-1).contentType(f.getContentType()).build());}String hash=sha(f);jdbc.update("insert into sys_file(object_key,original_name,content_type,size_bytes,sha256,bucket_name,uploader_id) values(?,?,?,?,?,?,?)",key,safeName(f.getOriginalFilename()),f.getContentType(),f.getSize(),hash,bucket,user.id());Long id=jdbc.queryForObject("select id from sys_file where object_key=?",Long.class,key);return new FileView(Long.toString(id),safeName(f.getOriginalFilename()),f.getContentType(),f.getSize());}
 public String signedRead(long id)throws Exception{var row=jdbc.queryForMap("select object_key,bucket_name from sys_file where id=? and deleted=0",id);return minio.getPresignedObjectUrl(GetPresignedObjectUrlArgs.builder().bucket((String)row.get("bucket_name")).object((String)row.get("object_key")).method(Method.GET).expiry(5,java.util.concurrent.TimeUnit.MINUTES).build());}
 private void ensureBucket()throws Exception{if(!minio.bucketExists(BucketExistsArgs.builder().bucket(bucket).build()))minio.makeBucket(MakeBucketArgs.builder().bucket(bucket).build());} private String extension(String name){if(name==null)return "";int i=name.lastIndexOf('.');return i<0?"":name.substring(i).toLowerCase();} private String expectedType(String ext){return java.util.Map.of(".pdf","application/pdf",".png","image/png",".jpg","image/jpeg",".jpeg","image/jpeg",".txt","text/plain").getOrDefault(ext,"INVALID");} private boolean contentMatches(MultipartFile f,String ext)throws Exception{byte[] b;try(InputStream in=f.getInputStream()){b=in.readNBytes(8);}if(".pdf".equals(ext))return b.length>=5&&new String(b,0,5,java.nio.charset.StandardCharsets.US_ASCII).equals("%PDF-");if(".png".equals(ext))return b.length>=8&&java.util.Arrays.equals(b,new byte[]{(byte)137,80,78,71,13,10,26,10});if(".jpg".equals(ext)||".jpeg".equals(ext))return b.length>=3&&(b[0]&255)==255&&(b[1]&255)==216&&(b[2]&255)==255;if(".txt".equals(ext)){for(byte value:b)if(value==0)return false;return true;}return false;} private String safeName(String name){return name==null?"upload":name.replaceAll("[\\r\\n\\\\/]","_");} private String sha(MultipartFile f)throws Exception{try(InputStream i=f.getInputStream()){return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(i.readAllBytes()));}}
 public record FileView(String id,String originalName,String contentType,long sizeBytes){}
}
