package com.hospital.platform.visit;

import com.hospital.platform.common.error.BusinessException;
import com.hospital.platform.common.error.ErrorCode;
import com.hospital.platform.iam.application.DataScopeQueryService;
import java.util.*;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

/** Administrative facility data. Rooms are real master data, never a free-text schedule attribute. */
@Service public class ClinicRoomService {
  private final JdbcTemplate jdbc; private final DataScopeQueryService scopes;
  public ClinicRoomService(JdbcTemplate jdbc,DataScopeQueryService scopes){this.jdbc=jdbc;this.scopes=scopes;}
  public List<Map<String,Object>> list(long actor,Long outpatientDepartmentId){List<Long> allowed=scopes.visibleAdministrativeDepartmentIds(actor);if(allowed.isEmpty())return List.of();String marks=String.join(",",Collections.nCopies(allowed.size(),"?"));List<Object> args=new ArrayList<>(allowed);String filter=" r.deleted=0 and d.administrative_department_id in ("+marks+")";if(outpatientDepartmentId!=null){filter+=" and r.outpatient_department_id=?";args.add(outpatientDepartmentId);}return jdbc.queryForList("select r.id,r.campus_id campusId,r.building_id buildingId,r.floor_id floorId,r.outpatient_department_id outpatientDepartmentId,r.room_code roomCode,r.room_name roomName,r.room_number roomNumber,r.status,r.sort_order sortOrder,r.version from clinic_room r join outpatient_department od on od.id=r.outpatient_department_id join department d on d.id=od.department_id where "+filter+" order by r.sort_order,r.id",args.toArray());}
  @Transactional public long create(long actor,RoomRequest r){scope(actor,r.outpatientDepartmentId());valid(r);jdbc.update("insert into clinic_room(campus_id,building_id,floor_id,outpatient_department_id,room_code,room_name,room_number,status,sort_order,created_by,updated_by) values(?,?,?,?,?,?,?,?,?,?,?)",r.campusId(),r.buildingId(),r.floorId(),r.outpatientDepartmentId(),r.roomCode().trim(),r.roomName().trim(),r.roomNumber().trim(),r.status()?1:0,Math.max(0,r.sortOrder()),actor,actor);Long id=jdbc.queryForObject("select id from clinic_room where campus_id=? and room_code=?",Long.class,r.campusId(),r.roomCode().trim());return Objects.requireNonNull(id);}
  @Transactional public void update(long actor,long id,RoomRequest r){scope(actor,r.outpatientDepartmentId());valid(r);int changed=jdbc.update("update clinic_room set campus_id=?,building_id=?,floor_id=?,outpatient_department_id=?,room_code=?,room_name=?,room_number=?,status=?,sort_order=?,updated_by=?,version=version+1 where id=? and deleted=0 and version=?",r.campusId(),r.buildingId(),r.floorId(),r.outpatientDepartmentId(),r.roomCode().trim(),r.roomName().trim(),r.roomNumber().trim(),r.status()?1:0,Math.max(0,r.sortOrder()),actor,id,r.version());if(changed!=1)throw new BusinessException(ErrorCode.MASTER_CONFLICT);}
  @Transactional public void assignSchedule(long actor,long scheduleId,long roomId,int version){Map<String,Object>s=jdbc.queryForList("select s.outpatient_department_id outpatientDepartmentId from doctor_schedule s where s.id=? and s.deleted=0",scheduleId).stream().findFirst().orElseThrow(()->new BusinessException(ErrorCode.NOT_FOUND));scope(actor,((Number)s.get("outpatientDepartmentId")).longValue());Long valid=jdbc.queryForObject("select count(*) from clinic_room where id=? and outpatient_department_id=? and status=1 and deleted=0",Long.class,roomId,s.get("outpatientDepartmentId"));if(valid==null||valid==0)throw new BusinessException(ErrorCode.SCHEDULE_INVALID);int changed=jdbc.update("update doctor_schedule set clinic_room_id=?,version=version+1,updated_by=? where id=? and deleted=0 and schedule_status in ('DRAFT','PUBLISHED') and version=?",roomId,actor,scheduleId,version);if(changed!=1)throw new BusinessException(ErrorCode.SCHEDULE_INVALID);jdbc.update("update visit_encounter set clinic_room_id=?,version=version+1,updated_by=? where schedule_id=? and deleted=0 and status in ('WAITING','CALLED','IN_CONSULTATION')",roomId,actor,scheduleId);jdbc.update("update queue_ticket set clinic_room_id=?,version=version+1 where schedule_id=? and status in ('WAITING','CALLED','IN_SERVICE')",roomId,scheduleId);}
  private void scope(long actor,long outpatient){Long dept=jdbc.queryForObject("select d.administrative_department_id from outpatient_department od join department d on d.id=od.department_id where od.id=? and od.deleted=0 and d.deleted=0",Long.class,outpatient);if(dept==null||!scopes.visibleAdministrativeDepartmentIds(actor).contains(dept))throw new BusinessException(ErrorCode.FORBIDDEN);}
  private void valid(RoomRequest r){if(r==null||r.campusId()==null||r.buildingId()==null||r.floorId()==null||r.outpatientDepartmentId()==null||bad(r.roomCode(),32)||bad(r.roomName(),64)||bad(r.roomNumber(),32)||r.sortOrder()<0)throw new BusinessException(ErrorCode.VALIDATION);Long place=jdbc.queryForObject("select count(*) from hospital_floor f join hospital_building b on b.id=f.building_id where f.id=? and b.id=? and b.campus_id=? and f.deleted=0 and b.deleted=0",Long.class,r.floorId(),r.buildingId(),r.campusId());if(place==null||place==0)throw new BusinessException(ErrorCode.MASTER_INVALID);}
  private boolean bad(String value,int limit){return value==null||value.isBlank()||value.length()>limit||value.contains("<")||value.contains(">");}
  public record RoomRequest(Long campusId,Long buildingId,Long floorId,Long outpatientDepartmentId,String roomCode,String roomName,String roomNumber,boolean status,int sortOrder,int version){}
}
