package com.hospital.platform.visit;

import com.hospital.platform.common.error.BusinessException;
import com.hospital.platform.common.error.ErrorCode;
import com.hospital.platform.common.trace.TraceId;
import com.hospital.platform.clinical.ClinicalService;
import com.hospital.platform.iam.application.DataScopeQueryService;
import java.sql.Timestamp;
import java.time.*;
import java.util.*;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.dao.DuplicateKeyException;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

/** The only writer for encounter and queue state. Conditional updates make all externally retried actions idempotent. */
@Service public class OutpatientVisitService {
  private final JdbcTemplate jdbc; private final DataScopeQueryService scopes; private final ClinicalService clinical; private final int early,late,batch; private final String paymentPolicy; private final boolean requireSignedRecord;
  public OutpatientVisitService(JdbcTemplate jdbc,DataScopeQueryService scopes,ClinicalService clinical,@Value("${hospital.visit.checkin.early-minutes:120}")int early,@Value("${hospital.visit.checkin.late-minutes:240}")int late,@Value("${hospital.visit.checkin.payment-policy:REQUIRE_SETTLED}")String paymentPolicy,@Value("${hospital.visit.no-show.batch-size:100}")int batch,@Value("${hospital.clinical.encounter-complete.require-signed-record:true}")boolean requireSignedRecord){this.jdbc=jdbc;this.scopes=scopes;this.clinical=clinical;this.early=Math.max(0,early);this.late=Math.max(0,late);this.paymentPolicy=paymentPolicy==null?"REQUIRE_SETTLED":paymentPolicy;this.batch=Math.max(1,Math.min(500,batch));this.requireSignedRecord=requireSignedRecord;}
  @Transactional public QueueView checkInPatient(long patient,long appointmentId){return checkIn(patient,appointmentId,"PATIENT",false,null);}
  @Transactional public QueueView checkInStaff(long actor,long appointmentId,boolean paymentOverride,String reason){if(paymentOverride&&(reason==null||reason.isBlank()||reason.length()>512))throw new BusinessException(ErrorCode.VALIDATION);return checkIn(actor,appointmentId,"STAFF",paymentOverride,reason);}
  private QueueView checkIn(long actor,long appointmentId,String actorType,boolean override,String reason){Map<String,Object>a="PATIENT".equals(actorType)?jdbc.queryForList("select a.* from appointment a where a.id=? and a.patient_id=? and a.deleted=0",appointmentId,actor).stream().findFirst().orElseThrow(()->new BusinessException(ErrorCode.APPOINTMENT_NOT_OWNED)):scopedAppointment(actor,appointmentId);String status=String.valueOf(a.get("status"));if(!"BOOKED".equals(status))throw new BusinessException(ErrorCode.APPOINTMENT_INVALID_STATE);Map<String,Object>s=schedule(a);if(!"PUBLISHED".equals(String.valueOf(s.get("schedule_status"))))throw new BusinessException(ErrorCode.SCHEDULE_NOT_BOOKABLE);activePatientAndMember(a);checkWindow(s);checkPayment(a,s,override);List<Map<String,Object>> existing=jdbc.queryForList("select q.*,e.encounter_no encounterNo,e.status encounterStatus from queue_ticket q join visit_encounter e on e.id=q.encounter_id where e.appointment_id=?",appointmentId);if(!existing.isEmpty())return queueView(existing.getFirst());try{long sequence=nextSequence(num(a,"schedule_id"),date(s.get("schedule_date")));String no="E"+UUID.randomUUID().toString().replace("-","").substring(0,20).toUpperCase(Locale.ROOT);long doctor=num(s,"doctor_id");Long substitute=number(s,"substitute_doctor_id");if(substitute!=null)doctor=substitute;Long room=number(s,"clinic_room_id");long encounter=insertEncounter(no,a,s,doctor,room,actor);history(encounter,null,"WAITING","CHECK_IN",reason,actorType,actor);String queueNo="A"+String.format(Locale.ROOT,"%03d",sequence);jdbc.update("insert into queue_ticket(queue_no,encounter_id,schedule_id,doctor_id,department_id,outpatient_department_id,clinic_room_id,queue_date,status,queue_sequence,checkin_at) values(?,?,?,?,?,?,?,?,'WAITING',?,current_timestamp(3))",queueNo,encounter,num(a,"schedule_id"),doctor,num(s,"department_id"),num(s,"outpatient_department_id"),room,date(s.get("schedule_date")),sequence);Map<String,Object> q=jdbc.queryForMap("select q.*,e.encounter_no encounterNo,e.status encounterStatus from queue_ticket q join visit_encounter e on e.id=q.encounter_id where q.encounter_id=?",encounter);return queueView(q);}catch(DuplicateKeyException e){List<Map<String,Object>> after=jdbc.queryForList("select q.*,e.encounter_no encounterNo,e.status encounterStatus from queue_ticket q join visit_encounter e on e.id=q.encounter_id where e.appointment_id=?",appointmentId);if(!after.isEmpty())return queueView(after.getFirst());throw e;}}
  private long insertEncounter(String no,Map<String,Object>a,Map<String,Object>s,long doctor,Long room,long actor){jdbc.update("insert into visit_encounter(encounter_no,appointment_id,patient_id,member_id,doctor_id,department_id,outpatient_department_id,campus_id,schedule_id,slot_id,clinic_room_id,encounter_date,status,checked_in_at,waiting_at,created_by,updated_by) values(?,?,?,?,?,?,?,?,?,?,?,?,'WAITING',current_timestamp(3),current_timestamp(3),?,?)",no,num(a,"id"),num(a,"patient_id"),num(a,"member_id"),doctor,num(s,"department_id"),num(s,"outpatient_department_id"),num(s,"campus_id"),num(a,"schedule_id"),number(a,"slot_id"),room,date(s.get("schedule_date")),actor,actor);return Objects.requireNonNull(jdbc.queryForObject("select id from visit_encounter where appointment_id=?",Long.class,num(a,"id")));}
  @Transactional public QueueView callNext(long actor,long scheduleId){scopeSchedule(actor,scheduleId);return callNext(actor,scheduleId,"STAFF");}
  @Transactional public QueueView doctorCallNext(long userId,long scheduleId){long doctor=doctor(userId);Long matched=jdbc.queryForObject("select count(*) from doctor_schedule where id=? and coalesce(substitute_doctor_id,doctor_id)=? and schedule_date=current_date() and schedule_status='PUBLISHED' and deleted=0",Long.class,scheduleId,doctor);if(matched==null||matched==0)throw new BusinessException(ErrorCode.FORBIDDEN);return callNext(userId,scheduleId,"DOCTOR");}
  private QueueView callNext(long actor,long scheduleId,String actorType){for(int i=0;i<10;i++){List<Map<String,Object>> rows=jdbc.queryForList("select q.id,q.encounter_id from queue_ticket q where q.schedule_id=? and q.queue_date=current_date() and q.status='WAITING' order by case q.priority_code when 'URGENT' then 0 else 1 end,q.checkin_at,q.queue_sequence limit 1",scheduleId);if(rows.isEmpty())throw new BusinessException(ErrorCode.NOT_FOUND);Map<String,Object> row=rows.getFirst();if(jdbc.update("update queue_ticket set status='CALLED',called_at=current_timestamp(3),version=version+1 where id=? and status='WAITING'",num(row,"id"))==1){transition(num(row,"encounter_id"),"WAITING","CALLED","CALL",null,actorType,actor);return ticket(num(row,"encounter_id"));}}throw new BusinessException(ErrorCode.SYSTEM);}
  @Transactional public QueueView recall(long actor,long encounterId){return ticketTransition(actor,encounterId,"CALLED","CALLED","RECALL",null);}
  @Transactional public QueueView skip(long actor,long encounterId,String reason){requireReason(reason);return ticketTransition(actor,encounterId,"CALLED","SKIPPED","SKIP",reason);}
  @Transactional public QueueView returnToQueue(long actor,long encounterId,String reason){requireReason(reason);Map<String,Object> q=scopedTicket(actor,encounterId);if(!"SKIPPED".equals(q.get("status")))throw new BusinessException(ErrorCode.APPOINTMENT_INVALID_STATE);long sequence=nextSequence(num(q,"schedule_id"),date(q.get("queue_date")));if(jdbc.update("update queue_ticket set status='WAITING',queue_sequence=?,queue_no=?,version=version+1 where encounter_id=? and status='SKIPPED'",sequence,"A"+String.format(Locale.ROOT,"%03d",sequence),encounterId)!=1)throw new BusinessException(ErrorCode.APPOINTMENT_INVALID_STATE);transition(encounterId,"SKIPPED","WAITING","RETURN",reason,"STAFF",actor);return ticket(encounterId);}
  @Transactional public QueueView start(long userId,long encounterId){Map<String,Object> e=doctorEncounter(userId,encounterId);if(!"CALLED".equals(e.get("status")))throw new BusinessException(ErrorCode.APPOINTMENT_INVALID_STATE);Long active=jdbc.queryForObject("select count(*) from visit_encounter where doctor_id=? and encounter_date=? and status='IN_CONSULTATION' and deleted=0",Long.class,num(e,"doctor_id"),date(e.get("encounter_date")));if(active!=null&&active>0)throw new BusinessException(ErrorCode.APPOINTMENT_INVALID_STATE);if(jdbc.update("update queue_ticket set status='IN_SERVICE',service_started_at=current_timestamp(3),version=version+1 where encounter_id=? and status='CALLED'",encounterId)!=1)throw new BusinessException(ErrorCode.APPOINTMENT_INVALID_STATE);transition(encounterId,"CALLED","IN_CONSULTATION","START",null,"DOCTOR",userId);return ticket(encounterId);}
  @Transactional public QueueView complete(long userId,long encounterId){doctorEncounter(userId,encounterId);if(requireSignedRecord&&!clinical.hasSignedRecordForEncounter(encounterId))throw new BusinessException(ErrorCode.CLINICAL_REQUIRED_FIELD);if(jdbc.update("update queue_ticket set status='DONE',completed_at=current_timestamp(3),version=version+1 where encounter_id=? and status='IN_SERVICE'",encounterId)!=1)throw new BusinessException(ErrorCode.APPOINTMENT_INVALID_STATE);transition(encounterId,"IN_CONSULTATION","COMPLETED","COMPLETE",null,"DOCTOR",userId);return ticket(encounterId);}
  public List<Map<String,Object>> patientQueues(long patient){return jdbc.queryForList("select q.queue_no queueNo,q.status,q.priority_code priorityCode,q.queue_sequence queueSequence,e.encounter_no encounterNo,e.status encounterStatus,e.encounter_date encounterDate,dr.name doctorName,d.department_name departmentName,coalesce(r.room_name,r.room_number) roomName,(select count(*) from queue_ticket ahead where ahead.schedule_id=q.schedule_id and ahead.queue_date=q.queue_date and ahead.status='WAITING' and (ahead.checkin_at<q.checkin_at or (ahead.checkin_at=q.checkin_at and ahead.queue_sequence<q.queue_sequence))) aheadCount from queue_ticket q join visit_encounter e on e.id=q.encounter_id join doctor dr on dr.id=e.doctor_id join department d on d.id=e.department_id left join clinic_room r on r.id=q.clinic_room_id where e.patient_id=? and e.deleted=0 order by e.id desc",patient);}
  public List<Map<String,Object>> display(long scheduleId){return jdbc.queryForList("select q.queue_no queueNo,q.status,coalesce(r.room_name,r.room_number) roomName from queue_ticket q left join clinic_room r on r.id=q.clinic_room_id where q.schedule_id=? and q.queue_date=current_date() and q.status in ('WAITING','CALLED','IN_SERVICE') order by q.queue_sequence",scheduleId);}
  public List<Map<String,Object>> staffQueues(long actor,long scheduleId){scopeSchedule(actor,scheduleId);return jdbc.queryForList("select q.queue_no queueNo,q.status,q.priority_code priorityCode,q.queue_sequence queueSequence,q.encounter_id encounterId,coalesce(r.room_name,r.room_number) roomName from queue_ticket q left join clinic_room r on r.id=q.clinic_room_id where q.schedule_id=? and q.queue_date=current_date() order by q.queue_sequence",scheduleId);}
  public List<Map<String,Object>> doctorWorkbench(long userId){long doctor=doctor(userId);return jdbc.queryForList("select e.id encounterId,e.encounter_no encounterNo,e.status,q.queue_no queueNo,q.status queueStatus,q.queue_sequence queueSequence,q.schedule_id scheduleId,coalesce(r.room_name,r.room_number) roomName,a.appointment_no appointmentNo from visit_encounter e join queue_ticket q on q.encounter_id=e.id join appointment a on a.id=e.appointment_id left join clinic_room r on r.id=e.clinic_room_id where e.doctor_id=? and e.encounter_date=current_date() and e.deleted=0 order by case q.status when 'IN_SERVICE' then 0 when 'CALLED' then 1 else 2 end,q.queue_sequence",doctor);}
  @Transactional public Map<String,Object> doctorDetail(long userId,long encounterId){Map<String,Object> e=doctorEncounter(userId,encounterId);jdbc.update("insert into sys_audit_log(user_id,account_name,action,resource_type,resource_id,purpose,result,ip_address,request_path,trace_id) select ?,u.username,'VIEW','VISIT_ENCOUNTER',?,'DOCTOR_WORKBENCH','SUCCESS',null,'/api/v1/doctor/visits/',? from sys_user u where u.id=?",userId,String.valueOf(encounterId),TraceId.get(),userId);return Map.of("encounterNo",e.get("encounter_no"),"status",e.get("status"),"queue",ticket(encounterId));}
  @Scheduled(fixedDelayString="${hospital.visit.no-show.interval-ms:60000}") @Transactional public void markNoShows(){List<Map<String,Object>> rows=jdbc.queryForList("select a.*,s.schedule_date,s.end_time,coalesce(s.substitute_doctor_id,s.doctor_id) doctor_id,d.id department_id,s.outpatient_department_id,s.campus_id,s.clinic_room_id from appointment a join doctor_schedule s on s.id=a.schedule_id join outpatient_department od on od.id=s.outpatient_department_id join department d on d.id=od.department_id left join visit_encounter e on e.appointment_id=a.id where a.status='BOOKED' and a.deleted=0 and e.id is null and timestamp(s.schedule_date,s.end_time)<current_timestamp(3) order by a.id limit ?",batch);for(Map<String,Object>a:rows){try{String no="E"+UUID.randomUUID().toString().replace("-","").substring(0,20).toUpperCase(Locale.ROOT);long id=insertEncounter(no,a,a,num(a,"doctor_id"),number(a,"clinic_room_id"),0);if(jdbc.update("update visit_encounter set status='NO_SHOW' where id=? and status='WAITING'",id)==1)history(id,"WAITING","NO_SHOW","NO_SHOW",null,"SYSTEM",0L);}catch(DuplicateKeyException ignored){}}}
  private QueueView ticketTransition(long actor,long encounter,String expected,String target,String action,String reason){Map<String,Object> q=scopedTicket(actor,encounter);if(!expected.equals(q.get("status")))throw new BusinessException(ErrorCode.APPOINTMENT_INVALID_STATE);if(!expected.equals(target)&&jdbc.update("update queue_ticket set status=?,skipped_at=case when ?='SKIPPED' then current_timestamp(3) else skipped_at end,version=version+1 where encounter_id=? and status=?",target,target,encounter,expected)!=1)throw new BusinessException(ErrorCode.APPOINTMENT_INVALID_STATE);transition(encounter,expected,target,action,reason,"STAFF",actor);return ticket(encounter);}
  private void transition(long encounter,String before,String after,String action,String reason,String type,long actor){if(jdbc.update("update visit_encounter set status=?,called_at=case when ?='CALLED' then current_timestamp(3) else called_at end,started_at=case when ?='IN_CONSULTATION' then current_timestamp(3) else started_at end,completed_at=case when ?='COMPLETED' then current_timestamp(3) else completed_at end,version=version+1,updated_by=? where id=? and status=?",after,after,after,after,actor,encounter,before)!=1)throw new BusinessException(ErrorCode.APPOINTMENT_INVALID_STATE);history(encounter,before,after,action,reason,type,actor);}
  private void history(long encounter,String from,String to,String code,String reason,String type,long actor){jdbc.update("insert into visit_encounter_status_history(encounter_id,from_status,to_status,reason_code,reason,operator_type,operator_id,trace_id) values(?,?,?,?,?,?,?,?)",encounter,from,to,code,reason,type,actor,TraceId.get());}
  private void checkPayment(Map<String,Object>a,Map<String,Object>s,boolean override){if("ALLOW_UNPAID".equals(paymentPolicy)||override)return;Long required=jdbc.queryForObject("select count(*) from clinic_type ct where ct.id=? and ct.payment_required=1",Long.class,number(s,"clinic_type_id"));if(required!=null&&required>0){Long paid=jdbc.queryForObject("select count(*) from registration_order where appointment_id=? and status='PAID'",Long.class,num(a,"id"));if(paid==null||paid==0)throw new BusinessException(ErrorCode.APPOINTMENT_INVALID_STATE);}}
  private void checkWindow(Map<String,Object>s){ZoneId zone=ZoneId.of(String.valueOf(s.get("timezone")));LocalDateTime start=LocalDateTime.of(date(s.get("schedule_date")),time(s.get("start_time")));LocalDateTime now=LocalDateTime.now(zone);if(now.isBefore(start.minusMinutes(early))||now.isAfter(start.plusMinutes(late)))throw new BusinessException(ErrorCode.BOOKING_WINDOW_CLOSED);}
  private void activePatientAndMember(Map<String,Object>a){Long active=jdbc.queryForObject("select count(*) from patient p join patient_member m on m.id=? and m.patient_id=p.id where p.id=? and p.status=1 and p.deleted=0 and m.status='ACTIVE' and m.deleted=0",Long.class,num(a,"member_id"),num(a,"patient_id"));if(active==null||active==0)throw new BusinessException(ErrorCode.MEMBER_NOT_ELIGIBLE);}
  private Map<String,Object> schedule(Map<String,Object>a){return jdbc.queryForList("select s.*,d.id department_id,h.timezone from doctor_schedule s join outpatient_department od on od.id=s.outpatient_department_id join department d on d.id=od.department_id join hospital_campus c on c.id=s.campus_id join hospital h on h.id=c.hospital_id where s.id=? and s.deleted=0",num(a,"schedule_id")).stream().findFirst().orElseThrow(()->new BusinessException(ErrorCode.SCHEDULE_NOT_BOOKABLE));}
  private Map<String,Object> scopedAppointment(long actor,long id){Map<String,Object>a=jdbc.queryForList("select a.* from appointment a where a.id=? and a.deleted=0",id).stream().findFirst().orElseThrow(()->new BusinessException(ErrorCode.NOT_FOUND));scopeSchedule(actor,num(a,"schedule_id"));return a;}
  private Map<String,Object> scopedTicket(long actor,long encounter){Map<String,Object>q=jdbc.queryForList("select q.* from queue_ticket q where q.encounter_id=?",encounter).stream().findFirst().orElseThrow(()->new BusinessException(ErrorCode.NOT_FOUND));scopeSchedule(actor,num(q,"schedule_id"));return q;}
  private void scopeSchedule(long actor,long schedule){Long admin=jdbc.queryForObject("select d.administrative_department_id from doctor_schedule s join outpatient_department od on od.id=s.outpatient_department_id join department d on d.id=od.department_id where s.id=? and s.deleted=0",Long.class,schedule);if(admin==null||!scopes.visibleAdministrativeDepartmentIds(actor).contains(admin))throw new BusinessException(ErrorCode.FORBIDDEN);}
  private Map<String,Object> doctorEncounter(long user,long encounter){long doctor=doctor(user);Map<String,Object>e=jdbc.queryForList("select * from visit_encounter where id=? and doctor_id=? and deleted=0",encounter,doctor).stream().findFirst().orElseThrow(()->new BusinessException(ErrorCode.FORBIDDEN));return e;}
  private long doctor(long user){Long id=jdbc.queryForObject("select id from doctor where user_id=? and deleted=0 and status=1 and published=1",Long.class,user);if(id==null)throw new BusinessException(ErrorCode.FORBIDDEN);return id;}
  private long nextSequence(long schedule,LocalDate date){jdbc.update("insert into queue_sequence_counter(schedule_id,queue_date,next_sequence) values(?,?,2) on duplicate key update next_sequence=next_sequence+1",schedule,date);Integer next=jdbc.queryForObject("select next_sequence from queue_sequence_counter where schedule_id=? and queue_date=?",Integer.class,schedule,date);return Objects.requireNonNull(next)-1L;}
  private QueueView ticket(long encounter){return queueView(jdbc.queryForMap("select q.*,e.encounter_no encounterNo,e.status encounterStatus from queue_ticket q join visit_encounter e on e.id=q.encounter_id where q.encounter_id=?",encounter));}
  private QueueView queueView(Map<String,Object>q){return new QueueView(String.valueOf(q.get("encounterNo")),String.valueOf(q.get("queue_no")),String.valueOf(q.get("status")),String.valueOf(q.get("encounterStatus")),((Number)q.get("queue_sequence")).longValue(),q.get("clinic_room_id")==null?null:((Number)q.get("clinic_room_id")).longValue());}
  private long num(Map<String,Object>x,String key){return ((Number)x.get(key)).longValue();} private Long number(Map<String,Object>x,String key){Object v=x.get(key);return v==null?null:((Number)v).longValue();} private LocalDate date(Object x){return x instanceof java.sql.Date d?d.toLocalDate():x instanceof LocalDate d?d:LocalDate.parse(String.valueOf(x));} private LocalTime time(Object x){return x instanceof java.sql.Time t?t.toLocalTime():x instanceof LocalTime t?t:LocalTime.parse(String.valueOf(x));} private void requireReason(String s){if(s==null||s.isBlank()||s.length()>512)throw new BusinessException(ErrorCode.VALIDATION);}
  public record QueueView(String encounterNo,String queueNo,String queueStatus,String encounterStatus,long queueSequence,Long clinicRoomId){}
}
