package com.hospital.platform.masterdata;

import com.hospital.platform.common.api.ApiResponse;
import com.hospital.platform.common.api.PageResponse;
import com.hospital.platform.common.error.BusinessException;
import com.hospital.platform.common.error.ErrorCode;
import com.hospital.platform.common.security.AuthenticatedUser;
import com.hospital.platform.common.trace.TraceId;
import jakarta.validation.Valid;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.security.core.annotation.AuthenticationPrincipal;
import org.springframework.web.bind.annotation.*;

@RestController
public class MasterDataController {
  private final MasterDataService service; public MasterDataController(MasterDataService service){this.service=service;}
  @GetMapping("/api/v1/admin/master/hospitals") @PreAuthorize("hasAuthority('hospital:info:list')") public ApiResponse<List<Map<String,Object>>> hospitals(){return ok(service.hospitals(false));}
  @PostMapping("/api/v1/admin/master/hospitals") @PreAuthorize("hasAuthority('hospital:info:update')") public ApiResponse<Map<String,String>> createHospital(@Valid @RequestBody MasterDataService.HospitalRequest r,@AuthenticationPrincipal AuthenticatedUser user){return ok(Map.of("id",Long.toString(service.createHospital(r,user.id()))));}
  @PutMapping("/api/v1/admin/master/hospitals/{id}") @PreAuthorize("hasAuthority('hospital:info:update')") public ApiResponse<Void> updateHospital(@PathVariable long id,@RequestBody MasterDataService.HospitalRequest r,@AuthenticationPrincipal AuthenticatedUser user){service.updateHospital(id,r,user.id());return ok(null);}
  @GetMapping("/api/v1/admin/master/campuses") @PreAuthorize("hasAuthority('hospital:campus:list')") public ApiResponse<List<Map<String,Object>>> campuses(@RequestParam(required=false) Long hospitalId){return ok(service.campuses(hospitalId,false));}
  @PostMapping("/api/v1/admin/master/campuses") @PreAuthorize("hasAuthority('hospital:campus:manage')") public ApiResponse<Map<String,String>> createCampus(@RequestBody MasterDataService.CampusRequest r){return ok(Map.of("id",Long.toString(service.createCampus(r))));}
  @PutMapping("/api/v1/admin/master/campuses/{id}") @PreAuthorize("hasAuthority('hospital:campus:manage')") public ApiResponse<Void> updateCampus(@PathVariable long id,@RequestBody MasterDataService.CampusRequest r){service.updateCampus(id,r);return ok(null);}
  @GetMapping("/api/v1/admin/master/buildings") @PreAuthorize("hasAuthority('hospital:campus:list')") public ApiResponse<List<Map<String,Object>>> buildings(@RequestParam(required=false) Long campusId){return ok(service.buildings(campusId,false));}
  @PostMapping("/api/v1/admin/master/buildings") @PreAuthorize("hasAuthority('hospital:campus:manage')") public ApiResponse<Map<String,String>> createBuilding(@RequestBody MasterDataService.BuildingRequest r){return ok(Map.of("id",Long.toString(service.createBuilding(r))));}
  @PutMapping("/api/v1/admin/master/buildings/{id}") @PreAuthorize("hasAuthority('hospital:campus:manage')") public ApiResponse<Void> updateBuilding(@PathVariable long id,@RequestBody MasterDataService.BuildingRequest r){service.updateBuilding(id,r);return ok(null);}
  @GetMapping("/api/v1/admin/master/floors") @PreAuthorize("hasAuthority('hospital:campus:list')") public ApiResponse<List<Map<String,Object>>> floors(@RequestParam(required=false) Long buildingId){return ok(service.floors(buildingId,false));}
  @PostMapping("/api/v1/admin/master/floors") @PreAuthorize("hasAuthority('hospital:campus:manage')") public ApiResponse<Map<String,String>> createFloor(@RequestBody MasterDataService.FloorRequest r){return ok(Map.of("id",Long.toString(service.createFloor(r))));}
  @PutMapping("/api/v1/admin/master/floors/{id}") @PreAuthorize("hasAuthority('hospital:campus:manage')") public ApiResponse<Void> updateFloor(@PathVariable long id,@RequestBody MasterDataService.FloorRequest r){service.updateFloor(id,r);return ok(null);}
  @GetMapping("/api/v1/admin/master/departments") @PreAuthorize("hasAuthority('hospital:department:list')") public ApiResponse<List<Map<String,Object>>> departments(@AuthenticationPrincipal AuthenticatedUser user){return ok(service.departments(user.id(),false));}
  @PostMapping("/api/v1/admin/master/departments") @PreAuthorize("hasAuthority('hospital:department:manage')") public ApiResponse<Map<String,String>> createDepartment(@RequestBody MasterDataService.DepartmentRequest r,@AuthenticationPrincipal AuthenticatedUser user){service.assertAdministrativeDepartmentVisible(user.id(),r.administrativeDepartmentId());return ok(Map.of("id",Long.toString(service.createDepartment(r))));}
  @PutMapping("/api/v1/admin/master/departments/{id}") @PreAuthorize("hasAuthority('hospital:department:manage')") public ApiResponse<Void> updateDepartment(@PathVariable long id,@RequestBody MasterDataService.DepartmentRequest r,@AuthenticationPrincipal AuthenticatedUser user){service.assertAdministrativeDepartmentVisible(user.id(),r.administrativeDepartmentId());service.updateDepartment(id,r);return ok(null);}
  @GetMapping("/api/v1/admin/master/outpatient-departments") @PreAuthorize("hasAuthority('hospital:department:list')") public ApiResponse<List<Map<String,Object>>> outpatientDepartments(@RequestParam(required=false) Long departmentId){return ok(service.outpatientDepartments(departmentId,false));}
  @PostMapping("/api/v1/admin/master/outpatient-departments") @PreAuthorize("hasAuthority('hospital:department:manage')") public ApiResponse<Map<String,String>> createOutpatientDepartment(@RequestBody MasterDataService.OutpatientDepartmentRequest r){return ok(Map.of("id",Long.toString(service.createOutpatientDepartment(r))));}
  @PutMapping("/api/v1/admin/master/outpatient-departments/{id}") @PreAuthorize("hasAuthority('hospital:department:manage')") public ApiResponse<Void> updateOutpatientDepartment(@PathVariable long id,@RequestBody MasterDataService.OutpatientDepartmentRequest r){service.updateOutpatientDepartment(id,r);return ok(null);}
  @GetMapping("/api/v1/admin/master/{kind:titles|specialties|clinic-types}") @PreAuthorize("hasAuthority('hospital:title:manage') or hasAuthority('hospital:specialty:manage') or hasAuthority('hospital:clinic-type:manage')") public ApiResponse<List<Map<String,Object>>> catalogs(@PathVariable String kind){return ok(service.catalogs(kind,false));}
  @PostMapping("/api/v1/admin/master/{kind:titles|specialties|clinic-types}") @PreAuthorize("hasAuthority('hospital:title:manage') or hasAuthority('hospital:specialty:manage') or hasAuthority('hospital:clinic-type:manage')") public ApiResponse<Map<String,String>> createCatalog(@PathVariable String kind,@RequestBody MasterDataService.CatalogRequest r){return ok(Map.of("id",Long.toString(service.createCatalog(kind,r))));}
  @PutMapping("/api/v1/admin/master/{kind:titles|specialties|clinic-types}/{id}") @PreAuthorize("hasAuthority('hospital:title:manage') or hasAuthority('hospital:specialty:manage') or hasAuthority('hospital:clinic-type:manage')") public ApiResponse<Void> updateCatalog(@PathVariable String kind,@PathVariable long id,@RequestBody MasterDataService.CatalogRequest r){service.updateCatalog(kind,id,r);return ok(null);}
  @GetMapping("/api/v1/admin/master/doctors") @PreAuthorize("hasAuthority('hospital:doctor:list')") public ApiResponse<PageResponse<Map<String,Object>>> doctors(@AuthenticationPrincipal AuthenticatedUser user,@RequestParam(required=false) String keyword,@RequestParam(required=false) Long departmentId,@RequestParam(required=false) Long titleId,@RequestParam(defaultValue="1") long page,@RequestParam(defaultValue="20") long pageSize){return ok(service.doctors(user.id(),new MasterDataService.DoctorFilter(keyword,departmentId,titleId,page,pageSize),false));}
  @PostMapping("/api/v1/admin/master/doctors") @PreAuthorize("hasAuthority('hospital:doctor:manage')") public ApiResponse<Map<String,String>> createDoctor(@RequestBody MasterDataService.DoctorRequest r,@AuthenticationPrincipal AuthenticatedUser user){service.assertDoctorDepartmentsVisible(user.id(),r.departmentIds());return ok(Map.of("id",Long.toString(service.createDoctor(r))));}
  @PutMapping("/api/v1/admin/master/doctors/{id}") @PreAuthorize("hasAuthority('hospital:doctor:manage')") public ApiResponse<Void> updateDoctor(@PathVariable long id,@RequestBody MasterDataService.DoctorRequest r,@AuthenticationPrincipal AuthenticatedUser user){service.assertDoctorDepartmentsVisible(user.id(),r.departmentIds());service.updateDoctor(id,r);return ok(null);}
  @PostMapping("/api/v1/admin/master/doctors/{id}/publish") @PreAuthorize("hasAuthority('hospital:doctor:publish')") public ApiResponse<Void> publishDoctor(@PathVariable long id,@RequestBody PublishRequest r){service.setDoctorPublished(id,r.published(),r.version());return ok(null);}
  @PostMapping("/api/v1/admin/master/{resource:hospital|campus|building|floor|department|doctor|clinic-type|title|specialty}/{id}/disable") @PreAuthorize("hasAuthority('hospital:doctor:manage') or hasAuthority('hospital:department:manage') or hasAuthority('hospital:campus:manage')") public ApiResponse<Void> disable(@PathVariable String resource,@PathVariable long id){service.disable(resource,id);return ok(null);}

  @GetMapping("/api/v1/public/hospital") public ApiResponse<Map<String,Object>> publicHospital(){return ok(service.hospitals(true).stream().findFirst().map(this::publicHospitalView).orElse(null));}
  @GetMapping("/api/v1/public/campuses") public ApiResponse<List<Map<String,Object>>> publicCampuses(){return ok(service.campuses(null,true).stream().map(this::publicCampusView).toList());}
  @GetMapping("/api/v1/public/campuses/{id}") public ApiResponse<Map<String,Object>> publicCampus(@PathVariable long id){return ok(publicCampusView(required(service.campuses(null,true).stream().filter(x->longValue(x,"id")==id).findFirst().orElse(null))));}
  @GetMapping("/api/v1/public/departments") public ApiResponse<List<Map<String,Object>>> publicDepartments(){return ok(service.departments(0,true).stream().map(this::publicDepartmentView).toList());}
  @GetMapping("/api/v1/public/departments/{id}") public ApiResponse<Map<String,Object>> publicDepartment(@PathVariable long id){return ok(publicDepartmentView(required(service.departments(0,true).stream().filter(x->longValue(x,"id")==id).findFirst().orElse(null))));}
  @GetMapping("/api/v1/public/outpatient-departments") public ApiResponse<List<Map<String,Object>>> publicOutpatientDepartments(@RequestParam(required=false) Long departmentId){return ok(service.outpatientDepartments(departmentId,true).stream().map(row->fields(row,"id","departmentId","clinicTypeId","name","description")).toList());}
  @GetMapping("/api/v1/public/doctors") public ApiResponse<PageResponse<Map<String,Object>>> publicDoctors(@RequestParam(required=false) String keyword,@RequestParam(required=false) Long departmentId,@RequestParam(required=false) Long titleId,@RequestParam(defaultValue="1") long page,@RequestParam(defaultValue="20") long pageSize){var source=service.doctors(0,new MasterDataService.DoctorFilter(keyword,departmentId,titleId,page,pageSize),true);return ok(new PageResponse<>(source.page(),source.pageSize(),source.total(),source.records().stream().map(this::publicDoctorView).toList()));}
  @GetMapping("/api/v1/public/doctors/{id}") public ApiResponse<Map<String,Object>> publicDoctor(@PathVariable long id){return ok(service.publicDoctor(id));}
  @GetMapping("/api/v1/public/clinic-types") public ApiResponse<List<Map<String,Object>>> publicClinicTypes(){return ok(service.catalogs("clinic-types",true));}
  @GetMapping("/api/v1/public/files/{id}/url") public ApiResponse<Map<String,String>> publicFile(@PathVariable long id)throws Exception{return ok(Map.of("url",service.publicFileUrl(id)));}
  private Map<String,Object> publicHospitalView(Map<String,Object> row){return fields(row,"id","hospitalCode","name","shortName","logoFileId","hospitalLevel","hospitalType","introduction","telephone","serviceHotline","officialWebsite","address","longitude","latitude","postalCode","businessHours");}
  private Map<String,Object> publicCampusView(Map<String,Object> row){return fields(row,"id","hospitalId","campusCode","name","shortName","address","telephone","longitude","latitude","transportation","parkingInfo","businessHours");}
  private Map<String,Object> publicDepartmentView(Map<String,Object> row){return fields(row,"id","hospitalId","campusId","parentId","departmentCode","name","shortName","category","introduction","specialtyDescription","telephone","locationDescription","buildingId","floorId","logoFileId","doctorCount");}
  private Map<String,Object> publicDoctorView(Map<String,Object> row){return fields(row,"id","name","avatarFileId","titleId","title","profile","education","medicalExperience","specialtySummary","consultationNotice","departments","specialties");}
  private Map<String,Object> fields(Map<String,Object> source,String...names){Map<String,Object> result=new LinkedHashMap<>();for(String name:names)result.put(name,source.get(name));return result;}
  private static long longValue(Map<String,Object> row,String key){return ((Number)row.get(key)).longValue();} private static <T>T required(T value){if(value==null)throw new BusinessException(ErrorCode.NOT_FOUND);return value;} private static <T>ApiResponse<T> ok(T value){return ApiResponse.success(value,TraceId.get());}
  public record PublishRequest(boolean published,int version){}
}
