package com.hospital.platform.masterdata;

import com.hospital.platform.common.api.PageResponse;
import com.hospital.platform.common.error.BusinessException;
import com.hospital.platform.common.error.ErrorCode;
import com.hospital.platform.file.application.FileStorageService;
import com.hospital.platform.iam.application.DataScopeQueryService;
import java.util.ArrayList;
import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import org.springframework.dao.DuplicateKeyException;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

/** STEP 3 master data application service. Clinical departments deliberately remain separate from sys_department. */
@Service
public class MasterDataService {
  private final JdbcTemplate jdbc; private final DataScopeQueryService scopes; private final FileStorageService files;
  public MasterDataService(JdbcTemplate jdbc, DataScopeQueryService scopes, FileStorageService files){this.jdbc=jdbc;this.scopes=scopes;this.files=files;}

  public List<Map<String,Object>> hospitals(boolean onlyPublic){return jdbc.queryForList("select id,hospital_code hospitalCode,name,short_name shortName,logo_file_id logoFileId,hospital_level hospitalLevel,hospital_type hospitalType,introduction,telephone,service_hotline serviceHotline,official_website officialWebsite,address,longitude,latitude,postal_code postalCode,business_hours businessHours,status,sort_order sortOrder,published,version from hospital where deleted=0"+(onlyPublic?" and status=1 and published=1":"")+" order by sort_order,id");}
  @Transactional public long createHospital(HospitalRequest r,long actor){plain(r.name());plain(r.introduction());try{jdbc.update("insert into hospital(hospital_code,name,short_name,logo_file_id,hospital_level,hospital_type,introduction,telephone,service_hotline,official_website,address,longitude,latitude,postal_code,business_hours,status,sort_order,published,created_by,updated_by) values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",r.code(),r.name(),r.shortName(),r.logoFileId(),r.hospitalLevel(),r.hospitalType(),r.introduction(),r.telephone(),r.serviceHotline(),r.officialWebsite(),r.address(),r.longitude(),r.latitude(),r.postalCode(),r.businessHours(),enabled(r.status()),sort(r.sortOrder()),flag(r.published()),actor,actor);return id("select id from hospital where hospital_code=?",r.code());}catch(DuplicateKeyException e){throw new BusinessException(ErrorCode.MASTER_CONFLICT);}}
  @Transactional public void updateHospital(long id,HospitalRequest r,long actor){plain(r.name());plain(r.introduction());int n=jdbc.update("update hospital set name=?,short_name=?,logo_file_id=?,hospital_level=?,hospital_type=?,introduction=?,telephone=?,service_hotline=?,official_website=?,address=?,longitude=?,latitude=?,postal_code=?,business_hours=?,status=?,sort_order=?,published=?,updated_by=?,version=version+1 where id=? and deleted=0 and version=?",r.name(),r.shortName(),r.logoFileId(),r.hospitalLevel(),r.hospitalType(),r.introduction(),r.telephone(),r.serviceHotline(),r.officialWebsite(),r.address(),r.longitude(),r.latitude(),r.postalCode(),r.businessHours(),enabled(r.status()),sort(r.sortOrder()),flag(r.published()),actor,id,r.version());requireUpdated(n);}

  public List<Map<String,Object>> campuses(Long hospitalId,boolean onlyPublic){String sql="select id,hospital_id hospitalId,campus_code campusCode,name,short_name shortName,address,telephone,longitude,latitude,transportation,parking_info parkingInfo,business_hours businessHours,status,sort_order sortOrder,published,version from hospital_campus where deleted=0"+(hospitalId==null?"":" and hospital_id=?")+(onlyPublic?" and status=1 and published=1":"")+" order by sort_order,id";return hospitalId==null?jdbc.queryForList(sql):jdbc.queryForList(sql,hospitalId);}
  @Transactional public long createCampus(CampusRequest r){exists("hospital",r.hospitalId());try{jdbc.update("insert into hospital_campus(hospital_id,campus_code,name,short_name,address,telephone,longitude,latitude,transportation,parking_info,business_hours,status,sort_order,published) values(?,?,?,?,?,?,?,?,?,?,?,?,?,?)",r.hospitalId(),r.code(),r.name(),r.shortName(),r.address(),r.telephone(),r.longitude(),r.latitude(),plainValue(r.transportation()),plainValue(r.parkingInfo()),r.businessHours(),enabled(r.status()),sort(r.sortOrder()),flag(r.published()));return id("select id from hospital_campus where hospital_id=? and campus_code=?",r.hospitalId(),r.code());}catch(DuplicateKeyException e){throw new BusinessException(ErrorCode.MASTER_CONFLICT);}}
  @Transactional public void updateCampus(long id,CampusRequest r){exists("hospital",r.hospitalId());int n=jdbc.update("update hospital_campus set hospital_id=?,name=?,short_name=?,address=?,telephone=?,longitude=?,latitude=?,transportation=?,parking_info=?,business_hours=?,status=?,sort_order=?,published=?,version=version+1 where id=? and deleted=0 and version=?",r.hospitalId(),r.name(),r.shortName(),r.address(),r.telephone(),r.longitude(),r.latitude(),plainValue(r.transportation()),plainValue(r.parkingInfo()),r.businessHours(),enabled(r.status()),sort(r.sortOrder()),flag(r.published()),id,r.version());requireUpdated(n);}

  public List<Map<String,Object>> buildings(Long campusId,boolean onlyPublic){String sql="select id,campus_id campusId,building_code buildingCode,name,description,map_reference mapReference,status,sort_order sortOrder,published,version from hospital_building where deleted=0"+(campusId==null?"":" and campus_id=?")+(onlyPublic?" and status=1 and published=1":"")+" order by sort_order,id";return campusId==null?jdbc.queryForList(sql):jdbc.queryForList(sql,campusId);}
  @Transactional public long createBuilding(BuildingRequest r){exists("hospital_campus",r.campusId());try{jdbc.update("insert into hospital_building(campus_id,building_code,name,description,map_reference,status,sort_order,published) values(?,?,?,?,?,?,?,?)",r.campusId(),r.code(),r.name(),plainValue(r.description()),r.mapReference(),enabled(r.status()),sort(r.sortOrder()),flag(r.published()));return id("select id from hospital_building where campus_id=? and building_code=?",r.campusId(),r.code());}catch(DuplicateKeyException e){throw new BusinessException(ErrorCode.MASTER_CONFLICT);}}
  @Transactional public void updateBuilding(long id,BuildingRequest r){exists("hospital_campus",r.campusId());int n=jdbc.update("update hospital_building set campus_id=?,name=?,description=?,map_reference=?,status=?,sort_order=?,published=?,version=version+1 where id=? and deleted=0 and version=?",r.campusId(),r.name(),plainValue(r.description()),r.mapReference(),enabled(r.status()),sort(r.sortOrder()),flag(r.published()),id,r.version());requireUpdated(n);}
  public List<Map<String,Object>> floors(Long buildingId,boolean onlyPublic){String sql="select id,building_id buildingId,floor_code floorCode,floor_name floorName,floor_number floorNumber,description,map_reference mapReference,status,sort_order sortOrder,published,version from hospital_floor where deleted=0"+(buildingId==null?"":" and building_id=?")+(onlyPublic?" and status=1 and published=1":"")+" order by floor_number,sort_order,id";return buildingId==null?jdbc.queryForList(sql):jdbc.queryForList(sql,buildingId);}
  @Transactional public long createFloor(FloorRequest r){exists("hospital_building",r.buildingId());try{jdbc.update("insert into hospital_floor(building_id,floor_code,floor_name,floor_number,description,map_reference,status,sort_order,published) values(?,?,?,?,?,?,?,?,?)",r.buildingId(),r.code(),r.name(),r.floorNumber(),plainValue(r.description()),r.mapReference(),enabled(r.status()),sort(r.sortOrder()),flag(r.published()));return id("select id from hospital_floor where building_id=? and floor_code=?",r.buildingId(),r.code());}catch(DuplicateKeyException e){throw new BusinessException(ErrorCode.MASTER_CONFLICT);}}
  @Transactional public void updateFloor(long id,FloorRequest r){exists("hospital_building",r.buildingId());int n=jdbc.update("update hospital_floor set building_id=?,floor_name=?,floor_number=?,description=?,map_reference=?,status=?,sort_order=?,published=?,version=version+1 where id=? and deleted=0 and version=?",r.buildingId(),r.name(),r.floorNumber(),plainValue(r.description()),r.mapReference(),enabled(r.status()),sort(r.sortOrder()),flag(r.published()),id,r.version());requireUpdated(n);}

  public List<Map<String,Object>> departments(long actor,boolean onlyPublic){List<Long> allowed=onlyPublic?List.of():scopes.visibleAdministrativeDepartmentIds(actor);String visible=onlyPublic?"":allowed.isEmpty()?" and 1=0":" and d.administrative_department_id in ("+marks(allowed.size())+")";String sql="select d.id,d.hospital_id hospitalId,d.campus_id campusId,d.parent_id parentId,d.organization_id organizationId,d.administrative_department_id administrativeDepartmentId,d.department_code departmentCode,d.department_name name,d.short_name shortName,d.category,d.introduction,d.specialty_description specialtyDescription,d.telephone,d.location_description locationDescription,d.building_id buildingId,d.floor_id floorId,d.logo_file_id logoFileId,d.status,d.published,d.sort_order sortOrder,d.version,(select count(*) from doctor_department dd join doctor x on x.id=dd.doctor_id where dd.department_id=d.id and dd.status=1 and x.status=1 and x.published=1 and x.deleted=0) doctorCount from department d where d.deleted=0"+(onlyPublic?" and d.status=1 and d.published=1":"")+visible+" order by d.sort_order,d.id";return allowed.isEmpty()&& !onlyPublic?jdbc.queryForList(sql):jdbc.queryForList(sql,allowed.toArray());}
  @Transactional public long createDepartment(DepartmentRequest r){exists("hospital",r.hospitalId());if(r.parentId()!=null){exists("department",r.parentId());}plain(r.name());plain(r.introduction());try{jdbc.update("insert into department(organization_id,administrative_department_id,hospital_id,campus_id,parent_id,department_code,department_name,short_name,category,introduction,specialty_description,telephone,location_description,building_id,floor_id,logo_file_id,status,published,sort_order) values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",r.organizationId(),r.administrativeDepartmentId(),r.hospitalId(),r.campusId(),r.parentId(),r.code(),r.name(),r.shortName(),r.category(),r.introduction(),r.specialtyDescription(),r.telephone(),r.locationDescription(),r.buildingId(),r.floorId(),r.logoFileId(),enabled(r.status()),flag(r.published()),sort(r.sortOrder()));return id("select id from department where organization_id=? and department_code=?",r.organizationId(),r.code());}catch(DuplicateKeyException e){throw new BusinessException(ErrorCode.MASTER_CONFLICT);}}
  @Transactional public void updateDepartment(long id,DepartmentRequest r){exists("hospital",r.hospitalId());if(r.parentId()!=null){exists("department",r.parentId());if(r.parentId()==id||isDescendant(r.parentId(),id))throw new BusinessException(ErrorCode.MASTER_INVALID);}int n=jdbc.update("update department set organization_id=?,administrative_department_id=?,hospital_id=?,campus_id=?,parent_id=?,department_name=?,short_name=?,category=?,introduction=?,specialty_description=?,telephone=?,location_description=?,building_id=?,floor_id=?,logo_file_id=?,status=?,published=?,sort_order=?,version=version+1 where id=? and deleted=0 and version=?",r.organizationId(),r.administrativeDepartmentId(),r.hospitalId(),r.campusId(),r.parentId(),r.name(),r.shortName(),r.category(),plainValue(r.introduction()),plainValue(r.specialtyDescription()),r.telephone(),r.locationDescription(),r.buildingId(),r.floorId(),r.logoFileId(),enabled(r.status()),flag(r.published()),sort(r.sortOrder()),id,r.version());requireUpdated(n);}
  private boolean isDescendant(long candidate,long root){Long count=jdbc.queryForObject("with recursive tree as (select id,parent_id from department where id=? and deleted=0 union all select d.id,d.parent_id from department d join tree t on d.parent_id=t.id where d.deleted=0) select count(*) from tree where id=?",Long.class,root,candidate);return count!=null&&count>0;}

  public List<Map<String,Object>> outpatientDepartments(Long departmentId,boolean onlyPublic){String sql="select id,department_id departmentId,clinic_type_id clinicTypeId,name,description,status,sort_order sortOrder,published,version from outpatient_department where deleted=0"+(departmentId==null?"":" and department_id=?")+(onlyPublic?" and status=1 and published=1":"")+" order by sort_order,id";return departmentId==null?jdbc.queryForList(sql):jdbc.queryForList(sql,departmentId);}
  @Transactional public long createOutpatientDepartment(OutpatientDepartmentRequest r){exists("department",r.departmentId());if(r.clinicTypeId()!=null)exists("clinic_type",r.clinicTypeId());plain(r.name());try{jdbc.update("insert into outpatient_department(department_id,clinic_type_id,outpatient_code,name,description,status,sort_order,published) values(?,?,?,?,?,?,?,?)",r.departmentId(),r.clinicTypeId(),r.code(),r.name(),plainValue(r.description()),enabled(r.status()),sort(r.sortOrder()),flag(r.published()));return id("select id from outpatient_department where outpatient_code=?",r.code());}catch(DuplicateKeyException e){throw new BusinessException(ErrorCode.MASTER_CONFLICT);}}
  @Transactional public void updateOutpatientDepartment(long id,OutpatientDepartmentRequest r){exists("department",r.departmentId());if(r.clinicTypeId()!=null)exists("clinic_type",r.clinicTypeId());plain(r.name());int n=jdbc.update("update outpatient_department set department_id=?,clinic_type_id=?,name=?,description=?,status=?,sort_order=?,published=?,version=version+1 where id=? and deleted=0 and version=?",r.departmentId(),r.clinicTypeId(),r.name(),plainValue(r.description()),enabled(r.status()),sort(r.sortOrder()),flag(r.published()),id,r.version());requireUpdated(n);}

  public List<Map<String,Object>> catalogs(String kind,boolean onlyPublic){Catalog c=catalog(kind);return jdbc.queryForList("select id,code,name,"+c.extra+" description,status,sort_order sortOrder,published,version from "+c.table+" where deleted=0"+(onlyPublic?" and status=1 and published=1":"")+" order by sort_order,id");}
  @Transactional public long createCatalog(String kind,CatalogRequest r){Catalog c=catalog(kind);plain(r.name());try{jdbc.update("insert into "+c.table+"(code,name,"+c.extra+",status,sort_order,published) values(?,?,?,?,?,?)",r.code(),r.name(),r.description(),enabled(r.status()),sort(r.sortOrder()),flag(r.published()));return id("select id from "+c.table+" where code=?",r.code());}catch(DuplicateKeyException e){throw new BusinessException(ErrorCode.MASTER_CONFLICT);}}
  @Transactional public void updateCatalog(String kind,long id,CatalogRequest r){Catalog c=catalog(kind);int n=jdbc.update("update "+c.table+" set name=?,"+c.extra+"=?,status=?,sort_order=?,published=?,version=version+1 where id=? and deleted=0 and version=?",r.name(),plainValue(r.description()),enabled(r.status()),sort(r.sortOrder()),flag(r.published()),id,r.version());requireUpdated(n);}

  public PageResponse<Map<String,Object>> doctors(long actor,DoctorFilter f,boolean onlyPublic){List<Long> allowed=onlyPublic?List.of():scopes.visibleAdministrativeDepartmentIds(actor);String scope=onlyPublic?"":allowed.isEmpty()?" and 1=0":" and exists(select 1 from doctor_department scope_dd join department scope_d on scope_d.id=scope_dd.department_id where scope_dd.doctor_id=d.id and scope_dd.status=1 and scope_d.deleted=0 and scope_d.administrative_department_id in ("+marks(allowed.size())+"))";List<Object> args=new ArrayList<>(allowed);String where=" d.deleted=0"+(onlyPublic?" and d.status=1 and d.published=1":"")+scope;if(f.departmentId()!=null){where+=" and exists(select 1 from doctor_department filterdd where filterdd.doctor_id=d.id and filterdd.department_id=? and filterdd.status=1)";args.add(f.departmentId());}if(f.titleId()!=null){where+=" and d.title_id=?";args.add(f.titleId());}if(f.keyword()!=null&&!f.keyword().isBlank()){where+=" and (d.name like ? or d.doctor_no like ?)";args.add("%"+f.keyword()+"%");args.add("%"+f.keyword()+"%");}long page=Math.max(1,f.page()),size=Math.min(100,Math.max(1,f.pageSize()));Long total=jdbc.queryForObject("select count(*) from doctor d where "+where,Long.class,args.toArray());List<Object> pageArgs=new ArrayList<>(args);pageArgs.add(size);pageArgs.add((page-1)*size);String sql="select d.id,d.doctor_no doctorNo,d.name,d.gender,d.avatar_file_id avatarFileId,d.title_id titleId,t.name title,d.profile,d.education,d.medical_experience medicalExperience,d.specialty_summary specialtySummary,d.consultation_notice consultationNotice,d.status,d.published,d.sort_order sortOrder,d.version from doctor d left join doctor_title t on t.id=d.title_id and t.deleted=0 where "+where+" order by d.sort_order,d.id limit ? offset ?";List<Map<String,Object>> rows=jdbc.queryForList(sql,pageArgs.toArray());if(!rows.isEmpty())attachDoctorRelations(rows,onlyPublic);return new PageResponse<>(page,size,total==null?0:total,rows);}
  public Map<String,Object> publicDoctor(long doctorId){
    List<Map<String,Object>> rows=jdbc.queryForList("select d.id,d.name,d.avatar_file_id avatarFileId,d.title_id titleId,t.name title,d.profile,d.education,d.medical_experience medicalExperience,d.specialty_summary specialtySummary,d.consultation_notice consultationNotice from doctor d left join doctor_title t on t.id=d.title_id and t.deleted=0 where d.id=? and d.deleted=0 and d.status=1 and d.published=1",doctorId);
    if(rows.isEmpty()) throw new BusinessException(ErrorCode.NOT_FOUND);
    attachDoctorRelations(rows,true);
    return rows.get(0);
  }
  private void attachDoctorRelations(List<Map<String,Object>> doctors,boolean onlyPublic){List<Long> ids=doctors.stream().map(x->((Number)x.get("id")).longValue()).toList();String marks=String.join(",",Collections.nCopies(ids.size(),"?"));List<Map<String,Object>> departments=jdbc.queryForList("select dd.doctor_id doctorId,d.id,d.department_name name,dd.is_primary isPrimary from doctor_department dd join department d on d.id=dd.department_id where dd.doctor_id in ("+marks+") and dd.status=1 and d.deleted=0"+(onlyPublic?" and d.status=1 and d.published=1":""),ids.toArray());List<Map<String,Object>> specialties=jdbc.queryForList("select ds.doctor_id doctorId,s.id,s.name from doctor_specialty ds join medical_specialty s on s.id=ds.specialty_id where ds.doctor_id in ("+marks+") and s.deleted=0"+(onlyPublic?" and s.status=1 and s.published=1":"")+" order by ds.sort_order,s.id",ids.toArray());for(Map<String,Object> doctor:doctors){long id=((Number)doctor.get("id")).longValue();doctor.put("departments",departments.stream().filter(x->((Number)x.get("doctorId")).longValue()==id).toList());doctor.put("specialties",specialties.stream().filter(x->((Number)x.get("doctorId")).longValue()==id).toList());}}
  @Transactional public long createDoctor(DoctorRequest r){validateDoctor(r);try{jdbc.update("insert into doctor(doctor_no,user_id,name_ciphertext,name,gender,avatar_file_id,title_id,profile,education,medical_experience,specialty_summary,consultation_notice,status,published,sort_order) values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",r.doctorNo(),r.userId(),r.name(),r.name(),r.gender(),r.avatarFileId(),r.titleId(),plainValue(r.profile()),plainValue(r.education()),plainValue(r.medicalExperience()),plainValue(r.specialtySummary()),plainValue(r.consultationNotice()),enabled(r.status()),flag(r.published()),sort(r.sortOrder()));long id=id("select id from doctor where doctor_no=?",r.doctorNo());replaceDoctorRelations(id,r);return id;}catch(DuplicateKeyException e){throw new BusinessException(ErrorCode.MASTER_CONFLICT);}}
  @Transactional public void updateDoctor(long id,DoctorRequest r){validateDoctor(r);int n=jdbc.update("update doctor set user_id=?,name=?,gender=?,avatar_file_id=?,title_id=?,profile=?,education=?,medical_experience=?,specialty_summary=?,consultation_notice=?,status=?,published=?,sort_order=?,version=version+1 where id=? and deleted=0 and version=?",r.userId(),r.name(),r.gender(),r.avatarFileId(),r.titleId(),plainValue(r.profile()),plainValue(r.education()),plainValue(r.medicalExperience()),plainValue(r.specialtySummary()),plainValue(r.consultationNotice()),enabled(r.status()),flag(r.published()),sort(r.sortOrder()),id,r.version());requireUpdated(n);replaceDoctorRelations(id,r);}
  @Transactional public void setDoctorPublished(long id,boolean published,long version){int n=jdbc.update("update doctor set published=?,version=version+1 where id=? and deleted=0 and version=?",flag(published),id,version);requireUpdated(n);}
  private void validateDoctor(DoctorRequest r){plain(r.name());plain(r.profile());if(r.titleId()!=null)exists("doctor_title",r.titleId());if(r.departmentIds()==null||r.departmentIds().isEmpty())throw new BusinessException(ErrorCode.MASTER_INVALID);if(r.primaryDepartmentId()==null||!r.departmentIds().contains(r.primaryDepartmentId()))throw new BusinessException(ErrorCode.MASTER_INVALID);for(Long departmentId:r.departmentIds())exists("department",departmentId);if(r.specialtyIds()!=null)for(Long specialtyId:r.specialtyIds())exists("medical_specialty",specialtyId);}
  private void replaceDoctorRelations(long doctorId,DoctorRequest r){jdbc.update("delete from doctor_department where doctor_id=?",doctorId);for(Long d:r.departmentIds())jdbc.update("insert into doctor_department(doctor_id,department_id,relation_type,is_primary,sort_order) values(?,?,?,?,?)",doctorId,d,"MEMBER",d.equals(r.primaryDepartmentId())?1:0,0);jdbc.update("delete from doctor_specialty where doctor_id=?",doctorId);if(r.specialtyIds()!=null)for(Long s:r.specialtyIds())jdbc.update("insert into doctor_specialty(doctor_id,specialty_id,sort_order) values(?,?,?)",doctorId,s,0);}

  @Transactional public void disable(String resource,long id){String table=switch(resource){case "hospital"->"hospital";case "campus"->"hospital_campus";case "building"->"hospital_building";case "floor"->"hospital_floor";case "department"->"department";case "doctor"->"doctor";case "clinic-type"->"clinic_type";case "title"->"doctor_title";case "specialty"->"medical_specialty";default->throw new BusinessException(ErrorCode.MASTER_INVALID);};if(resource.equals("campus")&&children("hospital_building","campus_id",id)>0||resource.equals("building")&&children("hospital_floor","building_id",id)>0||resource.equals("department")&&children("department","parent_id",id)>0)throw new BusinessException(ErrorCode.MASTER_CONFLICT);if(jdbc.update("update "+table+" set status=0,published=0,version=version+1 where id=? and deleted=0",id)!=1)throw new BusinessException(ErrorCode.NOT_FOUND);}
  public void assertAdministrativeDepartmentVisible(long actorId,Long administrativeDepartmentId){if(administrativeDepartmentId==null||!scopes.visibleAdministrativeDepartmentIds(actorId).contains(administrativeDepartmentId))throw new BusinessException(ErrorCode.FORBIDDEN);}
  public void assertDoctorDepartmentsVisible(long actorId,List<Long> departmentIds){List<Long> visible=scopes.visibleAdministrativeDepartmentIds(actorId);if(departmentIds==null||departmentIds.isEmpty())throw new BusinessException(ErrorCode.MASTER_INVALID);for(Long departmentId:departmentIds){Long administrativeDepartmentId=jdbc.queryForObject("select administrative_department_id from department where id=? and deleted=0",Long.class,departmentId);if(administrativeDepartmentId==null||!visible.contains(administrativeDepartmentId))throw new BusinessException(ErrorCode.FORBIDDEN);}}
  private long children(String table,String column,long id){Long n=jdbc.queryForObject("select count(*) from "+table+" where "+column+"=? and deleted=0",Long.class,id);return n==null?0:n;}
  public String publicFileUrl(long id)throws Exception{Long count=jdbc.queryForObject("select count(*) from doctor where avatar_file_id=? and status=1 and published=1 and deleted=0",Long.class,id);if(count==null||count==0)count=jdbc.queryForObject("select count(*) from hospital where logo_file_id=? and status=1 and published=1 and deleted=0",Long.class,id);if(count==null||count==0)count=jdbc.queryForObject("select count(*) from department where logo_file_id=? and status=1 and published=1 and deleted=0",Long.class,id);if(count==null||count==0)throw new BusinessException(ErrorCode.NOT_FOUND);return files.signedRead(id);}
  private String marks(int n){return String.join(",",Collections.nCopies(n,"?"));}
  // Scope predicates require their data-scope ids as SQL parameters. Administrators with no scope see no mapped records; unassigned records remain visible only to explicitly scoped administrators through master-data assignment.
  private void exists(String table,Long id){if(id==null)throw new BusinessException(ErrorCode.MASTER_INVALID);Long n=jdbc.queryForObject("select count(*) from "+table+" where id=? and deleted=0",Long.class,id);if(n==null||n==0)throw new BusinessException(ErrorCode.MASTER_INVALID);}
  private long id(String sql,Object...args){Long id=jdbc.queryForObject(sql,Long.class,args);if(id==null)throw new BusinessException(ErrorCode.NOT_FOUND);return id;}
  private void requireUpdated(int n){if(n==0)throw new BusinessException(ErrorCode.MASTER_CONFLICT);}
  private int enabled(Boolean v){return v==null||v?1:0;} private int flag(Boolean v){return Boolean.TRUE.equals(v)?1:0;} private int sort(Integer v){return v==null?0:Math.max(0,Math.min(100000,v));}
  private void plain(String value){if(value==null||value.isBlank()||value.contains("<")||value.contains(">"))throw new BusinessException(ErrorCode.MASTER_INVALID);} private String plainValue(String value){if(value!=null&&(value.contains("<")||value.contains(">")))throw new BusinessException(ErrorCode.MASTER_INVALID);return value;}
  private Catalog catalog(String kind){return switch(kind){case "titles"->new Catalog("doctor_title","description");case "specialties"->new Catalog("medical_specialty","description");case "clinic-types"->new Catalog("clinic_type","description");default->throw new BusinessException(ErrorCode.MASTER_INVALID);};}
  private record Catalog(String table,String extra){}
  public record HospitalRequest(String code,String name,String shortName,Long logoFileId,String hospitalLevel,String hospitalType,String introduction,String telephone,String serviceHotline,String officialWebsite,String address,java.math.BigDecimal longitude,java.math.BigDecimal latitude,String postalCode,String businessHours,Boolean status,Integer sortOrder,Boolean published,int version){}
  public record CampusRequest(Long hospitalId,String code,String name,String shortName,String address,String telephone,java.math.BigDecimal longitude,java.math.BigDecimal latitude,String transportation,String parkingInfo,String businessHours,Boolean status,Integer sortOrder,Boolean published,int version){}
  public record BuildingRequest(Long campusId,String code,String name,String description,String mapReference,Boolean status,Integer sortOrder,Boolean published,int version){}
  public record FloorRequest(Long buildingId,String code,String name,int floorNumber,String description,String mapReference,Boolean status,Integer sortOrder,Boolean published,int version){}
  public record DepartmentRequest(Long organizationId,Long administrativeDepartmentId,Long hospitalId,Long campusId,Long parentId,String code,String name,String shortName,String category,String introduction,String specialtyDescription,String telephone,String locationDescription,Long buildingId,Long floorId,Long logoFileId,Boolean status,Integer sortOrder,Boolean published,int version){}
  public record OutpatientDepartmentRequest(Long departmentId,Long clinicTypeId,String code,String name,String description,Boolean status,Integer sortOrder,Boolean published,int version){}
  public record CatalogRequest(String code,String name,String description,Boolean status,Integer sortOrder,Boolean published,int version){}
  public record DoctorRequest(String doctorNo,Long userId,String name,String gender,Long avatarFileId,Long titleId,String profile,String education,String medicalExperience,String specialtySummary,String consultationNotice,Boolean status,Integer sortOrder,Boolean published,List<Long> departmentIds,Long primaryDepartmentId,List<Long> specialtyIds,int version){}
  public record DoctorFilter(String keyword,Long departmentId,Long titleId,long page,long pageSize){}
}
